Fix parameter list expansion by making SQLParserUtils platform aware
doctrine/dbal pull request #2296
Opened 2016-01-12 18:04 UTC by deeky666

fixes #2295

@Ocramius @zeroedin-bill Ideas about how to test this properly without having to completely rewrite `Doctrine\Tests\DBAL\SQLParserUtilsTest` are welcome. Also I don't see a reasonable way how to test the changes in the connection as `SQLParserUtils` is called statically.

@maryo also please test if that fixes your problem if you have time to.

2016-01-12 18:06 UTC, maryo commented
That's really great you are working on it! :+1: 
I made a quick workarround to satisfy the issue i described. But OFC your solution is the solution.

https://github.com/vaniocz/dbal/commit/0dcfbbab9b232a138b477a3a7d24b743cc869937

At least i added very simple test scenario.

2016-01-12 18:10 UTC, deeky666 commented
@maryo thanks for investigation on this. Theoretically I need to test everything that already is present with every available platform. This would be quite some work to achieve so I am first asking for ideas of a simpler solution before doing the effort :)

2016-01-12 19:55 UTC, deeky666 commented on lib/Doctrine/DBAL/SQLParserUtils.php
> +                if ($platform instanceof SQLServerPlatform) {
Btw another misconception in the platform. SQL Server has different quote characters for start and end, therefore the platform returns `"` here as a workaround :>

2016-01-12 20:19 UTC, maryo commented on lib/Doctrine/DBAL/SQLParserUtils.php
> +                if ($platform instanceof SQLServerPlatform) {
Looks like `SQLServerPlatform` does not override `getIdentifierQuoteCharacter` so the `AbstractPlatform` implementation is used which is `return '"'`. Does it really makes sense for `SQLServerPlatform`? Could't it be modified to return `[`? It's still not ideal but it makes more sense. Then the $quoteCharacterClass could be set to `preg_quote($platform->getIdentifierQuoteCharacter())`

2016-01-12 20:22 UTC, deeky666 commented on lib/Doctrine/DBAL/SQLParserUtils.php
> +                if ($platform instanceof SQLServerPlatform) {
@maryo I don't think it makes much sense as we cannot profit from it. Applications not knowing that it's SQL Server will assume it is also the ending quote character and still generate invalid SQL. IIRC it is possible to enable ANSI quotes in SQL Server so in that case `"` would work.
Won't open another can here. For now it is only about the platform awareness that's all. Everything else will be addressed in `3.0`

2016-01-12 20:33 UTC, maryo commented on lib/Doctrine/DBAL/SQLParserUtils.php
> +                if ($platform instanceof SQLServerPlatform) {
If `"` can be valid then you're right :)

2016-01-13 12:22 UTC, maryo commented
"also please test if that fixes your problem if you have time to."
@deeky666 I've just replaced my workarround with your fix uxing "doctrine/dbal":"dev-DBAL-2295 as 2.6.x-dev". It works fine.

2016-01-13 12:40 UTC, deeky666 commented
@maryo thank you for testing this. Now the only things that's left is figuring out how to add tests properly...

2016-09-04 14:33 UTC, maryo commented
Since nobody contributed since that time I wanted to complete the tests but you are right - it's tricky to test this implementation properly since it expects actual implementations of AbstractPlatform and contains those conditions and so the test would need to reflect it also. And since there is no possibility in PHPUnit to chain/merge data providers it would be very ugly.

So I created another PR https://github.com/doctrine/dbal/pull/2496 which solves just the exact problem I had just using negative look behind.

2016-09-09 18:49 UTC, Ocramius commented
@maryo since @deeky666 didn't get to check your diff yet, I will have to delay this (removed milestone)

2017-07-23 01:09 UTC, lcobucci requested changes
Patch looks good, just some small things

2017-07-23 01:09 UTC, lcobucci commented on lib/Doctrine/DBAL/Connection.php
> +                list($query, $params, $types) = SQLParserUtils::expandListParameters(
`[$query, $params, $types]`

2017-07-23 01:09 UTC, lcobucci commented on lib/Doctrine/DBAL/Connection.php
> +                list($query, $params, $types) = SQLParserUtils::expandListParameters(
`[$query, $params, $types]`

2017-07-23 01:09 UTC, lcobucci commented on lib/Doctrine/DBAL/SQLParserUtils.php
> +    static public function getPlaceholderPositions(
`public static`

2017-07-23 01:09 UTC, lcobucci commented on lib/Doctrine/DBAL/SQLParserUtils.php
> +    static public function expandListParameters($query, $params, $types, AbstractPlatform $platform = null)
`public static`

2017-07-23 01:09 UTC, lcobucci commented on lib/Doctrine/DBAL/SQLParserUtils.php
> +    static private function getUnquotedStatementFragments($statement, AbstractPlatform $platform = null)
`private static`

2017-07-23 01:09 UTC, lcobucci commented on lib/Doctrine/DBAL/SQLParserUtils.php
> +    static private function getUnquotedStatementFragments($statement, AbstractPlatform $platform = null)
Since it's a private method we can add the type declarations and use `?AbstractPlatform $platform` instead of `AbstractPlatform $platform = null`

2020-11-30 02:42 UTC, closed without merging