[SQLite Platform] doctrine:database:create --if-not-exists fix
doctrine/dbal pull request #2402
Opened 2016-05-22 19:28 UTC by eugene-matvejev

2016-05-22 20:06 UTC, mikeSimonson commented on lib/Doctrine/DBAL/Platforms/SqlitePlatform.php
> +        return 'PRAGMA databases';
In sqlite the PRAGMA is "database_list" not "databases".
You will need to fix the tests and verify that the ouput of that PRAGMA is comparable to the output of the others platforms.

2016-06-04 10:20 UTC, eugene-matvejev commented
I tried fix it, basically PRAGMA database_list return test/master while database file been create in tests/travis directory

whenever I launch it with command:
./vendor/bin/phpunit --configuration tests/travis/sqlite.travis.xml

test_create_database file been created in root, but 
```

    public function testListDatabases()
    {
        if (!$this->_sm->getDatabasePlatform()->supportsCreateDropDatabase()) {
            $this->markTestSkipped('Cannot drop Database client side with this Driver.');
        }

        $this->_sm->dropAndCreateDatabase('test_create_database');
        $databases = $this->_sm->listDatabases();
        /** left for debug purposes */
        $databases_ = [];
        foreach ($databases as $database) {
            $databases_[] = is_array($database) ? strtolower($database['name']) : $database;
        }

        $this->assertContains('test_create_database', $databases_);
    }
``

$databases content: ```
Array
(
    [0] => Array
        (
            [seq] => 0
            [name] => main
            [file] => 
        )
    [1] => Array
        (
            [seq] => 1
            [name] => temp
            [file] => 
        )
)
```


i presume it should detect test_create_database file , what I am doing wrong? I didn't catch =/

2016-07-17 01:44 UTC, eugene-matvejev commented
bump!

2016-07-24 15:24 UTC, eugene-matvejev commented
@mikeSimonson seems you have more experience with SQLIte than me, can you please help?

2017-08-13 17:33 UTC, sharif9876 commented
Any updates on this? It's still an issue

2017-08-13 18:38 UTC, Ocramius requested changes

2017-08-13 18:38 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Functional/Schema/SqliteSchemaManagerTest.php
> +    // /**
If it's dead, it should be removed

2017-08-13 18:38 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Functional/Schema/SchemaManagerFunctionalTestCase.php
> +        /** left for debug purposes */
Remove - debugging stuff only while debugging please

2017-08-13 18:38 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Functional/Schema/SchemaManagerFunctionalTestCase.php
> +        $this->assertContains('test_create_database', $databases_);
The return format of `SchemaManager#listDatabases()` changed: that is a BC break.

2017-08-13 18:38 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Functional/Schema/SchemaManagerFunctionalTestCase.php
> -        $databases = array_map('strtolower', $databases);
Please DO ADD a test to demonstrate your issue, rather than modifying existing tests.

2019-05-30 16:36 UTC, ostrolucky commented
Closing, as author never got around to finish this. If you ever intend to finish this, feel free to open new PR. Thanks!

2019-05-30 16:36 UTC, closed without merging