Add immutable date types
doctrine/dbal pull request #2450
Opened 2016-07-15 13:52 UTC by deeky666

As we have bumped PHP requirement to 5.6+ in 2.6, we now can finally add immutable variants of date types.

Closes #1882

2016-07-21 15:48 UTC, Deltachaos commented
If we would merge #2362 and #2365 we could try to re use the platform methods to to generate the immutable objects. Currently we have a lot of code duplication here. This could be reduced in my opinion. Additionaly i dont see anything that holds #2362 from getting merged.

2016-07-22 07:00 UTC, deeky666 commented
@Deltachaos I don't see how merging those PRs helps with reusability as those deal with mutable `\DateTime` objects. We would have to introduced another 8! methods to `AbstractPlatform` which makes it 16! new methods overall already. While I see the advantage with your other PRs, I am still not happy with adding some many new methods to the platform (which is public API and has to be maintained afterwards!).

2016-07-22 08:54 UTC, Deltachaos commented
@deeky666 you could reuse the methods in ``AbstractPlatform`` and convert the result into a immutable object by ``DateTimeImmutable::createFromMutable``.
By using this method we would not duplicate the code for converting a database date type to a php type just because we have two different type of date objects we would like to convert to.
On the database level there is no difference between mutable and immutable ones.

2016-07-22 09:12 UTC, deeky666 commented
@Deltachaos unfortunately this is not an option because of performance implications. The type system is highly performance sensitive.

2016-07-22 09:52 UTC, Deltachaos commented
@deeky666 ok i see. But there is the question what kind of solution we should use. Because fact is that the current date time conversion is to unflexible for some platforms.
I meet @beberlei and he said one of the team members is currently working on a draft for a new type system that is more flexible. He wanted to bring me in touch with him because i am interested to work on this topic.
But anyway this would be the solution for the long run. In my opinion we should have a solution for this problem also in the 2.x branch. But it would be a good idea to synchronize concepts with the 3.x solution.

May introducing a new ``TypeConverter`` class that can be defined by the ``AbstractPlatform`` similar to the ``getReservedKeywordsClass`` method would be a starting point.
This new class could inherit from a ``AbstractTypeConverter`` and override only the methods where special handling for this type is required for the specific platform.
The instance of ``TypeConverter`` could be revived in the specific types by calling something like ``getTypeConverter`` on the platform. In a new type system the platform and the type converter could be injected into the types at constructing time of the objects.
Now that the type has the ``TypeConverter`` it could simply bypass the convert calls to this ``TypeConverter`` (to seperate all the conversions we could use traits if we would like to eliminate one more call into a other class, or we could have specific type convers like ``DateTimeTypeConverter`` which are created by a factory in the platform using ``getTypeConverter(Type::DATETIME)``).

In this ``TypeConverter`` we could then also merge the conversions for mutable and immutable ones by having something like ``convertFromDateTime(bool $immutable = true)``. And if this is not perfomant enough having a ``if`` switch in the method for creating immutable or mutable ones, at least ``convertDateTimeToDatabaseValue(\DateTimeInterface)`` could be unified by rely on ``\DateTimeInterface`` instead of ``\DateTime``.

Using such an approach we would not have any BC break but a more flexible type system that can considerate all the platform specific stuff whitout bloating everything again.
We could then deprecate a few methods in the ``AbstractPlatform`` like ``convertFromBoolean``, ``convertBooleansToDatabaseValue``, ``convertBooleans``.
We could in a second step also try to move the declaration SQL's into a sperate class.

If you like the idea i could implement this.

2016-08-16 09:03 UTC, Deltachaos commented
@deeky666 any thoughts?

2017-02-13 13:00 UTC, Ocramius requested changes

2017-02-13 13:00 UTC, Ocramius commented on lib/Doctrine/DBAL/Types/DateTimeImmutableType.php
> +        throw ConversionException::conversionFailedInvalidType($value, $this->getName(), ['null', 'DateTimeImmutable']);
`DateTimeImmutable::class`

2017-02-13 13:00 UTC, Ocramius commented on lib/Doctrine/DBAL/Types/DateImmutableType.php
> +        $val = \DateTimeImmutable::createFromFormat('!'.$platform->getDateFormatString(), $value);
Don't abbreviate. Also, spacing around `.`

2017-02-13 13:00 UTC, Ocramius commented on lib/Doctrine/DBAL/Types/DateTimeImmutableType.php
> +        $val = \DateTimeImmutable::createFromFormat($platform->getDateTimeFormatString(), $value);
Same as above regarding abbreviations

2017-02-13 13:00 UTC, Ocramius commented on lib/Doctrine/DBAL/Types/DateTimeImmutableType.php
> +            $val = date_create_immutable($value);
This block looks really shady. While it may have been discussed before, could you clarify in a comment why it is needed?

2017-02-13 13:00 UTC, Ocramius commented on lib/Doctrine/DBAL/Types/DateTimeImmutableType.php
> +            $val = date_create_immutable($value);
Also, use the FQN version of it (`\` prefix)

2017-02-13 13:00 UTC, Ocramius commented on lib/Doctrine/DBAL/Types/DateTimeTzImmutableType.php
> +        throw ConversionException::conversionFailedInvalidType($value, $this->getName(), ['null', 'DateTimeImmutable']);
`::class`

2017-02-13 13:00 UTC, Ocramius commented on lib/Doctrine/DBAL/Types/DateTimeTzImmutableType.php
> +        $val = \DateTimeImmutable::createFromFormat($platform->getDateTimeTzFormatString(), $value);
Same as above regarding abbreviations

2017-02-13 13:00 UTC, Ocramius commented on lib/Doctrine/DBAL/Types/TimeImmutableType.php
> +        throw ConversionException::conversionFailedInvalidType($value, $this->getName(), ['null', 'DateTimeImmutable']);
`::class`

2017-02-13 13:00 UTC, Ocramius commented on lib/Doctrine/DBAL/Types/TimeImmutableType.php
> +        $val = \DateTimeImmutable::createFromFormat('!' . $platform->getTimeFormatString(), $value);
Spacing and abbreviations

2017-02-13 13:00 UTC, Ocramius commented on lib/Doctrine/DBAL/Types/Type.php
> +        self::DATETIME_IMMUTABLE => 'Doctrine\DBAL\Types\DateTimeImmutableType',
We can safely use `::class` here now (also for all other constants)

2017-02-13 13:00 UTC, Ocramius commented on lib/Doctrine/DBAL/Types/VarDateTimeImmutableType.php
> +        throw ConversionException::conversionFailedInvalidType($value, $this->getName(), ['null', 'DateTimeImmutable']);
`::class`

2017-02-13 13:00 UTC, Ocramius commented on lib/Doctrine/DBAL/Types/VarDateTimeImmutableType.php
> +        $val = date_create_immutable($value);
Same remarks as above:

 * why this instead of a constructor (comment needed)?
 * abbreviations?
 * FQN (`\` prefix)

2017-02-13 13:00 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Types/DateImmutableTypeTest.php
> +class DateImmutableTypeTest extends \PHPUnit_Framework_TestCase
Add `@covers` annotation

2017-02-13 13:00 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Types/DateTimeImmutableTypeTest.php
> +class DateTimeImmutableTypeTest extends \PHPUnit_Framework_TestCase
Add `@covers` annotation

2017-02-13 13:00 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Types/DateTimeTzImmutableTypeTest.php
> +class DateTimeTzImmutableTypeTest extends \PHPUnit_Framework_TestCase
Add `@covers` annotation

2017-02-13 13:00 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Types/TimeImmutableTypeTest.php
> +class TimeImmutableTypeTest extends \PHPUnit_Framework_TestCase
Add `@covers` annotation

2017-02-13 13:00 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Types/VarDateTimeImmutableTypeTest.php
> +class VarDateTimeImmutableTypeTest extends \PHPUnit_Framework_TestCase
Add `@covers` annotation

2017-02-13 13:00 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Types/DateImmutableTypeTest.php
> +     * @expectedException \Doctrine\DBAL\Types\ConversionException
Use `$this->expectException()` in the m method, also use `::class` there

2017-02-13 13:00 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Types/DateImmutableTypeTest.php
> +     * @expectedException \Doctrine\DBAL\Types\ConversionException
Use `$this->expectException()` in the m method, also use `::class` there

2017-02-13 13:00 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Types/DateTimeImmutableTypeTest.php
> +     * @expectedException \Doctrine\DBAL\Types\ConversionException
Use `$this->expectException()` in the m method, also use `::class` there

2017-02-13 13:00 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Types/DateTimeImmutableTypeTest.php
> +     * @expectedException \Doctrine\DBAL\Types\ConversionException
Use `$this->expectException()` in the m method, also use `::class` there

2017-02-13 13:00 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Types/DateTimeTzImmutableTypeTest.php
> +     * @expectedException \Doctrine\DBAL\Types\ConversionException
Use `$this->expectException()` in the m method, also use `::class` there

2017-02-13 13:00 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Types/DateTimeTzImmutableTypeTest.php
> +     * @expectedException \Doctrine\DBAL\Types\ConversionException
Use `$this->expectException()` in the m method, also use `::class` there

2017-02-13 13:00 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Types/TimeImmutableTypeTest.php
> +     * @expectedException \Doctrine\DBAL\Types\ConversionException
Use `$this->expectException()` in the m method, also use `::class` there

2017-02-13 13:00 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Types/TimeImmutableTypeTest.php
> +     * @expectedException \Doctrine\DBAL\Types\ConversionException
Use `$this->expectException()` in the m method, also use `::class` there

2017-02-13 13:00 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Types/VarDateTimeImmutableTypeTest.php
> +     * @expectedException \Doctrine\DBAL\Types\ConversionException
Use `$this->expectException()` in the m method, also use `::class` there

2017-02-13 13:00 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Types/VarDateTimeImmutableTypeTest.php
> +     * @expectedException \Doctrine\DBAL\Types\ConversionException
Use `$this->expectException()` in the m method, also use `::class` there

2017-03-02 11:24 UTC, enumag commented
ping @deeky666

2017-04-13 08:26 UTC, eigan commented
Looking at the other types in DBAL while trying to fix up @Ocramius comments, and I see several of his comments also applies for them.

----

[$val](https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Types/DateTimeType.php#L72) is used in almost all other classes.
`\Class` is used in other Date types
[Not using ::class](https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Types/DateTimeType.php#L60), is also applied there.
using [method instead of constructor](https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Types/DateTimeType.php#L75).

And with tests:
`@covers` is almost never used, I see it in two tests(?)
expectException is not used, but [setExpectedException](https://github.com/doctrine/dbal/blob/master/tests/Doctrine/Tests/DBAL/Types/TimeTest.php#L34). _(isnt this method deprecated anyway?)_ `::class` is not used in them.

----

While I agree with your comments @Ocramius, I think its better to have it same as the other types for now, and then make another pull request that addresses your points on all the other types aswell.

Anyway, I opened a [pull request](https://github.com/deeky666/dbal/pull/5) on deeky666 that addresses some of the comments.

Looking forward to having immutable dates. Thanks for your work @deeky666

2017-05-09 14:28 UTC, kimhemsoe commented
Know it is out of the scope in this PR. But would it make sense to support DatetimeInterface when converting to sql value?

I see why it would i a bit.. !wrong! possible. So properly not a good idea, but i just wanted to throw the idea out here.

2017-05-10 14:18 UTC, deeky666 commented on lib/Doctrine/DBAL/Types/DateTimeImmutableType.php
> +            $val = date_create_immutable($value);
@Ocramius the logic is more or less a 1:1 copy from the original DateTime types. As far as I recall it is kind of a fallback option if the first attempt to create the DateTime object fails. For more information see: https://github.com/doctrine/dbal/issues/1609
Anything I should change here?

Concerning the FQN I don't quite get why I should use it here for the function call. If that was the case, wouldn't we have to FQN ALL internal function calls aswell? This seems rather wird to me.

2017-05-10 14:29 UTC, deeky666 commented on lib/Doctrine/DBAL/Types/VarDateTimeImmutableType.php
> +        $val = date_create_immutable($value);
See above. Also the class DocBlock should be enough. No need to duplicate comments IMO.

2017-05-10 14:30 UTC, deeky666 commented on tests/Doctrine/Tests/DBAL/Types/DateImmutableTypeTest.php
> +class DateImmutableTypeTest extends \PHPUnit_Framework_TestCase
Since when are we doing that? Never used it before. Please give an example here if I should.

2017-05-10 14:41 UTC, deeky666 commented
@Ocramius fixed CS concerns and the other stuff.

2017-05-10 14:59 UTC, Ocramius commented
All green :ship:

2017-05-10 14:59 UTC, merged

2017-06-28 13:52 UTC, Majkl578 commented on lib/Doctrine/DBAL/Types/DateTimeImmutableType.php
> +            $dateTime = \date_create_immutable($value);
Any particular reason why functional interface is preferred rather than `new DateTimeImmutable`?

2017-06-28 15:21 UTC, jvasseur commented on lib/Doctrine/DBAL/Types/DateTimeImmutableType.php
> +            $dateTime = \date_create_immutable($value);
Because it returns false on failure instead of throwing an exception.