[MySQL] Use native JSON type on MySQL >=5.7
doctrine/dbal pull request #2455
Opened 2016-07-24 14:46 UTC by rh389

This follows https://github.com/doctrine/dbal/pull/2266 , with changes merged into the MySQL57 platform as suggested by @beberlei.

2016-08-15 06:20 UTC, arroyo commented
Is there any movement on the json type support for mysql.  I see these two open pull requests.  Looking forward to using this when it's ready.  Thanks.

2016-08-19 21:11 UTC, sameg14 commented
Guys can we please get this merged in! It's causing a lot issues on our end, we need to use the JSON type!

2016-08-23 15:58 UTC, rh389 commented
It's been over a month since there were any commits at all to master, but fairly active before that - I guess the key maintainers are away/occupied.

2016-08-23 16:06 UTC, sameg14 commented
If you need to setup a custom JSON type for Doctrine in Symfony here is how you can achieve it

Ensure that `app/config/config.yml` has this line for doctrine
```yml
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        server_version: 5.7
        mapping_types:
            json: string
        types:
            custom_json:
                class: CoreBundle\DBAL\Type\JsonType
                commented: true
```

Then ensure that you create the custom type as such
```php
<?php

namespace CoreBundle\DBAL\Type;

use Doctrine\DBAL\Types\JsonArrayType;
use Doctrine\DBAL\Platforms\AbstractPlatform;

/**
 * Class JsonType
 * @package CoreBundle\DBAL
 */
class JsonType extends JsonArrayType
{
    /**
     * @param array $fieldDeclaration
     * @param AbstractPlatform $platform
     * @return string
     */
    public function getSQLDeclaration(array $fieldDeclaration, AbstractPlatform $platform)
    {
        return 'json';
    }

    /**
     * Convert the value of the field into a PHP data type
     * @param mixed $value
     * @param AbstractPlatform $platform
     * @return array|mixed|null
     */
    public function convertToPHPValue($value, AbstractPlatform $platform)
    {
        return $value === null ? null : parent::convertToPHPValue($value, $platform);
    }

    /**
     * Name of the db type
     * @return string
     */
    public function getName()
    {
        return 'json';
    }
}
```

Then your entity property should use the `custom_json` type to store data in mysql using json
```php
<?php

namespace CoreBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @package CoreBundle\ExampleJsonEntity
 * @ORM\Table(name="example_json_table")
 * @ORM\Entity(repositoryClass="CoreBundle\Repository\ExampleJsonRepository")
 */
class ExampleJsonEntity
{
    /**
     * @var int
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     * @ORM\Column(name="json_data", type="custom_json", nullable=true)
     */
    private $jsonData;

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return string
     */
    public function getJsonData()
    {
        return $this->jsonData;
    }

    /**
     * @param string $jsonData
     */
    public function setJsonData($jsonData)
    {
        $this->jsonData = $jsonData;
    }
}
```

2016-09-26 00:43 UTC, phansys commented on tests/Doctrine/Tests/DBAL/Platforms/MySQL57PlatformTest.php
> +        $this->assertEquals('json_array', $this->_platform->getDoctrineTypeMapping('json'));
Why not `assertSame()`?

2016-09-26 00:43 UTC, phansys requested changes

2016-09-26 11:11 UTC, rh389 commented on tests/Doctrine/Tests/DBAL/Platforms/MySQL57PlatformTest.php
> +        $this->assertEquals('json_array', $this->_platform->getDoctrineTypeMapping('json'));
Thanks - updated.

2016-10-12 15:19 UTC, teohhanhui commented on tests/Doctrine/Tests/DBAL/Platforms/MySQL57PlatformTest.php
> +    /**
Missing blank line.

2016-10-12 16:08 UTC, rh389 commented on tests/Doctrine/Tests/DBAL/Platforms/MySQL57PlatformTest.php
> +    /**
Good spot - fixed

2017-02-09 22:42 UTC, deeky666 commented
Closing in favour of #2653. See description.

2017-02-09 22:42 UTC, closed without merging

2017-05-09 10:49 UTC, Ocramius commented
Handled in #2653