IBM_DB2 platform doesn't handle offset without limit
doctrine/dbal pull request #2463
Opened 2016-08-03 15:04 UTC by morozov

There's a non-empty table `users`. The following script should return all existing record IDs.
```php
$builder = $conn->createQueryBuilder();
$builder->select('id')
    ->from('users')
    ->setFirstResult(0);
$data = $builder->execute()->fetchAll();
var_dump($data);
```
It does so on Oracle and MySQL, but returns empty result on DB2. The reason is that resulting SQL has a condition like `WHERE db22.DC_ROWNUM BETWEEN 1 AND 0`.

2016-09-13 00:25 UTC, morozov commented
Resolved merge conflict with #2372.

2017-01-16 22:05 UTC, deeky666 requested changes
Patch is good, just some minor CS adjustments required.

2017-01-16 22:05 UTC, deeky666 commented on lib/Doctrine/DBAL/Platforms/DB2Platform.php
> +        if (count($where) === 0) {
Can you use `empty()` here?

2017-01-16 22:05 UTC, deeky666 commented on lib/Doctrine/DBAL/Platforms/DB2Platform.php
> +        $sql = sprintf(
Can you return early here like `return sprintf()`?

2017-01-16 22:16 UTC, morozov commented on lib/Doctrine/DBAL/Platforms/DB2Platform.php
> +        if (count($where) === 0) {
Sure. Just trying to understand the requirements, is `empty($array)` somehow better than `count($array)`? IMO, `empty()` is prone to typos like `empty($were)` which one may not notice w/o running tests.

2017-01-16 23:24 UTC, deeky666 commented on lib/Doctrine/DBAL/Platforms/DB2Platform.php
> +        if (count($where) === 0) {
@morozov this is just about minor optimizations. `empty()` is a language construct and much more efficient than using the function `count()`. The point about typos is a good point, but in DBAL we try to code as much performance efficient as possible even if it seems neglible. Thanks for changing.

2017-01-16 23:24 UTC, deeky666 approved these changes

2017-01-16 23:25 UTC, merged

2017-01-16 23:25 UTC, deeky666 commented
@morozov thanks for your effort!

2017-01-16 23:27 UTC, deeky666 commented
Backported to `2.5` via https://github.com/doctrine/dbal/commit/0f7bf0ce3f061fa94912318f2d762ccaf78491ac

2017-01-16 23:28 UTC, morozov commented on lib/Doctrine/DBAL/Platforms/DB2Platform.php
> +        if (count($where) === 0) {
@deeky666 gotcha, thanks, will keep that in mind in the future.