Fix problem with non-existing implicit indexes
doctrine/dbal pull request #2470
Opened 2016-08-13 14:52 UTC by aimeos

On tables which contains a foreign key constraint with no explicit index, _addForeignKeyConstraint() in \Doctrine\DBAL\Schema\Table creates an implicit index. If that schema is used to create a SchemaDiff object, the diff creates a SQL statement to drop that implicit index that doesn't exist in the database, so DROP INDEX fails.

https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Schema/Table.php#L546

2016-09-13 08:02 UTC, aimeos commented
Any objections to this PR? It would be great to get it into the next release because the bug causes a lot failed migrations in our case.

2017-06-12 07:53 UTC, tmbdrogba commented
👍

2017-06-12 08:10 UTC, Ocramius requested changes

2017-06-12 08:10 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Schema/TableTest.php
> +        $table->addIndex(array('bloo', 'bar', 'baz'), 'full_idx');
Please *add* tests: removing or changing tests will lead to BC breaks.

2017-06-12 08:10 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Platforms/SqlitePlatformTest.php
> -            'CREATE INDEX IDX_8D93D64923A0E66 ON client (article)',
Is this test supposed to be removed?

2017-06-12 08:10 UTC, Ocramius commented on lib/Doctrine/DBAL/Schema/Index.php
> +        if (count($other->getColumns()) < count($this->getColumns())) {
Not all databases are necessarily able to use larger indexes as a replacement for indexes with a subset of their covered columns. In addition to that, see the comment right above (about PK + UNIQUE)

2017-06-12 08:11 UTC, Ocramius commented
@aimeos also, really sorry for not seeing this PR earlier: it completely went off my radar :(

2017-07-26 07:56 UTC, tmbdrogba commented on tests/Doctrine/Tests/DBAL/Platforms/SqlitePlatformTest.php
> -            'CREATE INDEX IDX_8D93D64923A0E66 ON client (article)',
I supposed this is a non existing implicit index, right @aimeos ?

2017-07-26 13:35 UTC, aimeos commented on tests/Doctrine/Tests/DBAL/Platforms/SqlitePlatformTest.php
> -            'CREATE INDEX IDX_8D93D64923A0E66 ON client (article)',
@tmbdrogba Yes, it is. It's created to be added to the database at the end

2017-09-28 15:56 UTC, maximecrtmc commented
any update about this issue ?

2018-07-16 11:45 UTC, loconox commented
Hi,
I'm facing the issue.

2021-01-22 07:44 UTC, closed without merging