URL-decode URL-style DSN
doctrine/dbal pull request #2504
Opened 2016-09-12 17:19 UTC by c960657

The URL-style DSN does not support escaping, so if the username/password/database name contains certain characters, the connection options simply cannot be represented this way.

This patch URL-decodes the different parts. It introduces a small BC break for usernames/passwords/database names containing the character `%`.

2017-01-14 20:52 UTC, deeky666 commented
@Ocramius this looks like a reasonable improvement. The BC question arises of course, especially significant for passwords IMO. What do you think? Shall we accept the slight BC and target this patch for `2.6` only? Also I think this needs documentation.

2017-01-14 22:49 UTC, Ocramius commented
This is sane, and can be landed in `2.6`, but it needs documenting in [`UPGRADE.md`](https://github.com/doctrine/dbal/blob/7963f131bef97caa54f7e765334abc5d79562473/UPGRADE.md) before it can be merged. 

@c960657 can you add notes for how an upgrade would be performed, and what the BC break for `%` characters would be? I'd like to also have the `%` character as part of the test suite data-providers (additional entry to what you added), so that the expected output can be viewed by users hitting the problem, and further regressions prevented.

2017-01-14 22:50 UTC, Ocramius requested changes
Requesting changes as per https://github.com/doctrine/dbal/pull/2504#issuecomment-272659210

2017-01-14 23:20 UTC, deeky666 commented
@c960657 also an entry about URL econding/deconding should make its way into the DBAL documentation.

2017-01-15 12:00 UTC, c960657 commented
I have added a test and some upgrade information.

2017-01-15 17:34 UTC, Ocramius commented
@c960657 awesome, thanks!

2017-01-15 17:34 UTC, Ocramius approved these changes

2017-01-15 17:34 UTC, merged