Normalize method signatures for `fetch()` and `fetchAll()`
doctrine/dbal pull request #2527
Opened 2016-10-01 13:42 UTC by phansys

|Q            |A    |
|---          |---  |
|Branch       |2.5  |
|Bug fix?     |yes  |
|New feature? |no   |
|BC breaks?   |yes  |
|Deprecations?|no   |
|Tests pass?  |yes  |
|Fixed tickets|#2519|
|License      |MIT  |
|Doc PR       |n/a  |
                     

Close #2519.

2016-10-01 13:43 UTC, Ocramius commented
Please PR against master. Backporting is up to us.

On 1 Oct 2016 15:42, "Javier Spagnoletti" <notifications@github.com> wrote:

> Q A
> Branch 2.5
> Bug fix? yes
> New feature? no
> BC breaks? yes
> Deprecations? no
> Tests pass? yes
> Fixed tickets #2519 <https://github.com/doctrine/dbal/issues/2519>
> License MIT
> Doc PR n/a
>
> Close #2519 <https://github.com/doctrine/dbal/issues/2519>.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/doctrine/dbal/pull/2527
> Commit Summary
>
>    - Changed the composer constraint to allow Common 2.5
>    - add test for explicit positional parameter keys
>    - Fixed expanding positional parameters which do not start from 0
>    - Fixing default timezone for tests, as travis keeps failing due to
>    travis-ci/travis-ci#2523
>    - fix column comments containing string literal chars on SQL Server
>    - fix renaming column with default value on SQL Server
>    - Add missing quotes at the end of literal strings
>    - normalize asset names consistently
>    - fix explicit case sensitive identifiers in Oracle
>    - revert identity sequence naming strategy on Oracle to keep BC
>    - use identity sequence name for generating SQL to drop an
>    autoincrement from a column
>    - fix NULL / NOT NULL clause for column alterations in Oracle
>    - fix column comment lifecycle
>    - fix table diff's new name if it is not set
>    - `false` is not a valid type: replacing with `boolean`
>    - Moving HHVM+mysql back to allowed failures: we need green builds to
>    keep moving (for now)
>    - fallback to default MySQL port if not given in mysqli connection
>    - close statement cursor after test completion
>    - add HHVM + mysqli driver to Travis build matrix
>    - Using vendor PHPUnit version for travis builds
>    - Reset date fields to UNIX epoch in TimeType.
>    - Adds support for setting the charset in SQLSrv
>    - fix explicitly quoted table identifiers in ALTER TABLE statements
>    - Fixed closing a connection
>    - Add test case for #688
>    - Fix test purpose
>    - Use method `setExpectedException` instead annotation
>    - #685 - as per @deeky666's review, exception should be expected only
>    on the quoting call
>    - doModifyLimitQuery() was missing an outer "ORDER BY doctrine_rownum"
>    - fixed test cases
>    - Enabled placeholders for "in" method in ExpressionBuilder
>    - wrap PDOException for exec() method and cleanup unnecessary try
>    catch blocks
>    - fix quoted sequence name
>    - add test to verify null cast in boolean type
>    - resolves #632 Fix null cast in boolean type in Postgres platform
>    - refs #632 Remove is_null to be consistent with doctrine coding
>    standard
>    - Update PostgreSqlPlatform.php
>    - Test to check null conversion with boolean type
>    - refs #632 check boolean conversion with and without PDO type value
>    - Fix boolean conversion with php 5.6
>    - Revert change to fix php 5.6
>    - Change assertEquals to assertSame
>    - Fix return type of Connection::project
>    - Update PostgreSqlPlatform.php
>    - fix table column alteration
>    - Update PostgreSqlPlatform.php
>    - Update PostgreSqlPlatform.php
>    - Update PostgreSqlPlatform.php
>    - Update PostgreSqlPlatform.php
>    - only introspect namespaces and views accessible
>    - allow connecting without database name for sqlanywhere driver
>    - add test for connecting without database name on capable platforms
>    - fix line separators
>    - fix foreign key referential action SQL on SQL Server and SQL Anywhere
>    - throw exception if exec() fails in mysqli driver connection
>    - add more foreign key constraint violation error codes
>    - fix fetching NULL values via fetchColumn()
>    - fix CS
>    - fix tear down foreign key constraint violation exception tests
>    - fix foreign key referential action SQL on SQL Server and SQL Anywhere
>    - fix generating COMMENT ON COLUMN statements for quoted identifiers
>    - Merge branch 'master' into 2.5
>    - sign release tags in ant build script
>    - Prepare 2.5.0 release
>    - Release 2.5.0
>    - Bump version to 2.5.1
>    - Update UPGRADE.md
>    - Update index name quoting in MySQL table creation
>    - Move index name quote to abstract
>    - Only quote in get*SQL() methods
>    - Use name rather than index object
>    - fix quoting reserved keywords as unique constraint name in SQL
>    Anywhere
>    - throw exception for unsupported inline index declaration in DB2
>    - apply reserved keyword as index name test case for all platforms
>    - Removed non-phpdoc @internal tags
>    - minor phpdoc fixes in the platform files
>    - minor phpdoc fixes in the remaining files after pr #746
>    - Take care about MariaDB versioning
>    - Check for changed fixed option added in PostgreSqlPlatform
>    - unittest for fixed string alteration added
>    - unittest group added to testcase for the fix
>    - unittest adapted for all plattforms using AbstractPlatformTestCase
>    - fix renaming indexes used by foreign key constraints
>    - Merge branch 'hotfix/#756-DBAL-1062-DBAL-1092-backport-to-2.5.x'
>    into 2.5
>    - fix creating and dropping database on PostgreSQL
>    - Merge branch 'hotfix/backport-#757-DBAL-1093-to-2.5' into 2.5
>    - fix index introspection on SQL Anywhere
>    - Merge branch 'hotfix/#759-DDC-1095-sql-anywhere-index-introspection-fk-fixes'
>    into 2.5
>    - Fix error handling in mysqli driver
>    - char length fixed in PostgreSqlSchemaManager
>    - add fixed string column introspection functional test case
>    - fix foreign key constraint referential action NO ACTION and RESTRICT
>    on Oracle
>    - Merge branch 'hotfix/#760-DBAL-1097-backport-to-2.5' into 2.5
>    - Force connection close to allow further DROP DATABASE statements to
>    work under PostgreSQL.
>    - allow defining duplicate indexes based on columns and properties on
>    a table
>    - Merge branch 'hotfix/#764-DDC-1102-backport-to-2.5' into 2.5
>    - Made the handling of NULL more consistent in the json_array type.
>    - Added a unit test for the type JsonArray, to test empty string
>    conversion.
>    - Do not TRIM() parentheses around partial index's conditions
>    - add group tag to test case
>    - add more assertions for partial index test case
>    - fix partial index test case
>    - allow overriding implicit indexes
>    - Merge branch 'hotfix/#769-allow-implicit-indexes-overrides' into 2.5
>    - Fix unique index exception handling for an index on multiple columns
>    in PHP 5.4
>    - Merge branch 'hotfix/#771-backport-php-5-4-
>    unique-index-exception-error-handling' into 2.5
>    - Quote the name of an index in the create table statement.
>    - #723 - Added tests
>    - fix database and namespace introspection for SQL Server
>    - Merge branch 'hotfix/#736-DBAL-1058-fix-database-and-namespace-
>    introspection-for-sql-server-backport-to-2.5' into 2.5
>    - make host and server connection parameters optional for sqlanywhere
>    driver
>    - Merge branch 'hotfix/#777-allow-optional-host-and-server-connection-parameters-2.5'
>    into 2.5
>    - SQLite supports null limit via `LIMIT -1`
>    - Hotfix: SQLite supports null limit via `LIMIT -1`
>    - Merge branch 'hotfix/sqlite-offset-with-no-limit-support-2.5-backport'
>    into 2.5
>    - fix quoted identifiers for database creation SQL on SQL Anywhere
>    - Merge branch 'hotfix/#773-fix-quoted-identifiers-in-database-creation-for-sqlanywhere'
>    into 2.5
>    - Update QueryBuilder.php
>    - Update QueryException.php
>    - Update QueryBuilder.php
>    - Update QueryBuilder.php
>    - Update QueryBuilderTest.php
>    - Update QueryBuilderTest.php
>    - Update QueryBuilderTest.php
>    - Update QueryBuilderTest.php
>    - rename exception method
>    - fix passing known aliases to QueryException
>    - fix test case
>    - simplify test case
>    - use more decl [...]

2017-02-06 08:08 UTC, mikeSimonson commented
@phansys What about the usage of func_get_args ?

2017-02-09 23:06 UTC, deeky666 commented
@phansys yes please do as @mikeSimonson suggested. We already follow this approach [here](https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Driver/PDOConnection.php#L86-L108)

2017-02-14 14:54 UTC, phansys commented
@mikeSimonson, @deeky666; the reason for the comment in my **TODO** is that I'm trying to normalize the method signatures, making them as explicitly as possible. Using `func_get_args()` to unpack method arguments is precisely doing the opposite.

2017-02-16 21:17 UTC, mikeSimonson commented
@phansys If it's possible to make the signature more explicit in those cases go for it.
As long as it doesn't break backward compatibility.
If it does put it in another PR.

2017-02-19 00:32 UTC, phansys commented
The BC is respected internally, since `ResultStatement::fetch()` and `ResultStatement::fetchAll()` have default values for the new arguments. But this could lead to issues if somebody was using `ResultStatement` interface for their own classes.

2017-06-06 11:54 UTC, phansys commented
Which is the status of this PR? Ping @Ocramius, @deeky666, @mikeSimonson.

2017-06-06 12:08 UTC, Ocramius approved these changes

2017-06-06 12:12 UTC, Ocramius requested changes
@phansys excellent work, but we need to document the migration approach for existing implementations in `UPGRADE.md`

2017-06-06 12:12 UTC, Ocramius commented on lib/Doctrine/DBAL/Driver/ResultStatement.php
> +    public function fetch($fetchMode = null, $cursorOrientation = \PDO::FETCH_ORI_NEXT, $cursorOffset = 0);
This signature change is a BC break and needs upgrade/migration path in `UPGRADE.md`

2017-06-06 12:12 UTC, Ocramius commented on lib/Doctrine/DBAL/Driver/ResultStatement.php
> +    public function fetchAll($fetchMode = null, $fetchArgument = null, $ctorArgs = null);
This signature change is a BC break and needs upgrade/migration path in `UPGRADE.md`

2017-06-06 15:47 UTC, phansys commented on lib/Doctrine/DBAL/Driver/ResultStatement.php
> +    public function fetch($fetchMode = null, $cursorOrientation = \PDO::FETCH_ORI_NEXT, $cursorOffset = 0);
Thank you @Ocramius, I've added a note in the upgrade path for 2.6 regarding these changes.

2017-06-06 15:59 UTC, Ocramius commented
Thanks @phansys!

2017-06-06 15:59 UTC, Ocramius approved these changes

2017-06-06 16:00 UTC, merged

2018-01-03 07:16 UTC, morozov commented on UPGRADE.md
> +    Doctrine\DBAL\Driver\ResultStatement::fetch($fetchMode, $fetchArgument, $ctorArgs);
It probably should've been `Doctrine\DBAL\Driver\ResultStatement::fetchAll($fetchMode, $fetchArgument, $ctorArgs);`.

2018-01-03 07:19 UTC, morozov commented
After #2953 gets resolved, we may want to revert the API changes made here. Or maybe we could revert `fetchAll()` as part of #2953 (it already reverts the `fetch()` part)?

/cc @Ocramius

2018-01-03 08:51 UTC, Ocramius commented
As part of #2953 would be best, since it already deals with moving away from PDO

2018-01-03 23:41 UTC, morozov commented
Apparently, some drivers like [IBM DB2](https://github.com/doctrine/dbal/blob/e3ab127672fd72e5e64a17f20b11ab2d12b8bfc5/lib/Doctrine/DBAL/Driver/IBMDB2/DB2Statement.php#L228), [SQLServer](https://github.com/doctrine/dbal/blob/e3ab127672fd72e5e64a17f20b11ab2d12b8bfc5/lib/Doctrine/DBAL/Driver/SQLSrv/SQLSrvStatement.php#L315)  and others implement handling additional arguments in `fetch()` and `fetchAll()` using `func_get_args()`, so removing all arguments except `$fetchMode` from the `fetch*()` methods is incorrect. I thought those arguments were introduced solely for compatibility with `PDOStatement`. Thanks to `DataAccessTest::testFetchAllSupportFetchClass()`.

Instead, we can change their signatures to `fetch*($fetchMode = null, ...$args)` to make the optional arguments explicit and at the same time independent on the `PDO` constants.