sql_variant and sysname as string
doctrine/dbal pull request #2530
Opened 2016-10-10 00:31 UTC by hounded

2016-10-12 15:44 UTC, phansys requested changes
Status: Needs Work.

2016-10-12 15:44 UTC, phansys commented on lib/Doctrine/DBAL/Platforms/SQLServerPlatform.php
> +            'sql_variant'=>'string',
Please, respect CS (missing spaces around `=>` operator).

2016-10-24 06:13 UTC, hounded commented
Respected CS (missing spaces around => operator).

2016-10-25 03:04 UTC, Ocramius commented
Seems straightforward, but a unit test is needed to prevent future regressions.

2017-10-31 13:16 UTC, federicoemartinez commented
Is there a workaround if this PR is not merged? I have already faced an issue with "sysname"

2021-07-09 01:19 UTC, morozov commented
Closing as SQLAnywhere is no longer supported.

2021-07-09 01:19 UTC, closed without merging