Implement the column collation for Mysql
doctrine/dbal pull request #2551
Opened 2016-11-06 21:09 UTC by mikeSimonson

Related to #2538

2016-11-06 21:24 UTC, Ocramius commented
@mikeSimonson should this fix (since it fixes #2538, if I understand it correctly) come with a test case then?

2017-02-20 14:00 UTC, tristanbes commented
Any updates on this @mikeSimonson ? I can confirm that this fix should fix my issue about Doctrine Migrations generating a diff without the collate information set on `Table` option

` * @ORM\Table(name="fos_user", options={"collate"="utf8mb4_unicode_ci", "charset"="utf8mb4"}) `

When I put a new field and I generate the diff it outputs
`$this->addSql('ALTER TABLE fos_user ADD lessNoise TINYINT(1) NOT NULL');`

resulting in the field created in `utf8_unicode` and `utf8_unicode_ci` for collation instead of the settings set on the table.

2017-02-20 17:22 UTC, mikeSimonson commented
@Ocramius Do you mean that the test should be removed or that it needs a higher level test case ?

2017-02-21 11:24 UTC, Ocramius commented
@mikeSimonson higher level test case reflecting #2538

2017-02-25 08:55 UTC, mikeSimonson commented
@Ocramius What is the right approach here for the test ?

2017-02-25 14:22 UTC, Ocramius requested changes
One last change probably needed: verifying that the comparator will pick up the collation (unless that is already covered)

2017-02-25 14:22 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Schema/SchemaTest.php
> +    public function testFixGithub2538_autoincrement()
This test seems unrelated to the changes, or am I missing something?

2017-02-25 14:22 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Schema/SchemaTest.php
> +        $tableName = "public.foo";
Single quotes

2017-02-25 14:22 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Schema/SchemaTest.php
> +    public function testFixGithub2538_autoincrement()
Please use a method name describing the issue being covered. Also, use `@group #2538` for labeling it

2017-02-25 14:22 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Schema/SchemaTest.php
> +    public function testFixGithub2538Collation()
Please use a method name describing the issue being covered. Also, use `@group #2538` for labeling it

2017-02-25 14:22 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Platforms/AbstractPlatformTestCase.php
> +    public function testFixGithub2538Collation()
Please use a method name describing the issue being covered. Also, use `@group #2538` for labeling it

2017-07-23 23:15 UTC, yukoff commented
What is the progress with this one? And maybe there should be column charset implemented ass well?

2017-08-03 17:03 UTC, Tobion commented
I don't see the point of this PR. Column collations are working in mysql already in general.

`@ORM\Column(type="string", options={"collation"="ascii_general_ci"})` will correctly generate a mysql column like `myfield VARCHAR(255) NOT NULL COLLATE ascii_general_ci`

The requested change seems useless. MysqlPlatform already implements 

```
public function supportsColumnCollation()
{
        return true;
}
```
and the rest is handled by the default implementation of AbstractPlatform.

There are two bugs with column collations:
1. schema update / migrations doesn't recognize collation changes, see #2401 similar issues
2. When you have a column collation overwritten for an enity primary key that is used as forgeign key in another entity, then the collation is MISSING in the foreign key definition. This makes the generated schema invalid because the collations can be different which is not allowed in foreign key constraints. This is what is stumbled upon. I'll create an issue for this.

2017-08-03 19:31 UTC, Ocramius commented
> Column collations are working in mysql already in general.

Tests seem to say otherwise, but feel free to provide more tests or comment on the ones provided in this PR.

2018-03-30 22:07 UTC, closed without merging