DateIntervalType (negative support) resolves doctrine/dbal#2578
doctrine/dbal pull request #2579
Opened 2016-12-14 15:37 UTC by galeaspablo

2016-12-15 09:30 UTC, galeaspablo commented
If #2316 is merged before this, we'll need to refactor this PR.

2016-12-15 10:54 UTC, lcobucci requested changes

2016-12-15 10:54 UTC, lcobucci commented on lib/Doctrine/DBAL/Types/DateIntervalType.php
> +            $interval = new \DateInterval(substr($value, 1));
With this you assume that `$value` always have the sign, which is not the case for existing data.
We should make sure that the type would still work for the "old" format.

2016-12-15 10:56 UTC, lcobucci commented on lib/Doctrine/DBAL/Types/DateIntervalType.php
> +            $interval = new \DateInterval(substr($value, 1));
> We should make sure that the type would still work for the "old" format.

Testing it too :wink:

2016-12-15 11:19 UTC, galeaspablo commented on lib/Doctrine/DBAL/Types/DateIntervalType.php
> +            $interval = new \DateInterval(substr($value, 1));
I don't think `\DateInterval` accepts a leading `+` or `-`.
How about?
```php
try {
            $firstCharacter = substr($value, 0, 1);
            if ($firstCharacter !== '+' && $firstCharacter !== '-') {
                  return new \DateInterval($value);
            }
            $interval = new \DateInterval(substr($value, 1));
            if ($firstCharacter === '-') {
                 $interval->invert = 1;
             }
             return $interval;
}
```

2017-01-17 22:47 UTC, deeky666 commented on lib/Doctrine/DBAL/Types/DateIntervalType.php
> +            $interval = new \DateInterval(substr($value, 1));
My 2 cents on this. As already pointed out, this is a BC break that cause schema changes and format changes, which we cannot accept for a minor release. We could however introduce a new type like `SignedDateIntervalType` to keep BC.

2017-01-18 09:31 UTC, galeaspablo commented on lib/Doctrine/DBAL/Types/DateIntervalType.php
> +            $interval = new \DateInterval(substr($value, 1));
Is this really a BC break? This isn't on 2.5.

2017-01-18 09:33 UTC, deeky666 commented on lib/Doctrine/DBAL/Types/DateIntervalType.php
> +            $interval = new \DateInterval(substr($value, 1));
@galeaspablo oh you are right I thought it was part of 2.5 already. Thanks for pointing that out, then we won't have a problem with BC indeeed :)

2017-02-28 10:06 UTC, foaly-nr1 commented
Any update on this? Would you go ahead with the merge with the solution from https://github.com/doctrine/dbal/pull/2579#discussion_r92590246, @lcobucci?

2017-06-29 17:28 UTC, Ocramius commented
After looking at it with @sebastianfeldmann at the DPC code night, I'd say that this is NOT ready to be deployed. Instead, a new type is needed, because this kind of change would mean that users of the library would have half the data WITH the sign, and half the data without.

In addition to that, binding with the sign would change behavior: queries using parameter binding would be broken.

That's the way to go IMO, whereas the existing type would have to stay unchanged.

2017-06-29 17:29 UTC, Ocramius commented
Closing and pushing discussion back to #2578

2017-06-29 18:04 UTC, Ocramius commented
Re-opening as per https://github.com/doctrine/dbal/issues/2579#issuecomment-312047665 - sorry @galeaspablo!

2017-07-02 11:08 UTC, galeaspablo commented
#2316 was merged. Through it, the database value format was changed. As I said before, this means that I had to refactor my PR.

I've refactored my PR to work with the new master branch (i.e. handle negative support with the new format).

2017-07-23 02:25 UTC, lcobucci submitted a review, later dismissed
Just synced with `master`. LGTM

2017-07-23 04:12 UTC, Ocramius commented
@lcobucci as mentioned before, the fact that I released early is my fuckup (technical terminology).

We discussed it earlier tonight, and while it is technically possible for us to introduce a quick `2.6.1` with the change in it, nothing denies folks to install `2.6.0` now, then upgrade and have it broken later.

This PR is now a BC break, and I don't think we can fix it without introducing a `SignedDateIntervalType`.

@galeaspablo I apologise, this will need some rework :-(

2017-07-23 10:20 UTC, Ocramius commented
I think so. @deeky666 @lcobucci thoughts?

2017-07-24 08:29 UTC, lcobucci commented
#2578 is labeled as a `bug` and the PR is an improvement. If we tackle it as an improvement I with a new type (maybe even deprecating the existing one), however if we see it as a bug I'd rather change the PR in a way that doesn't break BC.

We also need to keep in mind that new features will land just on `2.7`.

2018-03-29 02:55 UTC, Majkl578 commented
Hi, shall we consider this a blocker for 2.7? If so, it needs a rebase & fixing the conflicts, otherwise we could push this back to 2.8/3.0 and decide later.

2018-03-29 19:50 UTC, Ocramius approved these changes

2018-03-29 20:20 UTC, morozov approved these changes

2018-03-29 20:20 UTC, merged