Fetch table options to improve dumping of table structure
doctrine/dbal pull request #2581
Opened 2016-12-20 13:31 UTC by digilist

Currently, information like the collation, charset and the engine (in MySQL) get lost when I use Doctrine to analyze the data and to create "CREATE TABLE" statements.  When I have a table, that has for example a utf8_general_ci collation, MySQL does not fetch this information. However, the collation of a column is fetched correctly.

Consider the following table:

<pre>
CREATE TABLE foo
(name VARCHAR(255) NOT NULL COLLATE utf8_general_ci)
DEFAULT CHARACTER SET utf8 COLLATE <b>utf8_general_ci</b> ENGINE = InnoDB;
</pre>

By dumping the table structure, we get the following result:

<pre>
CREATE TABLE foo
(name VARCHAR(255) NOT NULL COLLATE utf8_general_ci)
DEFAULT CHARACTER SET utf8 COLLATE <b>utf8_unicode_ci</b> ENGINE = InnoDB;
</pre>

As you can see, the collation information got lost. And it is the same with the character set and the engine and probably other options I don't know about.

I'd like to propose a feature that analyses the tables and adds those options into the Table object.

Before I start to implement this feature for all platforms and build tests, I'd like to ask for your feedback. Are there any objections not to implement this feature?

2017-01-14 17:49 UTC, deeky666 commented
@digilist generally speaking I am not against this feature. You have have to be aware of the fact that this feature only covers dumping table options, it will not be used by the comparator for comparing schemas (and I would not suggest adding that in the future as this is too vendor specific). Despite that, this change introduced a BC break for custom platform/schema implementation because of the exception being thrown in the abstract platform. We would have to turn this into a non breaking change I suppose.

2017-02-07 10:56 UTC, digilist commented
I can remove the exception, I just reflected that behavior from another method. Returning an empty array is fine.

If we just return an empty array, do we need to implement this for all database platforms or is it sufficient to implement it only for some at first?

2017-02-14 15:15 UTC, phansys requested changes
Status: Needs work.

2017-02-14 15:15 UTC, phansys commented on lib/Doctrine/DBAL/Platforms/AbstractPlatform.php
> +    public function getTableOptionsSQL($table, $database = null)
Docblock for argument 2 is missing.

2017-02-14 15:15 UTC, phansys commented on lib/Doctrine/DBAL/Platforms/MySqlPlatform.php
> +        $databaseNameSql = null === $database ? 'DATABASE()' : $database;
`$databaseNameSql = $database ?: 'DATABASE()';`

2021-07-09 01:46 UTC, morozov commented
Closing as stale and missing tests.

2021-07-09 01:46 UTC, closed without merging