Inherit charset from master connection if not set explicitly
doctrine/dbal pull request #2588
Opened 2016-12-27 13:54 UTC by Deltachaos

If you configure a master/slave connection we should inherit the character set from master if it is not set explicitly for the slave.

2016-12-27 14:05 UTC, kimhemsoe commented
Can you add a test?

2016-12-27 18:27 UTC, phansys requested changes
Status: Needs work.

2016-12-27 18:27 UTC, phansys commented on lib/Doctrine/DBAL/Connections/MasterSlaveConnection.php
> +        if (!isset($config['charset']) && isset($params['master']['charset'])) {
Please, respect CS (` ! isset()`).

2016-12-29 10:31 UTC, Deltachaos commented
Yes i will a a test

2017-10-13 12:45 UTC, Deltachaos commented
@kimhemsoe @phansys Tests have been added

2017-11-19 13:09 UTC, lcobucci requested changes
LGTM just some nitpicks, I'll apply the fixes, don't worry

2017-11-19 13:09 UTC, lcobucci commented on lib/Doctrine/DBAL/Connections/MasterSlaveConnection.php
> +        if (! isset($config['charset']) && isset($params['master']['charset'])) {
Missing whitespace **before** of  `!`

2017-11-19 13:09 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Functional/MasterSlaveConnectionTest.php
>          $params['wrapperClass'] = 'Doctrine\DBAL\Connections\MasterSlaveConnection';
Please change this to `MasterSlaveConnection::class`

2017-11-19 13:09 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Functional/MasterSlaveConnectionTest.php
> +     * @param bool $keepSlave
Please drop docblock

2017-11-19 13:09 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Functional/MasterSlaveConnectionTest.php
> +    public function createMasterSlaveConnection($keepSlave = false)
`public function createMasterSlaveConnection(bool $keepSlave = false) : MasterSlaveConnection`

2017-11-19 13:09 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Functional/MasterSlaveConnectionTest.php
> +    public function testInheritCharsetFromMaster()
` : void` missing

2017-11-19 13:09 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Functional/MasterSlaveConnectionTest.php
> +        $charsets = array(
Please use short-array syntax

2017-11-19 13:09 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Functional/MasterSlaveConnectionTest.php
> +            self::assertEquals(
`self::assertSame()` is more appropriated here (avoid type juggling and stuff)

2017-11-19 13:09 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Functional/MasterSlaveConnectionTest.php
> +    public function createMasterSlaveConnectionParams($keepSlave = false)
`public function createMasterSlaveConnectionParams(bool $keepSlave = false) : array`

2017-11-19 13:20 UTC, lcobucci approved these changes

2017-11-19 13:35 UTC, merged

2017-11-19 13:36 UTC, lcobucci commented
@Deltachaos 🚢 thanks for your contribution!

2017-11-21 15:05 UTC, Deltachaos commented
@lcobucci no problem. Can you have a look into doctrine/doctrine2#6812 as well? This bug currently prevents me from using the latest doctrine version.