[DBAL-2555] Fix date and datetimetz type mapping on Oracle
doctrine/dbal pull request #2612
Opened 2017-01-21 14:07 UTC by deeky666

Fixes #2555 

Oracle's `DATE` type was erroneously mapped to Doctrine's `DateTime` type. Although I wonder why nobody ever complained about that until now, the fix looks straight forward and also complies to what we have documented.

Additionally the instrospection of `DateTimeTzType` was wrong and has been fixed (wrong case in type comparison).

Tests pass locally.

2017-01-21 23:46 UTC, Ocramius requested changes

2017-01-21 23:46 UTC, Ocramius commented on lib/Doctrine/DBAL/Schema/OracleSchemaManager.php
> +            if (strpos($dbType, "with time zone")) {
Since this seems to be something that the DB engine doesn't guarantee, `strtolower()` should be used (or at least case insensitive matching).

2017-01-21 23:46 UTC, Ocramius commented on lib/Doctrine/DBAL/Schema/OracleSchemaManager.php
> +            if (strpos($dbType, "with time zone")) {
Test probably also needed with it, but unsure if practical

2017-01-22 16:33 UTC, deeky666 commented on lib/Doctrine/DBAL/Schema/OracleSchemaManager.php
> +            if (strpos($dbType, "with time zone")) {
Have a look at line 193 ;)
But besides that you reminded me that I forgot a unit test case for the mapping issue in the platform which I added now.

2017-01-22 16:34 UTC, deeky666 commented on lib/Doctrine/DBAL/Schema/OracleSchemaManager.php
> +            if (strpos($dbType, "with time zone")) {
This is is covered by the functional test case btw. Not sure how else to test this :>

2017-01-22 16:54 UTC, Ocramius approved these changes

2017-01-22 16:54 UTC, Ocramius commented on lib/Doctrine/DBAL/Schema/OracleSchemaManager.php
> +            if (strpos($dbType, "with time zone")) {
Dammit, didn't read that, thanks :-)

2017-01-23 10:01 UTC, DeepDiver1975 commented on tests/Doctrine/Tests/DBAL/Platforms/OraclePlatformTest.php
> +     * @group DBAK-2555
DBAL :wink:

2017-01-23 13:44 UTC, deeky666 commented on tests/Doctrine/Tests/DBAL/Platforms/OraclePlatformTest.php
> +     * @group DBAK-2555
thx, fixed

2017-01-23 22:51 UTC, merged

2017-01-23 22:51 UTC, Ocramius commented
:shipit:

2017-01-23 22:53 UTC, Ocramius commented
Backported via doctrine/dbal@8a13144aa046f4c218dc12ed48167de7b184416c