[DBAL2626] Add PHPUnit config for continuousphp Oracle testing
doctrine/dbal pull request #2630
Opened 2017-02-04 11:30 UTC by deeky666

Closes #2626.

2017-02-04 12:08 UTC, deeky666 commented
Seems to work. The error was expected and has to be fixed (it is a test error on Oracle 11g).

2017-02-04 13:50 UTC, photodude commented
Is there a reason for not using the new convention we set up for the config file naming?
- expected `tests/<service>/<db_type>.<db_version>.<dbal_driver_name>.<service>.xml`
- found `tests/continuousphp/oci8.phpunit.continuousphp.xml`

Does continuousphp not use a yml config file?

2017-02-04 16:19 UTC, deeky666 commented
@photodude I did not care about convention here because there is only 1 DB version and only 1 driver we want to test here.
Continuousphp does not have a config file, no. It is all configured via their web frontend.

2017-02-04 16:21 UTC, deeky666 commented
Though I can rename the phpunit config file is that is desired.

2017-02-04 19:24 UTC, Ocramius commented
Gotta love OracleDB's expressiveness:

```
1) Doctrine\Tests\DBAL\Functional\Driver\OCI8\OCI8ConnectionTest::testLastInsertIdAcceptsFqn 
Exception: [Doctrine\DBAL\Exception\DriverException] An exception occurred while executing 'CREATE TABLE DBAL2595(id NUMBER DEFAULT dbal2595_seq.NEXTVAL, foo NUMBER)': 
 
ORA-00984: column not allowed here 
 ```

2017-02-04 19:25 UTC, Ocramius requested changes
Need it to be green before we merge it, obviously.

2017-02-04 19:25 UTC, Ocramius commented on tests/continuousphp/oci8.phpunit.continuousphp.xml
> +<php>
Alignment is a bit borked all over the file ;-)

2017-02-04 19:54 UTC, photodude commented
Just a consistency item, if that is the convention that we want to try to stick to.

Also, isn't there two drivers to test, `PDO_OCI` and `OCI8`?

2017-02-05 12:24 UTC, deeky666 commented
@Ocramius I wanted to add a followup PR that fixes the test but I can do it right away with this PR if you want to.
@photodude you are right but the `PDO_OCI` PHP is very buggy since years and even was marked "experimental" until some time ago (no clue why they changed this). With `PDO_OCI` our testsuite is even segfaulting. Maybe we should remove support for it altogether. Also continuousphp does not have the driver installed so we won't be able to test against it out of the box anyways.

2017-02-05 12:51 UTC, deeky666 commented on tests/continuousphp/oci8.phpunit.continuousphp.xml
> +<php>
Fixed.

2017-02-05 13:14 UTC, deeky666 commented
@Ocramius fixed the failing test. It's green now :)

2017-02-05 19:09 UTC, Ocramius commented
LGTM! Finally some CI for OracleDB as well. I know we'll regret it, but at least we can enjoy a few moments of glory :-)

2017-02-05 19:09 UTC, merged