Fix fetching last insert ID for sequences on SQL Server
doctrine/dbal pull request #2634
Opened 2017-02-05 23:53 UTC by deeky666

Fixes fetching last insert ID for sequences on both `sqlsrv` and `pdo_sqlsrv` drivers. The implementation on `sqlsrv` was wrong and `pdo_sqlsrv` does not support this out of the box.

The issue was revealed in #2617. See:

- https://ci.appveyor.com/project/photodude/dbal/build/1.0.138/job/r1twtafm8vsaswy4#L441
- https://ci.appveyor.com/project/photodude/dbal/build/1.0.140/job/878bxlaoeiiajsqs

2017-02-05 23:59 UTC, Ocramius requested changes

2017-02-05 23:59 UTC, Ocramius commented on lib/Doctrine/DBAL/Driver/PDOSqlsrv/Connection.php
> +        $sql = 'SELECT CONVERT(VARCHAR(MAX), current_value) FROM sys.sequences WHERE name = ?';
Variable redundant

2017-02-05 23:59 UTC, Ocramius commented on lib/Doctrine/DBAL/Driver/PDOSqlsrv/Connection.php
> +        if (null === $name) {
Can a name be empty?

2017-02-05 23:59 UTC, Ocramius commented on lib/Doctrine/DBAL/Driver/PDOSqlsrv/Connection.php
> +        if (null === $name) {
As in `''`

2017-02-05 23:59 UTC, Ocramius commented on lib/Doctrine/DBAL/Driver/PDOSqlsrv/Connection.php
> +        return $stmt->fetchColumn();
Can `current_value` ever be `NULL`?

2017-02-06 00:00 UTC, deeky666 commented on lib/Doctrine/DBAL/Driver/PDOSqlsrv/Connection.php
> +        if (null === $name) {
I don't think so. What should we expect in this case?

2017-02-06 00:02 UTC, Ocramius commented on lib/Doctrine/DBAL/Driver/PDOSqlsrv/Connection.php
> +        if (null === $name) {
That's why I asked. Probably needs a new issue though, where we validate that the passed in value is not empty or such.

2017-02-06 00:05 UTC, deeky666 commented on lib/Doctrine/DBAL/Driver/PDOSqlsrv/Connection.php
> +        return $stmt->fetchColumn();
Given to [the documentation](https://msdn.microsoft.com/en-us/en-en/library/ff877934.aspx) no.

2017-02-06 00:05 UTC, deeky666 commented on lib/Doctrine/DBAL/Driver/PDOSqlsrv/Connection.php
> +        $sql = 'SELECT CONVERT(VARCHAR(MAX), current_value) FROM sys.sequences WHERE name = ?';
Redundant? You mean I should inject it into `prepare()` directly?

2017-02-06 00:06 UTC, Ocramius commented on lib/Doctrine/DBAL/Driver/PDOSqlsrv/Connection.php
> +        $sql = 'SELECT CONVERT(VARCHAR(MAX), current_value) FROM sys.sequences WHERE name = ?';
Correct

2017-02-06 00:06 UTC, deeky666 commented on lib/Doctrine/DBAL/Driver/PDOSqlsrv/Connection.php
> +        if (null === $name) {
@Ocramius the problem is the interface does not specify such case. Neither does PDO's interface. No exception, not non-string return value specified.

2017-02-06 00:10 UTC, Ocramius commented on lib/Doctrine/DBAL/Driver/PDOSqlsrv/Connection.php
> +        if (null === $name) {
Then all ok: had to ask 👍

2017-02-06 00:11 UTC, deeky666 commented on lib/Doctrine/DBAL/Driver/PDOSqlsrv/Connection.php
> +        if (null === $name) {
Sure, not happy with the situation either but that's what it is right now :(

2017-02-06 00:16 UTC, deeky666 commented
Btw the Oracle test failure is obviously unrelated. That test in question seems fragile. Think I have encountered that one on Oracle sometime before. Need to have a look at that.

2017-02-06 00:27 UTC, deeky666 commented on lib/Doctrine/DBAL/Driver/PDOSqlsrv/Connection.php
> +        $sql = 'SELECT CONVERT(VARCHAR(MAX), current_value) FROM sys.sequences WHERE name = ?';
Fixed.

2017-02-06 01:09 UTC, deeky666 commented
Test failure fixed in #2635

2017-02-06 01:55 UTC, merged

2017-02-06 01:57 UTC, Ocramius commented
Backported to `2.5` via doctrine/dbal@31c41ee0d5d09bd02ee3ef2e93f647d0ceed4363