[DBAL-2644] Fix fetchAll(PDO::FETCH_COLUMN) on DB2 with Portability wrapper
doctrine/dbal pull request #2647
Opened 2017-02-08 06:21 UTC by morozov

Fixes #2644:

1. Do not enforce platform-dependent portability settings
2. Properly handle the result of fetchAll(PDO::FETCH_COLUMN)

2017-02-08 08:00 UTC, Ocramius requested changes

2017-02-08 08:00 UTC, Ocramius commented on lib/Doctrine/DBAL/Portability/Statement.php
> +        if ($fetchMode === PDO::FETCH_COLUMN) {
@morozov can you isolate the contents of the `if` and `else` statements into private methods? Early return preferred

2017-02-08 08:00 UTC, Ocramius commented on lib/Doctrine/DBAL/Portability/Statement.php
> +                    if (($this->portability & Connection::PORTABILITY_EMPTY_TO_NULL) && $value === '') {
The first bitwise expression does not need re-computing within the loop, and should be moved to a variable

2017-02-08 08:00 UTC, Ocramius commented on lib/Doctrine/DBAL/Portability/Statement.php
> +                    } elseif (($this->portability & Connection::PORTABILITY_RTRIM) && is_string($value)) {
The first bitwise expression does not need re-computing within the loop, and should be moved to a variable

2017-02-09 16:48 UTC, Ocramius requested changes

2017-02-09 16:48 UTC, Ocramius commented on lib/Doctrine/DBAL/Portability/Statement.php
> +            $rows = $this->fixColumn($rows, $emptyToNull, $rTrim);
return early please

2017-02-09 16:48 UTC, Ocramius commented on lib/Doctrine/DBAL/Portability/Statement.php
> +        } else {
No need for `else`

2017-02-09 16:48 UTC, Ocramius commented on lib/Doctrine/DBAL/Portability/Statement.php
> +        if (!$emptyToNull && !$rTrim) {
Isn't it simpler to loop twice, and call two separate methods that do one the `emptyToNull` fixing, and the other the `rTrim` fixing?

2017-02-09 19:59 UTC, morozov commented on lib/Doctrine/DBAL/Portability/Statement.php
> +        if (!$emptyToNull && !$rTrim) {
I think ideally (if [performance allows](http://stackoverflow.com/questions/18144782/performance-of-foreach-array-map-with-lambda-and-array-map-with-static-function/26527704#26527704)), we could have just 2-3 lower level functions which convert keys and values, and combine them together in reusable combinations based on `fetch*(PDO::FETCH_*)`. But let's try your suggestion first.

2017-02-09 20:56 UTC, deeky666 commented on lib/Doctrine/DBAL/Portability/Statement.php
> +        if (!$emptyToNull && !$rTrim) {
Another idea that comes to mind is to normalize the rows at the beginning if `PDO::FETCH_COLUMN` is given and denormalize again at the end? Like expand the rows to a multi-dimensional array at the beginning and flatten again after portability adjustments? Not sure if that might be a better solution.

2017-02-09 21:04 UTC, morozov commented on lib/Doctrine/DBAL/Portability/Statement.php
> +        if (!$emptyToNull && !$rTrim) {
I think it'd look hacky but definitely save some lines of code.

2017-02-09 21:06 UTC, deeky666 commented on lib/Doctrine/DBAL/Portability/Statement.php
> +        if (!$emptyToNull && !$rTrim) {
The most important thing is it saves a lot of complexity and function calls which only serve for 1 use-case. But as I said, not sure about that, it is just an idea that came to my mind.

2017-02-15 07:58 UTC, morozov commented
@Ocramius are you okay with the current approach?

Off-topic: I tried putting together an [alternative implementation](https://github.com/doctrine/dbal/compare/master...morozov:portability-fun) which uses a functional approach to converting data and avoids code duplication, but… for some reason, there's even more code there than in the original one 😕

2017-02-16 19:14 UTC, Ocramius commented
@morozov I'm fine with it, and merging :-)

2017-02-16 19:14 UTC, Ocramius commented on lib/Doctrine/DBAL/Portability/Connection.php
>                  } elseif ($this->getDatabasePlatform()->getName() === "drizzle") {
Note for the next person that has to maintain this: we're sorry about this massive chain of doom and `elseif` :-(

2017-02-16 19:14 UTC, merged

2017-02-16 19:17 UTC, Ocramius commented
Backported to `2.5` via doctrine/dbal@5a4ff4673c98f18fc034c7222ce2d4b1481d4565