Test for duplicate foreign key entries
doctrine/dbal pull request #2667
Opened 2017-03-01 20:33 UTC by websmurf

In relation to issue #2576 I've created a test that covers this scenario

2017-03-06 13:58 UTC, websmurf commented
@Ocramius don't know why the tests have failed exactly btw, but it does not seem to relate to code change errors based on what I can find in travis logs

2018-08-01 23:03 UTC, morozov requested changes

2018-08-01 23:03 UTC, morozov commented on tests/Doctrine/Tests/DBAL/Platforms/MySQL57PlatformTest.php
> +            'ALTER TABLE documents DROP FOREIGN KEY documents_ibfk_1',
Given that the set of expected statements is different depending on the platform, I believe this feature should be tested in a functional way (statements are executed on a real DB) rather on the SQL level. This way, every DB platform will _prove_ the correctness of the generated statements.

2018-08-01 23:03 UTC, morozov commented on tests/Doctrine/Tests/DBAL/Platforms/AbstractMySQLPlatformTestCase.php
> +        $diff->addedForeignKeys['FK_a788692ffa0c224'] = $documents->getForeignKey('FK_a788692ffa0c224');
This is not what real DBAL usage looks like. The comparator should be used to produce the diff of two given schemas, the diff shouldn't be built in parallel with the schema(s).

2021-10-26 19:29 UTC, closed without merging