[Oracle] getListTableColumnsSQL returns columns ordered by position instead of by name.
doctrine/dbal pull request #2673
Opened 2017-03-10 19:27 UTC by mdwheele

Related: #1131

Hello!

This is my first contribution to DBAL, so I would appreciate any feedback on how I could improve this PR and future ones, if necessary. To the meat of it!

Other platforms (than Oracle) return column listings by position (implicitly). The `OraclePlatform` implementation explicitly orders by `column_name`. Order matters in my application of DBAL. I am building tooling for scheduled data migrations between platforms and would like to maintain ordering between migrations.

I have tested this to be the best of my ability locally, following the instructions for specifying `phpunit.xml` configuration. I am running Oracle XE 12c via [this docker container](https://hub.docker.com/r/sath89/oracle-12c). That said, tests are passing (with skipped / risky) but I **would appreciate extra scrutiny** to make sure I've made all necessary changes.

Thanks!

2017-03-10 22:56 UTC, morozov commented
@mdwheele I'd say it makes sense to add a functional test which would actually prove that the columns are now returned in the right order. It would also help seeing if the same is really true for the rest of supported platforms.

2017-03-10 23:05 UTC, mdwheele commented
I agree. Would you say that maintaining column positioning is the intended behaviour across platforms? If so, I can write up tests for some of the other platforms that verify current behaviour and we might also consider updating the queries to explicitly order by column position. That said, as long as there are functional tests that assert intended behaviour, we should be good. In fact, the default behaviour for Oracle seems to be to maintain column ordering (if you just leave out the order by clause altogether).

2017-03-10 23:15 UTC, morozov commented
> Would you say that maintaining column positioning is the intended behaviour across platforms?

I'm not that well familiar with the Doctrine. What I'm saying is any behavior should be the same for all supported platforms if possible.

> I can write up tests for some of the other platforms

I think it should be a single functional test which would execute regardles what the current platform is (see *tests/Doctrine/Tests/DBAL/Functional*).

2017-03-10 23:43 UTC, mdwheele commented
> I'm not that well familiar with the Doctrine. What I'm saying is any behavior should be the same for all supported platforms if possible.

Same here, haha. Agree behaviour should be same. This issue created some confusion for me this morning.

> I think it should be a single functional test which would execute regardless of what the current platform is (see tests/Doctrine/Tests/DBAL/Functional).

I agree. It looks like adding assertions on ordering [could be done here](https://github.com/doctrine/dbal/blob/master/tests/Doctrine/Tests/DBAL/Functional/Schema/SchemaManagerFunctionalTestCase.php#L195-L256) and would apply to all schema managers (which delegate to the platform). I'll go forward with adding extra assertions here and let CI handle setting up all the databases for functional tests. If things fail miserably, I'll do the work of getting everything running locally in containers. 

I'll probably stop for a bit after that until there's an "official" declaration of intended behaviour.

2017-03-11 03:26 UTC, mdwheele commented
After studying a little more and failing to reproduce CI results locally, I determined that it was because I am using Oracle 12c instead of Oracle XE 11g. I have pulled [sath89/oracle-xe-11g](https://hub.docker.com/r/sath89/oracle-xe-11g) and can now reliably run tests for Oracle locally. 

To be honest, I should have reverted my implementation change before committing 94df8b0 to show the failed assertion **only** for `OracleProvider`. That said, here are the results I get locally with `master`'s `OracleProvider`:

![capture](https://cloud.githubusercontent.com/assets/2453394/23820138/df9f9c8e-05df-11e7-91b9-47634e4150d6.PNG)

Arranging the key names in this test alphabetically, we get: 

0. `bar`
1. `baz1`
2. `baz2`
3. `baz3`
4. `foo`
5. `id`
6. `test`

`id` is in the 5th position while we assert it should remain the first column. When I use the patched `OracleProvider`: 

![capture](https://cloud.githubusercontent.com/assets/2453394/23820156/5f043b1a-05e0-11e7-8137-2bc5786cd8ac.PNG)

This is where 94df8b0 stands; passing.

I would like to pursue resolving the issues with Oracle 12c but think that is outside the scope of this PR. As far as I can tell, as long as CI is passing, the change in 94df8b0 should be asserting that all *other* providers maintain column position and that the `OracleProvider` now satisfies that assertion.

2017-03-11 14:30 UTC, deeky666 requested changes
Besides my nitpick, the patch looks good!

2017-03-11 14:30 UTC, deeky666 commented on tests/Doctrine/Tests/DBAL/Functional/Schema/SchemaManagerFunctionalTestCase.php
> +        $columns_keys = array_keys($columns);
Only nitpick I have: Please use camelCase throughout our codebase as we stick to PSR-2 coding standards.

2017-03-11 18:16 UTC, mdwheele commented
@deeky666 Haha, thanks for the review! Looks like CI failed 7.0 MariaDB 10.1 again. Is this an issue on Travis' side? Seems intermittent.

2017-03-11 18:17 UTC, deeky666 approved these changes

2017-03-11 18:19 UTC, merged

2017-03-11 18:19 UTC, deeky666 commented
@mdwheele yes it was a Travis problem. Restarted the job now it's green :) Thank you!

2017-03-11 18:26 UTC, deeky666 commented
Backported to `2.5` via https://github.com/doctrine/dbal/commit/fadc21b3b03e60ae78172ff6e2cb7d737895aa74 https://github.com/doctrine/dbal/commit/97eefb83660ecd29b4846924fa54aeff6a9701ba https://github.com/doctrine/dbal/commit/a8c4e5c9d95177e4f59f14717b05d19ead51fbc2 and https://github.com/doctrine/dbal/commit/3cc78d64199ff1bf9b9b40e24ba5dd7445fd01b5