DDC-3600
doctrine/dbal pull request #2677
Opened 2017-03-14 08:06 UTC by wenglockmok

First implementation of column INCLUDE-s for SQL Server non-clustered
indexes

2017-03-14 08:24 UTC, Ocramius requested changes

2017-03-14 08:24 UTC, Ocramius commented on lib/Doctrine/DBAL/Platforms/AbstractPlatform.php
> +    public function supportsCoveringIndexesWithColIncludes()
`ColumnIncludes` (don't abbreviate)

2017-03-14 08:24 UTC, Ocramius commented on lib/Doctrine/DBAL/Platforms/AbstractPlatform.php
> +        if ($this->supportsCoveringIndexesWithColIncludes() && $index->hasOption('include') && is_array($index->getOption('include')) && !$index->hasFlag('clustered')) {
Rewrite the conditional so that the `return ''` is within the `{}`, and the `INCLUDE` addition is the success scenario (at the end in this method)

2017-03-14 08:24 UTC, Ocramius commented on lib/Doctrine/DBAL/Platforms/AbstractPlatform.php
> +    protected function getCoveringIndexWithColIncludesSQL(Index $index)
This can now have a return type hint

2017-03-14 08:24 UTC, Ocramius commented on lib/Doctrine/DBAL/Platforms/AbstractPlatform.php
> +    public function supportsCoveringIndexesWithColIncludes()
This can have a return type hint

2017-03-14 08:24 UTC, Ocramius commented on lib/Doctrine/DBAL/Platforms/SQLServerPlatform.php
> +    public function supportsCoveringIndexesWithColIncludes()
return hint

2017-03-14 08:24 UTC, Ocramius commented on lib/Doctrine/DBAL/Platforms/SQLServerPlatform.php
> +     * @see \Doctrine\DBAL\Platforms\AbstractPlatform::supportsCoveringIndexesWithColIncludes()
Remove

2017-03-14 08:24 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Platforms/AbstractSQLServerPlatformTestCase.php
> +    public function testCreateNonClusteredIndexWithColIncludes()
We need tests on every combination in the conditional you wrote above

2017-03-14 08:24 UTC, Ocramius commented on lib/Doctrine/DBAL/Platforms/AbstractPlatform.php
> +     * Adds SQL for including columns in a covering index.
Please add an explanation regarding where this is needed/why

2017-03-14 08:24 UTC, Ocramius commented on lib/Doctrine/DBAL/Platforms/AbstractPlatform.php
> +    protected function getCoveringIndexWithColIncludesSQL(Index $index)
Add a comment explaining that an override is expected here

2017-03-14 08:25 UTC, Ocramius commented on lib/Doctrine/DBAL/Platforms/AbstractPlatform.php
> +        // included columns can only be used with unclustered indexes
This comment should probably be at the docblock level instead

2017-03-14 08:25 UTC, Ocramius commented
@wenglockmok was the change in the `_theme` submodule intentional?

2017-03-14 08:42 UTC, wenglockmok commented on lib/Doctrine/DBAL/Platforms/AbstractPlatform.php
> +     * Adds SQL for including columns in a covering index.
Hi @Ocramius - would this be good enough? 

```
     * Adds SQL for including columns in a covering index, which improves performance for queries, 
     * where selected columns not used in the index can be returned from the index lookup without a roundtrip to the actual table.
     *  
     * Note: columns can only be included with nonclustered indexes.
```

2017-03-14 08:44 UTC, wenglockmok commented
@Ocramius - my apologies!  The change to the _theme submodule was not intentional and is probably caused by my IDE.  Sorry about that!  Please ignore it.

2017-03-14 09:03 UTC, wenglockmok commented on lib/Doctrine/DBAL/Platforms/AbstractPlatform.php
> +    protected function getCoveringIndexWithColIncludesSQL(Index $index)
With the return type hint, did you mean something like - `protected function getCoveringIndexWithColumnIncludesSQL(Index $index): bool { ... }`?

Also, was the override meant to apply to the `supportsCoveringIndexWithColumnIncludesSQL()` function?

2021-10-26 19:25 UTC, morozov commented
Closing as stale.

2021-10-26 19:25 UTC, closed without merging