Keep track of full qualified type name when dealing with collections
doctrine/dbal pull request #2685
Opened 2017-03-22 15:55 UTC by sandvige

2017-03-22 15:58 UTC, Ocramius requested changes
Requires tests

2017-03-22 16:24 UTC, sandvige commented
@Ocramius Before trying harder to make unit tests, what do you think about the issue described above, and the solution we're trying to implement?

2017-03-22 16:29 UTC, Ocramius commented
I don't know what you are fixing without tests showing what is broken...

2017-03-27 17:27 UTC, sandvige commented on tests/Doctrine/Tests/DBAL/SQLParserUtilsTest.php
> +                array('datetime', 'datetime', 'datetime')
@Ocramius I added tests, I hope my tests are clear: we're trying to bring support for complex types into IN statements, like datetime, or any other custom types

2017-06-28 15:30 UTC, sandvige commented
@Ocramius?

2017-07-12 07:56 UTC, Ocramius requested changes

2017-07-12 07:56 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Functional/DataAccessTest.php
> +            $this->_conn->insert('fetch_table', array('test_int' => $i, 'test_string' => 'foo' . $i, 'test_datetime' => '2010-01-01 10:10:' . str_pad($i - 100, 2, "0", STR_PAD_LEFT)));
New tests should be written - existing tests should not be touched

2017-07-12 07:56 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Functional/DataAccessTest.php
> +        $stmt = $this->_conn->executeQuery('SELECT test_int FROM fetch_table WHERE test_int IN (?)',
Split out to a new test method

2017-07-12 07:56 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Functional/DataAccessTest.php
> +        $stmt = $this->_conn->executeQuery('SELECT test_int FROM fetch_table WHERE test_string IN (?)',
Split out to a new test method

2017-07-12 07:56 UTC, Ocramius commented on lib/Doctrine/DBAL/SQLParserUtils.php
> +        // [my_custom_type] -> my_custom_type
Ah, this is the trick: you are trying to use `[foo]` as an array mapping type of instances of `foo`.

The idea is good, but using strings for this is terrible, and we shouldn't let this land, as that is going to just complicate things much further.

A different approach could be needed here to define the type of a parameter: parsing the type is not viable...

2017-07-12 07:57 UTC, Ocramius commented
As mentioned in the review above, using strings for types is not viable for complex types. We should instead pass in a `ParameterType` object or such...

2017-07-18 13:00 UTC, sandvige commented on tests/Doctrine/Tests/DBAL/Functional/DataAccessTest.php
> +            $this->_conn->insert('fetch_table', array('test_int' => $i, 'test_string' => 'foo' . $i, 'test_datetime' => '2010-01-01 10:10:' . str_pad($i - 100, 2, "0", STR_PAD_LEFT)));
I had to change this because the value wasn't based on $i, this is just improving the way the test is working

2017-07-18 13:00 UTC, sandvige commented on tests/Doctrine/Tests/DBAL/Functional/DataAccessTest.php
> +        $stmt = $this->_conn->executeQuery('SELECT test_int FROM fetch_table WHERE test_int IN (?)',
Ok I could, but this is also a good way to prove the code is fully backward compatible

2017-07-18 13:00 UTC, sandvige commented on lib/Doctrine/DBAL/SQLParserUtils.php
> +        // [my_custom_type] -> my_custom_type
The DBAL project is already dealing with multiple types:
- string based types (looked up with Type::getType())
- PDO based types
- DBAL types (which are mixed in Connection::getBindingInfo() method)

We have to deal with strings without a major and full of BC breaks refacto ; this is how it currently works with Connection::ARRAY_PARAM_OFFSET. 

I understand this part is a major piece of the cake, maybe someone else could come with a better idea? We're already using this on our own project, and this is working well :)

2017-07-18 13:01 UTC, sandvige commented
@Ocramius Keep in mine the key feature is here: https://github.com/doctrine/doctrine2/pull/6354/files this is making your custom types being queriable through relationships \o/

2017-07-18 22:51 UTC, Ocramius commented on lib/Doctrine/DBAL/SQLParserUtils.php
> +        // [my_custom_type] -> my_custom_type
`"[foo]"` being considered `"special scenario in which the type represents an array of foo"` is not viable. What you are doing here is moving away from a simple map type, and converting type discovery into a function that actually creates more complex types.

I'd rather not have the feature at all than have it as magic strings.

 > We're already using this on our own project, and this is working well :)

The fact that it is working has nothing to do with correctness, sorry :-\

2021-10-26 19:29 UTC, closed without merging