MySQL: Fix primary key alteration when adding new columns
doctrine/dbal pull request #2696
Opened 2017-04-04 17:58 UTC by drieschel

Trying to get a column in a table which is not added yet, will result in throwing a SchemaException. Also altering not yet added columns does not make sense.

2017-04-10 07:08 UTC, drieschel commented
A feedback from someone of the doctrine/dbal team would be great.

2017-04-14 09:17 UTC, deeky666 requested changes

2017-04-14 09:17 UTC, deeky666 commented on lib/Doctrine/DBAL/Platforms/MySqlPlatform.php
> +            }
I think using the following check is more convenient and safer concerning the following `getColumn()` call:

```php
if (! $diff->fromTable->hasColumn($columnName)) {
    continue;
}
```

2017-04-14 11:42 UTC, drieschel commented
@deeky666 Done :)

2017-04-14 18:57 UTC, deeky666 requested changes

2017-04-14 18:57 UTC, deeky666 commented on lib/Doctrine/DBAL/Platforms/MySqlPlatform.php
> +            if(!$diff->fromTable->hasColumn($columnName)) {
sorry to nitpick but we use the following code style `if (! $diff` can you please adjust that? afterwards I'll merge.

2017-04-26 07:26 UTC, deeky666 approved these changes

2017-04-26 07:46 UTC, merged

2017-04-26 07:47 UTC, deeky666 commented
@drieschel thanks! Backported to `2.5` via c41cc5a6f03081ea5139050cb20901c0d663cd0c