Added missing filtering of table name assets in DB2SchemaManager
doctrine/dbal pull request #2702
Opened 2017-04-20 12:08 UTC by asgrim

Fixes #2701

2017-04-20 13:47 UTC, Ocramius requested changes

2017-04-20 13:47 UTC, Ocramius commented on lib/Doctrine/DBAL/Schema/DB2SchemaManager.php
> +        $tableNames = $this->_getPortableTablesList($tables);
assignment is redundant

2017-04-20 13:47 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Schema/DB2SchemaManagerTest.php
> +    public function testListTableNamesFiltersAssetNamesCorrectly()
Please add an `@group` annotation

2017-04-20 13:47 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Schema/DB2SchemaManagerTest.php
> +        $driverMock = $this->getMock(Driver::class);
I think we can use `createMock` already, since `master` only supports PHP 7.x

2017-04-20 13:47 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Schema/DB2SchemaManagerTest.php
> +        $platform = $this->getMock(DB2Platform::class);
Same

2017-04-20 13:52 UTC, asgrim commented on tests/Doctrine/Tests/DBAL/Schema/DB2SchemaManagerTest.php
> +        $driverMock = $this->getMock(Driver::class);
Doesn't seem available with a `composer up`...

2017-04-20 13:57 UTC, asgrim commented on lib/Doctrine/DBAL/Schema/DB2SchemaManager.php
> +        $tableNames = $this->_getPortableTablesList($tables);
Removed

2017-04-20 13:58 UTC, asgrim commented on tests/Doctrine/Tests/DBAL/Schema/DB2SchemaManagerTest.php
> +        $platform = $this->getMock(DB2Platform::class);
Same

2017-04-20 13:58 UTC, asgrim commented on tests/Doctrine/Tests/DBAL/Schema/DB2SchemaManagerTest.php
> +    public function testListTableNamesFiltersAssetNamesCorrectly()
Added

2017-05-02 11:31 UTC, Ocramius approved these changes

2017-05-02 11:31 UTC, Ocramius commented
@asgrim LGTM - merging into `master` only though, so it will land in `2.6` (PHP 7.x)

2017-05-02 11:32 UTC, merged

2017-05-02 11:40 UTC, asgrim commented
Makes sense, thanks!

2017-05-02 14:48 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Schema/DB2SchemaManagerTest.php
> +        $driverMock = $this->getMock(Driver::class);
The problem is [that we're depending on an old PHPUnit version](https://github.com/doctrine/dbal/blob/1b3c36b4550d4e29d2a896e032d7432d411682d1/composer.json#L19).