Update ExpressionBuilder.php
doctrine/dbal pull request #2711
Opened 2017-05-04 08:36 UTC by rabihsyw

parse array values as strings

2017-05-04 08:44 UTC, Ocramius commented
This patch needs additional tests and a better description. Also, check existing tests (they seem to fail on travis-ci)

2017-05-04 10:58 UTC, Ocramius requested changes

2017-05-04 10:58 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Query/Expression/ExpressionBuilderTest.php
> +        $this->assertEquals("u.groups IN ('1', '3', '4', '7')", $this->expr->in('u.groups', array(1, 3, 4, 7)));
This test shouldn't have changed

2017-05-04 10:58 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Query/Expression/ExpressionBuilderTest.php
> +        $this->assertEquals("u.groups NOT IN ('1', '3', '4', '7')", $this->expr->notIn('u.groups', array(1, 3, 4, 7)));
This test shouldn't have changed

2021-07-09 01:41 UTC, morozov commented
The API is improperly documented. Similar to the majority of the similar `AbstractPlatform` methods, `in()` expects an array of SQL expressions, not values.

2021-07-09 01:41 UTC, closed without merging