Fix - Duplicate 'COMMENT' part in SQL statement
doctrine/dbal pull request #2730
Opened 2017-05-16 15:19 UTC by mondrake

If you pass both a 'columnDefinition' containing a comment, _and_ a 'comment' option, to a column when creating /altering a table, the SQL statement produced by the schema has a duplicate COMMENT part.

The following code
```
  $table = new Table('my_table');
  $table->addColumn('id', 'integer', array(
    'columnDefinition' => 'INT DEFAULT 0 NOT NULL COMMENT \'expected+column+comment\'', 
    'comment' => 'unexpected_column_comment')
  );
  $sql = $this->_conn->getDatabasePlatform()->getCreateTableSQL($table);
```
will generate:
```
CREATE TABLE my_table 
(id INT DEFAULT 0 NOT NULL COMMENT 'expected+column+comment' COMMENT 'unexpected_column_comment') 
DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB
```

2017-05-16 15:20 UTC, mondrake commented
@Ocramius sorry for the mess on the other 2 PRs.

2017-05-18 15:36 UTC, phansys requested changes
Status: Needs work.

2017-05-18 15:36 UTC, phansys commented on tests/Doctrine/Tests/DBAL/Functional/Schema/SchemaManagerFunctionalTestCase.php
> +            'notnull' => TRUE,
Please, use `true` instead.

2017-05-18 17:02 UTC, mondrake commented on tests/Doctrine/Tests/DBAL/Functional/Schema/SchemaManagerFunctionalTestCase.php
> +            'notnull' => TRUE,
@phansys thanks, I'm used to Drupal CS which is just the opposite :(

2017-05-23 09:21 UTC, mondrake commented
Made changes requested.

2017-06-01 12:50 UTC, Ocramius approved these changes
Merging at the soonest occasion, as I cannot backport from here

2017-06-29 17:47 UTC, closed without merging

2017-06-29 17:49 UTC, Ocramius commented
Merged, thanks @mondrake!

`master`: doctrine/dbal@e60a5828186c2d15e53d1875703ed27b076abccd
`2.5`: doctrine/dbal@994f3b0002496cc380c9755869c87ff526d7f451