Bulk inserts
doctrine/dbal pull request #2762
Opened 2017-06-29 20:26 UTC by edefimov

This is an updated version of PR #682 solving issue #1392  refactored for php 7.1 and with small improvements like bulk insert execution even when the number of rows exceeds database limits.

2017-07-02 10:14 UTC, Ocramius commented
@deeky666 this patch introduces some fixups on your existing bulk-insert patch.

Specifically, it will force transactions when an `insert` operation is acting on a range of values bigger than what the database supports.

We should consider further scenarios too:

 * when a query string is bigger than what is endorsed by the DB engine
 * when the number of bound parameters is bigger than what is allowed by the DB engine (for example, that's 1000 on OracleDB)

2017-08-28 02:34 UTC, LisTo4ek commented on lib/Doctrine/DBAL/Query/BulkInsertQuery.php
> +            $parameters = array_slice($this->parameters, $offset, $insertMaxRows);
Here should be something like:
$parameters = array_slice($this->parameters, $offset * count($this->values), $insertMaxRows * count($this->values));

2018-06-12 01:24 UTC, morozov requested changes
@edefimov thank you for the patch. Please rebase it and make sure the most generic cases are tested in a functional way.

2019-09-10 14:29 UTC, karousn commented
any news about this ? available in next major version(3) ?

2020-01-14 18:19 UTC, claudiobizzotto commented
Until this gets incorporated into the next major release, here's a temporary option: https://github.com/pharako/mysql-dbal

2020-05-21 04:19 UTC, takahashiyuya commented
i hope can use it.

2021-10-26 19:25 UTC, morozov commented
Closing as stale.

2021-10-26 19:25 UTC, closed without merging