Added failure test where platform from params is passed to QueryCache…
doctrine/dbal pull request #2821
Opened 2017-08-22 18:16 UTC by kimhemsoe

If you pass in the platform from connection params it will be used to generate the cache key, which i most cases will as not it will not serializable 

https://github.com/doctrine/dbal/blob/db1395b7d2baaa3a027a3727fa34e17a5a85d54f/lib/Doctrine/DBAL/Cache/QueryCacheProfile.php#L105

I can create a better test case where it will fail from the serialize() call if needed. But i was lazy, copy pasted one there fitted my case :D

2017-08-22 18:29 UTC, kimhemsoe commented
Any suggestions for how i fix this?

One way  could be to remove  it from params in detectDatabasePlatform, but only happens if getPlatform have been called.

We could also check for it in the the constructor, or remove it from the passed connection params to generateCacheKeys()

And would there be any BC concerns with removing it from params, after we have assign it to $this->_platform?

2017-08-24 10:46 UTC, Ocramius requested changes

2017-08-24 10:46 UTC, Ocramius commented on lib/Doctrine/DBAL/Connection.php
> +                throw DBALException::invalidPlatformSpecified();
Should at least pass in the `$params['platform']` and let the exception produce a more detailed message about what was given instead.

2017-08-24 10:46 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/ConnectionTest.php
> +        $query  = 'SELECT * FROM foo WHERE bar = ?';
Use a simpler `SELECT 1` query - remove all unnecessary params/types

2017-08-24 10:46 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/ConnectionTest.php
> +        $connectionParams["platform"] = $this->createMock(AbstractPlatform::class);
Single quotes

2017-08-24 10:46 UTC, Ocramius commented on lib/Doctrine/DBAL/Connection.php
> +            if ( ! $params['platform'] instanceof Platforms\AbstractPlatform) {
This branch isn't tested

2017-08-24 10:46 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/ConnectionTest.php
> +        $expectedParams = $connectionParams;
Remove this variable - just rely on `$connectionParams` below

2017-08-24 10:46 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/ConnectionTest.php
> +            (new Connection($connectionParams, $driver))->executeCacheQuery($query, $params, $types, $queryCacheProfileMock)
Add a message to `assertInstanceOf`

2017-08-24 10:46 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/ConnectionTest.php
> +        $this->assertInstanceOf(
`self::assertInstanceOf()`

2017-08-24 10:46 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/ConnectionTest.php
> +    public function testShouldNotPassPlatformInParamsToTheQueryCacheProfileInExecuteCacheQuery()
Add an `@group` annotation to the test

2017-08-24 10:46 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/ConnectionTest.php
> +    public function testShouldNotPassPlatformInParamsToTheQueryCacheProfileInExecuteCacheQuery()
Mark the method as `void`

2017-08-24 20:53 UTC, kimhemsoe commented on tests/Doctrine/Tests/DBAL/ConnectionTest.php
> +            (new Connection($connectionParams, $driver))->executeCacheQuery($query, $params, $types, $queryCacheProfileMock)
Removing the assert as it is tested by "testConnectionParamsArePassedToTheQueryCacheProfileInExecuteCacheQuery"

2017-08-24 21:39 UTC, kimhemsoe commented on lib/Doctrine/DBAL/Connection.php
> +            if ( ! $params['platform'] instanceof Platforms\AbstractPlatform) {
Fixed

2017-08-24 21:43 UTC, kimhemsoe commented on lib/Doctrine/DBAL/Connection.php
> +                throw DBALException::invalidPlatformSpecified();
I've added more detailed exception message if an object is given. If another type is given it fails horrible and the bottom of your coffee mug will go out. Should i try to add support for any type? Or are we ok with that? :D

2017-08-24 21:46 UTC, kimhemsoe commented
Can someone give me a hint why Scrutinizer is suddenly throwing up?

2017-08-25 03:42 UTC, Ocramius requested changes

2017-08-25 03:42 UTC, Ocramius commented on lib/Doctrine/DBAL/DBALException.php
> +     * @param $invalidPlatform
`mixed`

2017-08-25 03:42 UTC, Ocramius commented on lib/Doctrine/DBAL/DBALException.php
> +     * @param $invalidPlatform
Needs to be documented as BC break or moved to a new method

2017-08-25 03:42 UTC, Ocramius commented on lib/Doctrine/DBAL/DBALException.php
> +            get_class($invalidPlatform),
Could be a non-object

2017-08-25 03:42 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/ConnectionTest.php
> +        // This is our main expectation
Comment can be dropped: if there were no expectations, the test would be marked as risky

2017-08-25 03:42 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/ConnectionTest.php
> +        self::expectExceptionMessage(
This needed to be a `$this->` call (IIRac, it's an instance method)

2017-08-25 03:42 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/ConnectionTest.php
> +        self::expectException(DBALException::class);
This needed to be a `$this->` call (IIRac, it's an instance method)

2017-08-25 03:42 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/ConnectionTest.php
> +            "Given 'platform' option 'stdClass' must be a subtype of 'Doctrine\DBAL\Platforms\AbstractPlatform'"
Thos should be a test on the exception test itself

2017-08-25 03:42 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/ConnectionTest.php
> +        self::expectException(DBALException::class);
Move the exception expectations right before the method call that raises them

2017-08-25 03:44 UTC, Ocramius commented
Scrutinizer fails on the mocks union types: ignore

On 24 Aug 2017 11:46 PM, "Kim Hemsø Rasmussen" <notifications@github.com>
wrote:

> Can someone give me a hint why Scrutinizer is suddenly throwing up?
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/doctrine/dbal/pull/2821#issuecomment-324766447>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAJakNJDWjAYfYQMswRTNhHW4SFmp8E2ks5sbe9CgaJpZM4O-_04>
> .
>

2017-08-28 10:51 UTC, merged

2017-08-28 10:53 UTC, Ocramius commented
@kimhemsoe merged and backported, thanks!

`master`: doctrine/dbal@ce7560f2d65a2fe0d3521921f208c60fed209090
`2.6`: doctrine/dbal@367b731d0051d4e56bde26b092ae38568a9f6dd0