Style improvements
doctrine/dbal pull request #2858
Opened 2017-09-11 18:24 UTC by greg0ire

Cleans up the mess I introduced in #2835 and #2851 

@SenseException @lcobucci please review

2017-09-11 18:31 UTC, Majkl578 requested changes

2017-09-11 18:31 UTC, Majkl578 commented on tests/Doctrine/Tests/DBAL/Platforms/AbstractPlatformTestCase.php
> +        $this->assertSame(
Should use `self::`.

2017-09-11 18:31 UTC, Majkl578 commented on tests/Doctrine/Tests/DBAL/Platforms/AbstractPlatformTestCase.php
> +    public function testGetDefaultValueDeclarationSQLForDateType(): void
Space around `:`.

2017-09-12 09:20 UTC, SenseException commented
Does Doctrine have a coding standard about concatenation of strings with `.`? Spaces or no spaces?

2017-09-12 09:22 UTC, Ocramius commented
Spaces

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

On Tue, Sep 12, 2017 at 11:20 AM, Claudio Zizza <notifications@github.com>
wrote:

> Does Doctrine have a coding standard about concatenation of strings with .?
> Spaces or no spaces?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/doctrine/dbal/pull/2858#issuecomment-328794946>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAJakP-qMekV-7RQUvw8V8n-cWP4Ei_Iks5shkz4gaJpZM4PTk9f>
> .
>

2017-09-12 09:40 UTC, SenseException commented
I have nothing to add here. :+1:

2017-09-12 09:49 UTC, lcobucci commented
@SenseException you can see more info on https://github.com/doctrine/coding-standard

2017-09-12 09:50 UTC, merged