Default value declaration for immutable types
doctrine/dbal pull request #2861
Opened 2017-09-13 09:38 UTC by tok-amsiq

2017-09-13 14:30 UTC, Majkl578 submitted a review, later dismissed
It appears there are no tests for Date type, could you possibly cherry-pick #2851 and expand it to include DateImmutable as well?

2017-09-13 14:30 UTC, Majkl578 commented on lib/Doctrine/DBAL/Platforms/AbstractPlatform.php
>                  } elseif ((string) $field['type'] == 'Time' && $field['default'] == $this->getCurrentTimeSQL()) {
There should also be TimeImmutable.

2017-09-13 15:06 UTC, tok-amsiq commented
Implemented TimeImmutable and tests for Date/DateImmutable types

2017-09-19 18:39 UTC, greg0ire commented
@tok-amsiq it does not look like you cherry-picked my commit

2017-09-20 06:29 UTC, tok-amsiq commented
@greg0ire it went a little fast when I read it, it has been cherry picked now :-)

2017-09-20 09:37 UTC, tok-amsiq commented
The check that fails doesn't seem to have anything to do with my commit

2017-09-20 09:41 UTC, greg0ire commented
@tok-amsiq you can try closing and reopening your PR, this looks like a transient Travis error.

2017-09-20 09:53 UTC, greg0ire commented
Green :)

2017-09-20 09:54 UTC, tok-amsiq commented
@greg0ire yea it did the trick, cheers 👍

2017-09-25 08:54 UTC, tok-amsiq commented
@Ocramius can this be added to the 2.6.3 milestone? :-)

2017-09-25 13:22 UTC, lcobucci requested changes
There's also a lot of duplication on the tests, do you see a way to simplify this?

Also, the destination branch of this fix should be `master` and we handle the necessary cherry-picks.

2017-09-25 13:22 UTC, lcobucci commented on lib/Doctrine/DBAL/Platforms/AbstractPlatform.php
> +                } elseif (in_array((string) $field['type'], array('DateTime', 'DateTimeTz', 'DateTimeImmutable', 'DateTimeTzImmutable')) && $field['default'] == $this->getCurrentTimestampSQL()) {
Please use short-array syntax here

2017-09-25 13:22 UTC, lcobucci commented on lib/Doctrine/DBAL/Platforms/AbstractPlatform.php
> +                } elseif (in_array((string) $field['type'], array('Time', 'TimeImmutable')) && $field['default'] == $this->getCurrentTimeSQL()) {
Please use short-array syntax here

2017-09-25 13:22 UTC, lcobucci commented on lib/Doctrine/DBAL/Platforms/AbstractPlatform.php
> +                } elseif (in_array((string) $field['type'], array('Date', 'DateImmutable')) && $field['default'] == $this->getCurrentDateSQL()) {
Please use short-array syntax here

2017-09-25 13:22 UTC, lcobucci commented on lib/Doctrine/DBAL/Platforms/SQLServerPlatform.php
> +        if (in_array((string) $field['type'], array('DateTime', 'DateTimeTz', 'DateTimeImmutable', 'DateTimeTzImmutable')) && $field['default'] == $this->getCurrentTimestampSQL()) {
Please use short-array syntax here

2017-09-25 13:22 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Platforms/AbstractPlatformTestCase.php
> +        foreach (array('datetime', 'datetimetz', 'datetime_immutable', 'datetimetz_immutable') as $type) {
Please use short-array syntax here

2017-09-25 13:22 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Platforms/AbstractPlatformTestCase.php
> +	    foreach (array('date', 'date_immutable') as $type) {
Please use short-array syntax here

2017-09-25 13:22 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Platforms/AbstractPlatformTestCase.php
> +		    $field = array(
Please use short-array syntax here

2017-09-25 13:22 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Platforms/SQLServer2008PlatformTest.php
> +	    foreach (array('date', 'date_immutable') as $type) {
Please use short-array syntax here

2017-09-25 13:22 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Platforms/SQLServerPlatformTest.php
> +	    foreach (array('date', 'date_immutable') as $type) {
Please use short-array syntax here

2017-09-25 13:22 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Platforms/AbstractPlatformTestCase.php
> +            $this->assertEquals(
Please use `self::assert*` instead, and it would be better to use `assertSame()` in this case

2017-09-25 13:22 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Platforms/AbstractPlatformTestCase.php
> +		    $this->assertEquals(
Please use `self::assert*` instead, and it would be better to use `assertSame()` in this case

2017-09-25 13:22 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Platforms/AbstractPlatformTestCase.php
> +	    foreach (array('date', 'date_immutable') as $type) {
Please use the short-array syntax here

2017-09-25 13:22 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Platforms/AbstractPlatformTestCase.php
> +	    foreach (array('date', 'date_immutable') as $type) {
And fix the indentation =)

2017-09-25 13:22 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Platforms/AbstractPlatformTestCase.php
> +    public function testGetDefaultValueDeclarationSQLForDateType()
Please add ` : void` here

2017-09-25 13:22 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Platforms/SQLServer2008PlatformTest.php
> +		    $this->assertEquals(
Please use `self::assert*` instead, and it would be better to use `assertSame()` in this case

2017-09-25 13:22 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Platforms/SQLServer2012PlatformTest.php
> +		    $this->assertEquals(
Please use `self::assert*` instead, and it would be better to use `assertSame()` in this case

2017-09-25 13:22 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Platforms/SQLServerPlatformTest.php
> +		    $this->assertEquals(
Please use `self::assert*` instead, and it would be better to use `assertSame()` in this case

2017-09-25 13:22 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Platforms/SQLServer2008PlatformTest.php
> +    public function testGetDefaultValueDeclarationSQLForDateType()
Please add ` : void` here

2017-09-25 13:22 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Platforms/SQLServer2012PlatformTest.php
> +    public function testGetDefaultValueDeclarationSQLForDateType()
Please add ` : void` here

2017-09-25 13:22 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Platforms/SQLServerPlatformTest.php
> +    public function testGetDefaultValueDeclarationSQLForDateType()
Please add ` : void` here

2017-09-25 13:22 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Platforms/SQLServer2008PlatformTest.php
> +	    foreach (array('date', 'date_immutable') as $type) {
Please use the short-array syntax here

2017-09-25 13:22 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Platforms/SQLServer2008PlatformTest.php
> +	    foreach (array('date', 'date_immutable') as $type) {
And fix the indentation

2017-09-25 13:22 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Platforms/SQLServer2008PlatformTest.php
> +		    $field = array(
Please use the short-array syntax here

2017-09-25 13:22 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Platforms/SQLServer2012PlatformTest.php
> +	    foreach (array('date', 'date_immutable') as $type) {
Please use the short-array syntax here

2017-09-25 13:22 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Platforms/SQLServer2012PlatformTest.php
> +		    $field = array(
Please use the short-array syntax here

2017-09-25 13:22 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Platforms/SQLServer2012PlatformTest.php
> +	    foreach (array('date', 'date_immutable') as $type) {
And fix the indentation too =)

2017-09-25 13:22 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Platforms/SQLServerPlatformTest.php
> +	    foreach (array('date', 'date_immutable') as $type) {
Please use the short-array syntax here

2017-09-25 13:22 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Platforms/SQLServerPlatformTest.php
> +		    $field = array(
Please use the short-array syntax here

2017-09-25 13:22 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Platforms/SQLServerPlatformTest.php
> +	    foreach (array('date', 'date_immutable') as $type) {
And fix the indentation

2017-09-25 13:22 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Platforms/SQLServerPlatformTest.php
> +			    " DEFAULT '".$currentDateSql."'",
Missing spaces before and after concatenation operator

2017-09-25 13:22 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Platforms/SQLServer2012PlatformTest.php
> +			    " DEFAULT '".$currentDateSql."'",
Missing spaces before and after concatenation operator

2017-09-25 13:22 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Platforms/SQLServer2008PlatformTest.php
> +			    " DEFAULT '".$currentDateSql."'",
Missing spaces before and after concatenation operator

2017-09-25 13:22 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Platforms/AbstractPlatformTestCase.php
> +			    ' DEFAULT '.$currentDateSql,
Missing spaces before and after concatenation operator

2017-09-25 13:22 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Platforms/AbstractPlatformTestCase.php
> +	            $this->_platform->getDefaultValueDeclarationSQL($field)
Indentation is wrong

2017-09-25 13:22 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Platforms/AbstractPlatformTestCase.php
>              $field = array(
Please use short-array syntax here

2017-09-25 13:22 UTC, lcobucci commented on lib/Doctrine/DBAL/Platforms/AbstractPlatform.php
> +                } elseif (in_array((string) $field['type'], array('Time', 'TimeImmutable')) && $field['default'] == $this->getCurrentTimeSQL()) {
Please use the third parameter in `in_array()` and is it possible to use strict comparison on the `$field['default']` instead?

2017-09-25 13:22 UTC, lcobucci commented on lib/Doctrine/DBAL/Platforms/AbstractPlatform.php
> +                } elseif (in_array((string) $field['type'], array('DateTime', 'DateTimeTz', 'DateTimeImmutable', 'DateTimeTzImmutable')) && $field['default'] == $this->getCurrentTimestampSQL()) {
Please use the third parameter in `in_array()` and is it possible to use strict comparison on the `$field['default']` instead?

2017-09-26 07:36 UTC, tok-amsiq commented
@lcobucci the requested changes should be fixed now and I've set the base branch to master as well. About the duplicated tests, I've moved the DateType tests from SQLServer, -2008 and -2012 to the AbstractSQLServer. If there's anything I missed, just let me know.

2017-11-18 23:13 UTC, lcobucci approved these changes

2017-11-18 23:29 UTC, merged

2017-11-18 23:31 UTC, lcobucci commented
@tok-amsiq merged and backported, thanks for your contribution!