Fixes custom type comment regex
doctrine/dbal pull request #2905
Opened 2017-11-07 07:00 UTC by jeremy-smith-maco

This is the same fix as #2679 which fixes the issue #2596 but this PR has tests for the change.

2017-11-12 11:03 UTC, lcobucci requested changes
Some small changes, thanks for your contribution

2017-11-12 11:03 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Functional/Schema/SchemaManagerFunctionalTestCase.php
> +    public function testExtractDoctrineTypeFromComment()
Please add ` : void`

2017-11-12 11:03 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Functional/Schema/SchemaManagerFunctionalTestCase.php
> +        self::assertEquals('type.should.return', $result);
`assertSame()` is more appropriated here

2017-11-12 11:03 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Functional/Schema/SchemaManagerFunctionalTestCase.php
> +        $result = $this->_sm->extractDoctrineTypeFromComment('(DC2Type:type.should.return)', $currentType);
Could you use a data provider for this test? It would become much simpler 😄

2017-11-12 22:34 UTC, jeremy-smith-maco commented
Done @lcobucci

2017-11-14 10:47 UTC, lcobucci requested changes
Nice job, just some more small things 😄

2017-11-14 10:47 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Functional/Schema/SchemaManagerFunctionalTestCase.php
> +     * @return array
Please drop this

2017-11-14 10:47 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Functional/Schema/SchemaManagerFunctionalTestCase.php
> +     * @param string $comment
Please drop the `@param` and `@return` annotations

2017-11-14 10:47 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Functional/Schema/SchemaManagerFunctionalTestCase.php
> +    public function testExtractDoctrineTypeFromComment($comment, $expected, $currentType) : void
Please add the type declarations for the parameters

2017-11-14 10:47 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Functional/Schema/SchemaManagerFunctionalTestCase.php
> +        return array(
Please use short-array syntax

2017-11-14 10:47 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Functional/Schema/SchemaManagerFunctionalTestCase.php
> +        return array(
Please define the indexes of the array with a short description of what the set of parameters is about, in order to improve PHPUnit's messages. Like:

```php
return [
    'invalid custom type comments' => ['should.return.current.type', $currentType, $currentType],
    'valid custom type with dots'  => ['(DC2Type:type.should.return)', 'type.should.return', $currentType],
];
```

2017-11-14 22:33 UTC, jeremy-smith-maco commented
Done @lcobucci

2017-11-19 00:34 UTC, lcobucci approved these changes

2017-11-19 00:45 UTC, merged

2017-11-19 00:51 UTC, lcobucci commented
@jeremy-smith-maco merged (with some minor changes - specially to also give credit to @PedroTroller) and backported. Thanks for your contribution!