Fix changing column from int to bigint with autoincrement
doctrine/dbal pull request #2916
Opened 2017-11-15 15:53 UTC by icewind1991

Currently it tries to alter the column type to `BIGSERIAL` which is not a valid type to be used in an `ALTER TABLE` query.

Also it currently drops the default which breaks the auto increment.

cc @nickvergessen

2017-11-19 12:58 UTC, lcobucci requested changes
Please rebase your branch to sync to the latest changes of `master`

2017-11-19 12:58 UTC, lcobucci commented on lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php
> +                $oldTypeIsNumeric = $columnDiff->fromColumn->getType()->getName() === Type::INTEGER || $columnDiff->fromColumn->getType()->getName() === Type::BIGINT;
Please don't rely on `Type::getName()`, use `instance of` instead.

2017-11-19 12:58 UTC, lcobucci commented on lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php
> +                $newTypeIsNumeric = $column->getType()->getName() === Type::INTEGER || $column->getType()->getName() === Type::BIGINT;
Please don't rely on `Type::getName()`, use `instance of` instead.

2017-11-19 12:58 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Functional/Schema/PostgreSqlSchemaManagerTest.php
> +    public function testAlterTableAutoIncrementBigInt()
` : void` missing

2017-11-19 12:58 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Functional/Schema/PostgreSqlSchemaManagerTest.php
> +        $tableFrom = new \Doctrine\DBAL\Schema\Table('autoinc_table_bitgint');
Please simplify the FQCN

2017-11-19 12:58 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Functional/Schema/PostgreSqlSchemaManagerTest.php
> +        $tableTo = new \Doctrine\DBAL\Schema\Table('autoinc_table_bitgint');
Please simplify the FQCN

2017-11-19 12:58 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Functional/Schema/PostgreSqlSchemaManagerTest.php
> +        $c = new \Doctrine\DBAL\Schema\Comparator();
Please simplify the FQCN

2017-11-19 12:58 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Functional/Schema/PostgreSqlSchemaManagerTest.php
> +        self::assertEquals(array("ALTER TABLE autoinc_table_bitgint ALTER id TYPE BIGINT"), $this->_conn->getDatabasePlatform()->getAlterTableSQL($diff));
`assertSame()` is more appropriated here

2017-11-19 12:58 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Functional/Schema/PostgreSqlSchemaManagerTest.php
> +        self::assertEquals(array("ALTER TABLE autoinc_table_bitgint ALTER id TYPE BIGINT"), $this->_conn->getDatabasePlatform()->getAlterTableSQL($diff));
Please also use short-array syntax

2017-11-19 12:58 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Functional/Schema/PostgreSqlSchemaManagerTest.php
> +    public function testAlterTableAutoIncrementBigInt()
Please add `@group 2916` to a docblock here

2017-11-20 13:12 UTC, icewind1991 commented
@lcobucci all done

2017-11-20 13:48 UTC, lcobucci requested changes
Nice job, some more nitpicks 😜

~Just to understand, is this needed only for PGSQL 10+ compatibility? I mean, I didn't see any issue reporting this before.~
~This question is just to categorise this PR correctly.~

I've already checked, this operation breaks badly on PGSQL 9.x too

2017-11-20 13:48 UTC, lcobucci commented on tests/Doctrine/Tests/DBAL/Functional/Schema/PostgreSqlSchemaManagerTest.php
> +        self::assertInstanceOf('Doctrine\DBAL\Schema\TableDiff', $diff, "There should be a difference and not false being returned from the table comparison");
Please use `TableDiff::class` instead

2017-11-20 13:48 UTC, lcobucci commented on lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php
> +            if ($columnDiff->fromColumn) {
What do you think about extracting this `if` block to a private method? I think that something like would improve the readability a bit:

```php
private function hasDefaultTypeChanged(ColumnDiff $columnDiff, Column $newColumn) : bool
{
    $defaultTypeChanged = $columnDiff->hasChanged('type');

    if ( ! $columnDiff->fromColumn || ! $defaultTypeChanged) {
        return $defaultTypeChanged;
    }

    $oldTypeIsNumeric = $this->isNumericType($columnDiff->fromColumn->getType());
    $newTypeIsNumeric = $this->isNumericType($newColumn->getType());

    return ! ($oldTypeIsNumeric && $newTypeIsNumeric && $newColumn->getDefault() === null)
}
```

We might improve things there (specially naming wise), but I think it makes things easier and more understandable 😄

2017-11-20 13:50 UTC, lcobucci commented
One last request, could add some info on the commit msg on why this is needed? BTW thanks for ensuring that the commit history is organised =)

2017-11-20 13:56 UTC, lcobucci commented
Ahhh I forgot one more thing, can you please add a test for the reverse operation too? bigint -> int

2017-11-20 15:23 UTC, icewind1991 commented
done

2017-11-20 21:28 UTC, lcobucci approved these changes

2017-11-20 21:57 UTC, merged

2017-11-20 21:59 UTC, lcobucci commented
@icewind1991 🚢 and backported to `2.6.x` (with some minor improvements). Thanks for your contribution!

2017-11-21 15:06 UTC, icewind1991 commented
Any chance of getting things backported to 2.5.x? We're stuck with supporting php 5.6/7.0 for the foreseeable future