Platform names as constants
doctrine/dbal pull request #2986
Opened 2018-01-22 12:08 UTC by simPod

I'd like to reference these from outside for eg. platform mapping to other db libraries.

Is this therefore viable?

2018-01-23 12:41 UTC, lcobucci requested changes
@simPod I honestly don't see much benefit on this kind of change, I'd rather remove `AbstractPlatform#getName()` and simply rely on `instanceof` - which you would be able to use the class reference ([even as string](https://3v4l.org/IKBqc)).

@Ocramius what's your take on this?

2018-01-26 10:29 UTC, Ocramius commented
`develop` was rebased on `master`, so this patch went a bit off-track. Only https://github.com/doctrine/dbal/pull/2986/commits/bbdae66d294167107199394aa943cad3ee3ad831 should be kept.

2018-01-26 10:30 UTC, Ocramius commented
Since this targets DB2, I'd rather prefer using the `PlatformClass::class` as name (consistent with `get_class()` and `instanceof` behavior).

`getName()` should probably be deprecated and removed instead of improved.

2018-01-26 15:53 UTC, simPod commented
@Ocramius and is it still worth doing then if it's for DBAL2?

2018-01-26 16:09 UTC, Ocramius commented
No, because it would be a BC break

On 26 Jan 2018 16:53, "Šimon Podlipský" <notifications@github.com> wrote:

> @Ocramius <https://github.com/ocramius> and is it still worth doing then
> if it's for DBAL2?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/doctrine/dbal/pull/2986#issuecomment-360822956>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAJakCAU2CM5xajLUeQbAiXZZqzN-qZKks5tOfUTgaJpZM4RmkYa>
> .
>

2018-01-26 16:48 UTC, simPod commented
Shall we close then?

On Fri, Jan 26, 2018, 17:09 Marco Pivetta <notifications@github.com> wrote:

> No, because it would be a BC break
>
> On 26 Jan 2018 16:53, "Šimon Podlipský" <notifications@github.com> wrote:
>
> > @Ocramius <https://github.com/ocramius> and is it still worth doing then
> > if it's for DBAL2?
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/doctrine/dbal/pull/2986#issuecomment-360822956>, or
> mute
> > the thread
> > <
> https://github.com/notifications/unsubscribe-auth/AAJakCAU2CM5xajLUeQbAiXZZqzN-qZKks5tOfUTgaJpZM4RmkYa
> >
> > .
> >
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/doctrine/dbal/pull/2986#issuecomment-360827440>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAUAJZFx9YYmHZsELMhTfvOnYkXSqMg0ks5tOfikgaJpZM4RmkYa>
> .
>

2018-01-29 07:13 UTC, Ocramius commented
Yes, let's close here :-)

If you want, you can send a patch against `develop` that completely removes `getName()`

2018-01-29 07:13 UTC, closed without merging