feature doctrine/dbal#3036 ability to return table names unprefixed
doctrine/dbal pull request #3037
Opened 2018-03-06 11:06 UTC by lopezator

feature: ability to return table names unprefixed with getTableNames function

2018-03-06 11:52 UTC, lopezator commented
Does that TravisCI error has anything to do with the code snippet changed?

2018-03-06 16:41 UTC, morozov requested changes

2018-03-06 16:44 UTC, morozov commented
@lopezator I've restarted the Travis job. But personally, I don't see a need for logic like this in the existing API. As long as the list of the table objects is available to the caller, it can represent them however it needs. What prefixes is this about and why would one caller need prefixes but the other wouldn't?

2018-03-07 08:42 UTC, lopezator commented on lib/Doctrine/DBAL/Schema/Schema.php
> +        if ($addPrefix) {
You might be right. It could be splitted if necessary.

2018-03-07 08:46 UTC, lopezator commented on lib/Doctrine/DBAL/Schema/Schema.php
> +            $tableNames = array_values(array_map(function($table) {
It can, but as if related to information that dbal has it makes sense for me to have the option to retrieve that information.

2018-03-07 08:48 UTC, lopezator commented
I see @morozov and understand your point. I did it in my userland already, I just thought It could be interesting to have the option to retrieve the data in both ways and shared it. :)

2018-03-07 22:59 UTC, morozov commented
@lopezator I did a little digging into how tables and schemas work and figured out the following:

1. The schema always has a non-empty name which defaults to "public".
2. The tables which the schema contains may or may not have a namespace.
3. The tables in the schema are indexed by a fully qualified name. If the table doesn't define its namespace explicitly, it's defaulted to the schema name.

See how `Schema::_addTable()` works.

With the above said, the schema returning table names without the namespace will only work if they all have the same namespace which can be omitted (which is the most likely use case). Otherwise, it will lead to a data loss (which is still possible). Therefore, this API cannot be introduced in any form in the schema as it's by design prone to losing data. Therefore, it only belongs to userland.

2018-03-07 22:59 UTC, closed without merging