Always use phpunit bridge 4
doctrine/dbal pull request #3076
Opened 2018-03-31 20:17 UTC by greg0ire

Old versions report annotation assertions as risky.

2018-03-31 21:04 UTC, Majkl578 commented
According to the comment this happens with 4.0.6 too: https://github.com/doctrine/dbal/pull/2846#discussion_r178441001

2018-03-31 21:13 UTC, greg0ire commented
Shit, created on a bar, from my phone, can't amend.

2018-03-31 21:55 UTC, greg0ire commented
@majkl edits from maintainers are allowed, feel free to edit or wait for later

2018-04-04 00:12 UTC, morozov requested changes
@greg0ire please make sure you localize the issue first (ideally, with the steps to reproduce).

2018-04-04 21:55 UTC, greg0ire commented
The issue still shows up in the build output: https://ci.appveyor.com/project/doctrine/dbal/build/job/wj27yvdla6mjfh5p, and 4.0.7 is in use, so I guess there is no fix for it right now.

2018-04-04 21:55 UTC, closed without merging