Removed the logic of using BLOB columns for BINARY type of fields
doctrine/dbal pull request #3179
Opened 2018-06-06 20:34 UTC by morozov

In DBAL 2.x, if a `BINARY` column has length greater than the max size on a given platform, it's represented as a `BLOB`. This idea may be inspired by the type systems of PostgreSQL and SQLite which don't make a difference between `BINARY` columns and `BLOB`s.

On the DBAL level, however, it looks like a bad idea for the following reasons:

1. `BLOB` columns cannot be used in `DISTINCT`, `WHERE, `ORDER BY` and `GROUP BY` clauses on some platforms (e.g. Oracle, IBM DB2) for a reason. A `BLOB` is just a _large_ piece of binary data which is not supposed to be compared. It should be just exported or imported.
2. The max binary length inconsistent between platforms: 2K, 4K, 8K, 32K, 64K. It means that depending on the length of a particular field, you'll get it represented as a `BLOB` on some platforms and as a `BINARY` on others.
3. To make `BLOB` and `BINARY` types look alike, DBAL represents `BINARY` columns in PHP as streams. It's pointless because unlike the `BLOB` type which could be used to store images or other media files, `BINARY` columns are used to store values like UUID or hashes like SHA1 and be used as key columns. You don't want to have your key value as a stream.
4. DBAL doesn't silently convert `(VAR)?CHAR` columns to `TEXT`. The same shouldn't be done for binary columns.

2018-06-14 03:19 UTC, Ocramius requested changes

2018-06-14 03:19 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Platforms/AbstractMySQLPlatformTestCase.php
> -        self::assertSame('MEDIUMBLOB', $this->_platform->getBinaryTypeDeclarationSQL(array('length' => 65536)));
I suggest keeping the assertion and checking that `VARBINARY(65536)` is generated.

2018-06-14 03:19 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Platforms/AbstractMySQLPlatformTestCase.php
> -        self::assertSame('MEDIUMBLOB', $this->_platform->getBinaryTypeDeclarationSQL(array('fixed' => true, 'length' => 65536)));
Same as above: asserted value should change, assertion should be kept

2018-06-14 03:19 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Platforms/OraclePlatformTest.php
> -        self::assertSame('BLOB', $this->_platform->getBinaryTypeDeclarationSQL(array('length' => 2001)));
Same as above: let's keep the assertion with the correct comparison instead

2018-06-14 03:19 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Platforms/AbstractSQLServerPlatformTestCase.php
> -        self::assertSame('VARBINARY(MAX)', $this->_platform->getBinaryTypeDeclarationSQL(array('length' => 8001)));
Same as above: let's keep the assertion with the correct comparison instead

2018-06-14 03:19 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Platforms/AbstractSQLServerPlatformTestCase.php
> -        self::assertSame('VARBINARY(MAX)', $this->_platform->getBinaryTypeDeclarationSQL(array('fixed' => true, 'length' => 8001)));
Same as above: let's keep the assertion with the correct comparison instead

2018-06-14 03:19 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Platforms/DB2PlatformTest.php
> -        self::assertSame('BLOB(1M)', $this->_platform->getBinaryTypeDeclarationSQL(['length' => 32705]));
Same as above: let's keep the assertion with the correct comparison instead

2018-06-14 03:19 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Platforms/DB2PlatformTest.php
> -        self::assertSame('BLOB(1M)', $this->_platform->getBinaryTypeDeclarationSQL(['fixed' => true, 'length' => 32705]));
Same as above: let's keep the assertion with the correct comparison instead

2018-06-14 03:19 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Platforms/OraclePlatformTest.php
> -        self::assertSame('BLOB', $this->_platform->getBinaryTypeDeclarationSQL(array('fixed' => true, 'length' => 2001)));
Same as above: let's keep the assertion with the correct comparison instead

2018-06-14 03:19 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Platforms/SQLAnywherePlatformTest.php
> -        self::assertSame('LONG BINARY', $this->_platform->getBinaryTypeDeclarationSQL(array('length' => 32768)));
Same as above: let's keep the assertion with the correct comparison instead

2018-06-14 03:19 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Platforms/SQLAnywherePlatformTest.php
> -        self::assertSame('LONG BINARY', $this->_platform->getBinaryTypeDeclarationSQL(array('fixed' => true, 'length' => 32768)));
Same as above: let's keep the assertion with the correct comparison instead

2018-06-14 03:19 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Types/BinaryTest.php
> +    private function getBinaryString()
` : string`

2018-06-14 03:19 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Types/BinaryTest.php
> +     * @return string
Omit

2018-06-14 03:19 UTC, Ocramius commented on tests/Doctrine/Tests/DBAL/Types/BinaryTest.php
> +        for ($i = 0; $i < 256; $i++) {
`return implode(array_map('chr', range(1, 256)))`? Or am I pushing it too far? :D

2018-06-14 03:20 UTC, Ocramius commented
Note: I agree with the overall patch idea - the comments are just about details

2018-06-17 18:04 UTC, morozov commented
@Ocramius mind taking another look?

2018-06-18 07:19 UTC, Ocramius approved these changes
LGTM 👍

2018-06-18 07:20 UTC, merged

2018-06-18 07:20 UTC, Ocramius commented
Thanks @morozov!