In Schema Diff, ignore default value alteration for MySQL TEXT and BLOB types
doctrine/dbal pull request #3189
Opened 2018-06-19 10:29 UTC by JarJak

MySQL (all versions) and MariaDB (<10.2.1) does not support default value for TEXT and BLOB types.

|      Q       |   A
|------------- | -----------
| Type         | bug
| BC Break     | no
| Fixed issues | #514 

#### Summary

If you look at #514 Doctrine already ignores those, but if you run schema diff you can still see that default value for these columns is altered.

See: https://github.com/bolt/bolt/pull/7477

I am not sure if this is best place to fix it. Any better proposals are more than welcomed :)

2018-06-19 19:34 UTC, morozov commented
> MySQL (all versions) and MariaDB (<10.2.1) does not support default value for TEXT and BLOB types.

@JarJak, as far as I understand the patch, it disables default value even for for all MySQL-like platforms even if they support the default values. What about the non-MySQL-like platforms ones?

Regardless of what the final decision is, we need to have a functional test which would pass on all supported platforms and therefore explain what the intended behavior is.

2018-06-19 19:36 UTC, morozov requested changes

2018-06-19 19:36 UTC, morozov commented on lib/Doctrine/DBAL/Schema/MySqlSchemaManager.php
> +                // MySQL (all versions) and MariaDB (<10.2.1) does not support default value for TEXT and BLOB types
This comment is a good candidate for a platform feature.

2018-07-05 13:31 UTC, JarJak commented
@morozov this patch does not disable default value because it is already disabled in #514. It only stops Schema Siff from showing this as a change in schema, which is false positive.

2018-07-06 04:52 UTC, morozov commented
> Regardless of what the final decision is, we need to have a functional test which would pass on all supported platforms and therefore explain what the intended behavior is.

Let's start with this.

2021-07-09 01:20 UTC, morozov commented
Closing as stale. The issue should be addressed by https://github.com/doctrine/dbal/pull/4659.

2021-07-09 01:20 UTC, closed without merging