Force Sequence::$initialValue type
doctrine/dbal pull request #3268
Opened 2018-08-23 08:55 UTC by vpArth

|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no
| Fixed issues | #3267

#### Summary
`Schema\Sequence`:  

 - Deduplicated setters code
 - Forced int type for numeric values

2018-08-28 10:10 UTC, vpArth commented
Is there any way to restart failed appveyor build? I believe this fail has nothing about code...

2018-08-28 15:53 UTC, morozov commented
@vpArth yes, I've restarted the build.

2018-08-28 15:55 UTC, morozov requested changes
> It can help to fix some issues with Schema\Comparator::diffSequence false positive diffs.

Please provide a test case with an example of a false positive.

2018-08-29 08:32 UTC, vpArth commented
> Please provide a test case with an example of a false positive.

Done

2018-08-29 16:54 UTC, morozov commented
@vpArth looks good. Please squash the commits.

2018-09-01 16:54 UTC, vpArth commented
It's squashed

2018-09-01 18:53 UTC, morozov approved these changes

2018-09-01 18:54 UTC, merged

2018-09-01 18:54 UTC, morozov commented
Thank you, @vpArth! Merged.