Provide for existing type to be of same output type for ConvertToPHPValue
doctrine/dbal pull request #3291
Opened 2018-09-18 04:28 UTC by TomHAnderson

|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no

#### Summary

The DoctrineObject Hydrator of DoctrineModule should use the Type objects to convert values into and out of arrays.  Currently only a mediocre filter is used for the most basic of DateTime types.  

Some of the existing Types (DateTimeType, DateTime, others) code in `convertToPHPValue` allow types of the same output type to be input data.  This is desired.  This PR fixes the types which do not allow such input.

2018-09-18 04:41 UTC, Ocramius commented
IMO this looks good: some performance overhead is involved, but I don't think it is relevant, and indeed does avoid double conversions.

Still, I don't think this is the correct fix for the underlying issue: types should be well-defined in and out, and these sort of "already PHP type shouldn't be converted again" shouldn't happen multiple times.

I think the patch is fixing a symptom, rather than the root cause of the issue.

2018-09-18 04:51 UTC, TomHAnderson commented
Users are currently using the DoctrineObject hydrator to hydrate values they are creating themselves such as 
```php
$doctrineObject->hydrate([ ['simple_array field', 'element2']], $entity);
```
which, if the hydrator adhered strictly to Types would read
```php
$doctrineObject->hydrate([ 'simple_array_field,element2'], $entity);
```
but this is counterintuitive because users are not thinking in raw database output.  This patch fixes this behavior.

But the bigger issue is custom types.  A custom type _must_ use a Type object because the input and output values could be anything.  In my case I created a `datetime_microsecond` type which was handled like a DateTime value but there was nothing to convert the value from a string to an object when hydrating the entity.  Fixing custom types is the larger correction here.

2018-09-18 04:53 UTC, Ocramius commented
> but this is counterintuitive because users are not thinking in raw database output.

Right, but this is `doctrine/dbal` after all, so it is designed for RDBMS<->PHP conversions, and pushing semantics from a different layer into it increase complexity and implicit considerations by a lot.

2018-09-18 05:11 UTC, TomHAnderson commented
I agree the considerations are increased.  I chose this path for the hydrator because we were already handling the conversion in most cases and I corrected only the few which did not conform to the pattern the other already followed.

Modifying these in `doctrine/dbal` was chosen because when a user creates a custom type it is for this layer but needs handling in the hydrator.  Tracing back to where a custom type acts I landed in dbal Types.

2018-09-18 05:15 UTC, Ocramius commented
Aye, and that is fine to some degree, just unsure if we should really do it here, since we're no longer talking about what comes fro.m the RDBMS, and we're actually being too lax on the user.

Instead, types should probably be stricter and throw more (for example when something is already a `DateTime`, it should just crash).

That's my feedback btw - let's see what other DBAL maintainers think.

2018-09-18 05:37 UTC, TomHAnderson commented
https://github.com/doctrine/DoctrineModule/pull/647

2018-09-18 12:42 UTC, morozov commented
I'm with @Ocramius on this one. I'd better see the code made stricter in 3.0 by not checking if the value is already of the desired type rather than add more complexity to the code and lose this opportunity.

2018-09-23 00:36 UTC, TomHAnderson commented
This is an opportunity with two directions:

* Remove existing code to deliberately break invalid parameters.  This reduces the Type code, which is called often, by one `if` statement with a single return if the output type matches the input type.  
*  * This will happen when users supply their own values for a hydrator such as an array for a simple_array type.
* Expand the code (this PR) to cover input types equal output types.  This supercharges Hydrators by allowing each extracted field to be processed through these Type classes.  
*  * Hydrator changes are at the heart of this change.

2018-09-23 06:02 UTC, morozov commented
> This reduces the `Type` code, which is called often, by one `if` statement with a single return if the output type matches the input type.

It explicitly removes the responsibility of the API for which it wasn't designed.

Instead of being used for conversion of the data retrieved from the DB, the types are used for conversion of data provided by a developer which doesn't look like a valid argument. If we want to let the developer know if the value is already of the expected type, there should be a separate method for that which hydrator would call before conversion if it's a valid case for it.

2018-09-25 00:05 UTC, TomHAnderson commented
I also see a separate class to handle this.  But that new set of classes would mirror the existing Types and would be required __in addition to__ any user custom Type.  

I approached this from creating a new custom type.  There was not a method of the hydrator to properly extract the value from my custom class.  So should I have to write a second custom class which only the hydrator uses to handle extracting from that custom type?  My custom type and many of the existing types already handled the job I needed them to do which is hydration.

So if a fleet of TypeSupport files is needed in order to properly fix the hydrator I would only do that if I cannot convince `dbal` of the elegance of this pr.

2018-09-25 04:49 UTC, morozov commented
> I also see a separate class to handle this.

No, I meant a new method of `Type`, not a new set of classes.

2018-11-23 22:56 UTC, greg0ire requested changes

2018-11-23 22:56 UTC, greg0ire commented on lib/Doctrine/DBAL/Types/Type.php
> +     * Converts a given value from a database reprentation or flexibly from an existing
```suggestion
     * Converts a given value from a database representation or flexibly from an existing
```

2019-01-30 06:40 UTC, greg0ire submitted a review, later dismissed

2019-01-30 06:57 UTC, greg0ire commented
Approving because I'm having a hard time understanding in what cases specifically this will be useful and I don't want to prevent a merge.

2019-02-07 22:16 UTC, SenseException requested changes

2019-02-13 03:53 UTC, TomHAnderson commented on tests/Doctrine/Tests/DBAL/Types/SimpleArrayTest.php
> +    public function testArrayConvertsToDatabaseValue()
I've added return types to all unit tests in the Types subdirectory.

2019-02-14 00:51 UTC, Majkl578 requested changes
Still 👎 from me here for the reasons stated above:
- complicates Type even further, instead of the overall aim to simplify/split it;
- rather than treating Types as single-pass _converters_, this now leverages them as multi-pass _normalizers_, which could/will lead to more duplicated calls.

Also this does not handle cases when input and output is of the same type. Take for example `ReverseStringType`, how do you know whether the value has already been converted or not?

2019-02-14 03:13 UTC, morozov requested changes
The current implementation violates the SRP since every single implementation of `normalizeToPHPValue()` calls `convertToPHPValue()` internally. The diff between the two would constitute the logic I tried to describe in https://github.com/doctrine/dbal/pull/3291#issuecomment-423794130:

> If we want to let the developer know if the value is already of the expected type, there should be a separate method for that which the hydrator would call before conversion if it's a valid case for it.

However, even that doesn't stand the use case @Majkl578 described above. Any non-primitive type would have this issue.

2019-02-14 21:37 UTC, TomHAnderson commented
The description for this PR states:

```
It is a goal of this change to create hydrators which fully support custom types.
```

In order to execute that goal I have designed this PR to where it is today.  But the issues raised don't address the original goal; perhaps too many changes had to be made to properly support custom types.  Do we need to roll back all the changes and begin by removing the type checking from `convertToPHPValue` then walking each part forward so instead of having such a large dartboard to address?  Or is that first step of removing type checking going too far already?

2019-02-25 00:28 UTC, TomHAnderson commented
I've started a thread to talk through all the reasons I created this PR one at a time.
PLEASE become part of this conversation: https://doctrine.slack.com/messages/CA8MNL2UQ/convo/CA8MNL2UQ-1551052461.002200/?

2020-11-17 15:49 UTC, closed without merging