Fix Fetch mode query in MasterSlaveConnection
doctrine/dbal pull request #3305
Opened 2018-10-01 12:18 UTC by BradCrumb

|      Q       |   A
|------------- | -----------
| Type         | bug
| BC Break     | no

#### Summary

The `Doctrine\DBAL\Connections\MasterSlaveConnection` class doesn't set the default fetchmode when using die `query()` method.

The issue came up when we were migrating a normal connection to master/slave. First we got a FETCH_ASSOC and after the config change we had FETCH_BOTH.

2018-10-01 12:31 UTC, Ocramius requested changes
Requires test case

2018-10-02 13:56 UTC, BradCrumb commented
@Ocramius Just checked the current existing test in `/test/Doctrine/Tests/DBAL/Functional/MasterSlaveConnectionTest.php`. But a lot of methods of the MasterSlaveConnection class (also the query method where i added the setFetchMode) are uncovered in the test class, so I think it is better to create a new issue for completing the coverage of this connection class.

2018-10-02 14:01 UTC, BradCrumb commented
@Ocramius Fine I add the test for the query method in the MasterSlaveConnectionTest because I changed the code in that method. I will add an issue for all other methods.

2018-10-06 19:46 UTC, morozov reviewed
@BradCrumb could you clarify how the tests are related to the code being changed? The issue and the fix are about the fetch mode, but nothing is fetched in the test.

2018-10-06 19:46 UTC, morozov commented on tests/Doctrine/Tests/DBAL/Functional/MasterSlaveConnectionTest.php
> +        self::assertTrue($statement instanceof Statement);
This assertion seems redundant. The `query()` method always returns a statement.

2018-10-06 19:46 UTC, morozov commented on tests/Doctrine/Tests/DBAL/Functional/MasterSlaveConnectionTest.php
> +        self::assertTrue($statement instanceof Statement);
This assertion seems redundant. The `query()` method always returns a statement.

2018-12-05 12:16 UTC, Ocramius submitted a review, later dismissed
@BradCrumb this looks good, just needs a squash before being considered for merge :+1:

2018-12-07 02:13 UTC, morozov approved these changes

2018-12-07 02:13 UTC, merged

2018-12-07 02:13 UTC, morozov commented
Thank you, @BradCrumb.