[SQL Anywhere] Fix query limit values "0" and "null"
doctrine/dbal pull request #3378
Opened 2018-12-04 09:09 UTC by deeky666

|      Q       |   A
|------------- | -----------
| Type         | bug
| BC Break     | no
| Fixed issues | n/a

#### Summary

Integration tests on SQL Anywhere revealed that the platform doesn't handle `$limit = null` when rewriting `SELECT` statements for LIMIT/OFFSET.
Also handling of `$limit = 0` was wrong as it was selecting ALL results instead of NONE.

Reference: http://dcx.sybase.com/1200/en/dbreference/select-statement.html

2018-12-04 15:30 UTC, Ocramius requested changes

2018-12-04 15:30 UTC, Ocramius commented on lib/Doctrine/DBAL/Platforms/SQLAnywherePlatform.php
> +                $limitOffsetClause .= 'START AT ' . ($offset + 1) . ' ';
Can you move the code that generates `$limitOffsetClause` to a `private` method? All of these if/else become early returns that way.

2018-12-04 17:54 UTC, deeky666 commented
@Ocramius done

2018-12-04 18:34 UTC, Ocramius requested changes

2018-12-04 18:34 UTC, Ocramius commented on lib/Doctrine/DBAL/Platforms/SQLAnywherePlatform.php
> +    private function getTopClauseSQL($limit, $offset) : string
These can be `?int` now

2018-12-05 05:01 UTC, deeky666 commented on lib/Doctrine/DBAL/Platforms/SQLAnywherePlatform.php
> +    private function getTopClauseSQL($limit, $offset) : string
@Ocramius fixed

2018-12-05 12:04 UTC, Ocramius approved these changes
LGTM :+1: 

@morozov assigning to you to do the backporting dance, if you have time

2018-12-05 18:07 UTC, merged