Issue #950: Fixed cardinality issue where subquery could return more than one row
doctrine/dbal pull request #3421
Opened 2019-01-02 15:56 UTC by jwilson-cee

Fixed cardinality issue where subquery could return more than than one row in getListTableForeignKeysSQL function

|      Q       |   A
|------------- | -----------
| Type         | bug
| BC Break     | no
| Fixed issues | #950 

#### Summary

Replaced "=" with "IN" in the query in the PostgreSqlPlatform->getListTableForeignKeysSQL() function to avoid getting a cardinality violation error thrown

2019-01-02 16:00 UTC, Ocramius requested changes
2.5 is closed for modifications, sorry

2019-01-02 16:00 UTC, closed without merging

2019-01-02 16:02 UTC, jwilson-cee commented
@Ocramius Okay, what branch should I commit this to then?

2019-01-02 16:16 UTC, Ocramius commented
Please target master

On Wed, 2 Jan 2019, 17:02 jwilson-cee <notifications@github.com wrote:

> @Ocramius <https://github.com/Ocramius> Okay, what branch should I commit
> this to then?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/doctrine/dbal/pull/3421#issuecomment-450903265>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAJakNuvxPLgNEx7yQ-CPt99zgSXZ7bwks5u_NgugaJpZM4Zm2Nd>
> .
>

2019-10-27 15:37 UTC, remoteclient commented
As the underlying issue still exists and PostgreSqlPlatform.php has to be altered manually after each composer update.... When will this be fixed?