[WIP] Index are recreated during a diff even when not changed
doctrine/dbal pull request #3458
Opened 2019-02-14 14:55 UTC by yvoyer

|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no
| Fixed issues | #2866

#### Summary

This PR adds the steps to reproduce for #2866

When generating a diff (using DoctrineMigration package) for a table containing an index, the index is always dropped and then recreated.

I wrote a test in the `Comparator` to see if it could be the source, but he seems to work properly. So I just added a test on the `MysqlPlatform` (the place where I got the error). 

I will try to work on a patch when I get the time, unless someone fixes it before.

**TODO**

- [X] Step to reproduce 
- [ ] Provide a fix

2019-02-18 21:33 UTC, SenseException requested changes
`testPreserveIndexOnAlterTable()` fails on my dbal 2.9.1 installation showing that index_name is dropped and added afterwards like described. `testPreserveIndexesWhenNoChange()` passes.

2019-02-18 21:33 UTC, SenseException commented on tests/Doctrine/Tests/DBAL/Platforms/MySqlPlatformTest.php
> +        $this->assertEquals([], $this->createPlatform()->getAlterTableSQL($diff));
Can you please use `self::assertSame()` here?

2019-02-18 21:33 UTC, SenseException commented on tests/Doctrine/Tests/DBAL/Schema/ComparatorTest.php
> +        self::assertEquals($expected, Comparator::compareSchemas($schema1, $schema2));
Can you please use `self::assertSame()` here?

2019-12-03 12:14 UTC, PowerKiKi commented
Still seeing this in v2.10.0

2019-12-26 16:40 UTC, PowerKiKi commented
I finally dug deeper in this issue. Across five of my projects it was always not because a bug in dbal, but because I did not specify a length on a varchar index. That meant that MariaDB created an index with a default length ([which may vary](https://mariadb.com/kb/en/innodb-system-variables/#innodb_large_prefix)). Then DBAL correctly got confused because he saw a length in DB, but it was not specified in my code.

Specifying the length, like below, fixes the problem:

```diff
 /**
  * @ORM\Table(indexes={
- *     @ORM\Index(name="message", columns={"message"})
+ *     @ORM\Index(name="message", columns={"message"}, options={"lengths" = {191}})
  * })
  * @ORM\Entity(repositoryClass="Application\Repository\LogRepository")
  */
```

I think this issue should be closed.

2019-12-26 17:12 UTC, PowerKiKi requested changes
I think this PR should be rejected as the introduced tests are not valid.

It is likely that the original behavior observed that lead to this PR is actually a misuse of DBAL. Possible solutions for the end-users are:

- [Adding parentheses](https://github.com/doctrine/dbal/issues/3780#issuecomment-290080207)
- [Using lowercase keywords](https://github.com/doctrine/dbal/issues/3780#issuecomment-381138100)
- [Specifying lengths](https://github.com/doctrine/dbal/pull/3458#issuecomment-569087641)
- [Quoting lengths](https://github.com/doctrine/dbal/issues/3780#issuecomment-565859839)

2019-12-29 15:04 UTC, yvoyer commented
@PowerKiKi, indeed it could be closed. but I would have liked to reproduce in a better way. I could rework it to assert that the varchar index has a length, so that this misuse never happens. Would it be better to move the test to doctrine/orm, with a mapping test? and maybe make a pr here to assert that a varchar index has a length?

2019-12-30 18:12 UTC, PowerKiKi commented
Requiring a length for varchar index sounds like a breaking to me. I'm not quite sure if it's the best way to fix this. We might need the insight of someone more involved in Doctrine to decide on that.

2021-10-26 19:28 UTC, closed without merging