Make classes final where applicable.
doctrine/dbal pull request #3590
Opened 2019-06-04 17:22 UTC by jwage

|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | yes
| Fixed issues | fixes #3585

#### Summary

2019-06-04 18:06 UTC, morozov commented on lib/Doctrine/DBAL/Driver/Mysqli/MysqliStatement.php
> +        $this->bindedValues = array_fill(1, $paramCount, null);
Can we make it "bound" now? This should be the proper form AFAIK.

2019-06-04 19:49 UTC, morozov commented on tests/Doctrine/Tests/DBAL/Driver/StatementIteratorTest.php
> -    public static function statementProvider() : iterable
It is fine to remove these tests. They enforce the lazy behavior in all statement classes however it's achieved by just using the statement iterator. As long as the statement iterator is instantiated internally by the implementations, you cannot really enforce it by a test w/o complicating the API. I believe not having these tests is a reasonable tradeoff.

2019-06-04 20:49 UTC, SenseException requested changes

2019-06-04 20:49 UTC, SenseException commented on lib/Doctrine/DBAL/Driver/PDOSqlite/Driver.php
>  class Driver extends AbstractSQLiteDriver
```suggestion
final class Driver extends AbstractSQLiteDriver
```

2019-06-04 22:45 UTC, morozov commented
FWIW, the current state is:
```
$ finalizer finalizer:check-final-classes lib
Following classes need to be made final:
+--------------------------------------+
| Doctrine\DBAL\Driver\Mysqli\Driver   |
| Doctrine\DBAL\Driver\PDOPgSql\Driver |
+--------------------------------------+
```

2019-06-04 23:02 UTC, jwage commented
@morozov fixed. Should we add that `finalizer` check to ci so it fails if a new class is introduced that should be final but isn't?

2019-06-04 23:50 UTC, morozov commented
This is the first time I'm using it but it looks more suitable for development, not for CI. Specifically, it also [fails the build](https://github.com/Ocramius/Finalizer/blob/8f7bf97c3d6adb25af1f07d94f01c6c6a0a1ba84/src/Finalizer/Console/CheckFinalClassesCommand.php#L105) if it finds the classes mistakenly marked as final which is not what we need. I don't think we're introducing new classes that often that we need it enforced on CI.

2019-06-05 02:00 UTC, jwage commented
I've got a few more tests to fix tomorrow.

2019-06-07 23:17 UTC, SenseException submitted a review, later dismissed

2019-06-07 23:17 UTC, SenseException commented on lib/Doctrine/DBAL/Driver/PDOSqlite/Driver.php
>  class Driver extends AbstractSQLiteDriver
This file is listed in `UPGRADE.md` as being final.

2020-01-03 06:02 UTC, morozov commented
In addition to already finalized classes, the following driver-level classes are meant to be final but currently cannot be declared as such:

The following class have not been automatically finalized:

1. `MysqliConnection` because of its `getWrappedResourceHandle()` which is not used anywhere and is not part of any API convention (see #3534 for a similar feature request).
2. `OCI8Connection` because of its `getExecuteMode()` which is used by `OCI8Statement::execute()`.
3. `OCI8Statement` because of its _static_ `convertPositionalToNamedPlaceholders()` which is `public` only because it's tested directly which indicates violation of the SRP. It could be extracted to a utility class.
4. `PDOConnection` because it has child classes and the `createStatement()` method.
5. `PDOSqlsrv\Connection` because of its `createStatement()`.

2020-01-12 01:18 UTC, morozov approved these changes

2020-01-12 01:19 UTC, merged

2020-01-12 01:46 UTC, morozov commented
Thank you @jwage :+1: