Add MySQL bit type support
doctrine/dbal pull request #3701
Opened 2019-10-16 04:43 UTC by WonlyCms

|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | yes
| Fixed issues | add MySQL bit type support.

#### Summary

This is a [#3693](https://github.com/doctrine/dbal/pull/3693) resubmit because I realized that I submitted the wrong branch before.

The following error occurred when I was generating phpdocs.
```
Exception: Unknown database type bit requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it.
Could not analyze class App\Models\UserModel.
```
By checking the source code, I found out that it was a type mapping problem, so I added this line of code.

2019-10-16 05:46 UTC, greg0ire commented
> This is a #3693 resubmit because I realized that I submitted the wrong branch before.

There was no need to create a new PR though, you can always retarget existing PRs ;)

2019-10-16 05:47 UTC, greg0ire commented
Please associate your email address with your Github account, or change the email in your commits to an address already associated with it.

2019-10-16 05:48 UTC, greg0ire approved these changes

2019-10-16 05:51 UTC, WonlyCms commented
> Please associate your email address with your Github account, or change the email in your commits to an address already associated with it.

ok,

2019-10-17 21:22 UTC, SenseException approved these changes

2019-10-17 22:11 UTC, morozov requested changes
The missing mapping is not covered by any existing test. Otherwise, it would have failed. Please add the missing test.

2020-07-13 09:54 UTC, closed without merging