Dropped handling of one-based numeric arrays of parameters in Statement::execute()
doctrine/dbal pull request #3809
Opened 2020-01-03 09:17 UTC by morozov

|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | yes

The logic of handling one-based arrays existed in `OCI8Statement` (57a97eba01156c8ad02debae28620e72217b46bc) and `SQLSrvStatement` (#110) since their initial implementation without any explanation of why it was needed. Apart from that, the APIs with semantics implicitly defined by input are often more error-prone.

This behavior is not portable. Consider the following test:
```php
/**
 * @dataProvider paramsProvider
 */
public function testHasZeroKey(array $params) : void
{
    $sql  = $this->connection->getDatabasePlatform()->getDummySelectSQL('?, ?');
    $stmt = $this->connection->prepare($sql);
    $stmt->execute($params);

    self::assertEquals([1, 2], $stmt->fetch(FetchMode::NUMERIC));
}

public static function paramsProvider() : iterable
{
    return [
        'zero-based' => [
            [0 => 1, 1 => 2],
        ],
        'one-based' => [
            [1 => 1, 2 => 2],
        ],
        'arbitrary-keys' =>
        [
            [28 => 1, 71 => 2],
        ],
    ];
}
```
Currently, it produces the following results:
```
RUNNING TESTS WITH CONFIG ibm-db2.phpunit.xml
PHPUnit 8.4.1 by Sebastian Bergmann and contributors.

EEE (for some reason, the test doesn't work here)                   3 / 3 (100%)

RUNNING TESTS WITH CONFIG mysqli.phpunit.xml
PHPUnit 8.4.1 by Sebastian Bergmann and contributors.

...                                                                 3 / 3 (100%)

RUNNING TESTS WITH CONFIG oci8.phpunit.xml
PHPUnit 8.4.1 by Sebastian Bergmann and contributors.

..E                                                                 3 / 3 (100%)

RUNNING TESTS WITH CONFIG pdo-mysql.phpunit.xml
PHPUnit 8.4.1 by Sebastian Bergmann and contributors.

.EE                                                                 3 / 3 (100%)

RUNNING TESTS WITH CONFIG pdo-oci.phpunit.xml
PHPUnit 8.4.1 by Sebastian Bergmann and contributors.

.EE                                                                 3 / 3 (100%)

RUNNING TESTS WITH CONFIG pdo-pgsql.phpunit.xml
PHPUnit 8.4.1 by Sebastian Bergmann and contributors.

.EE                                                                 3 / 3 (100%)

RUNNING TESTS WITH CONFIG pdo-sqlite.phpunit.xml
PHPUnit 8.4.1 by Sebastian Bergmann and contributors.

.EE                                                                 3 / 3 (100%)

RUNNING TESTS WITH CONFIG pdo-sqlsrv.phpunit.xml
PHPUnit 8.4.1 by Sebastian Bergmann and contributors.

.EE                                                                 3 / 3 (100%)

RUNNING TESTS WITH CONFIG sqlsrv.phpunit.xml
PHPUnit 8.4.1 by Sebastian Bergmann and contributors.

..E                                                                 3 / 3 (100%)
```

As you can see, the 2nd test passes only on `sqlsrv`, `oci8` (where the logic being removed is explicitly implemented) and `mysqli` (which doesn't care about the keys at all because it binds parameters using a `foreach` loop).

Additionally, the test that covers the logic implemented in `OCI8Statement` currently fails on PHP 8 (#3802) and, if kept, would have to be reworked for #3808.

In the past, the test was the source of extra maintenance for no real reason: #3642, #3369, #2854, #3507, #3552.

2020-01-04 10:42 UTC, beberlei commented
@morozov I believe the reason this exists is `->bindParam(1, ...)->bindParam(2, ...)` in QueryBuilder.

2020-01-04 12:28 UTC, morozov commented
@beberlei yes, this logic might have been introduced in some drivers because it was needed at the time of introduction but it's not currently needed. `Statement::bindParam()` and `Statement::execute($params)` are different API from the DBAL perspective and the perspective of the most of the drivers (some may implement one via the other but it's an implementation detail). The functional tests like `DataAccessTest::testPrepareWithExecuteParams()` and `::testPrepareWith*()` that still pass prove that.

Additionally, as the test results above show, this behavior is not portable and cannot be relied upon. It works as the test expects only in the drivers that artificially implement this behavior and `mysqli` (where the keys are simply ignored).

2020-01-08 19:22 UTC, beberlei commented
I have to honestly say that I am not to deep to give a good assessment, but the fact that this is not portable across different connections is reason enough to get rid of it. My problem is that this is extremely "hidden" for users in a way that it could lead to sutble breaks if someone would rely on it.

2020-01-08 19:38 UTC, morozov commented
> My problem is that this is extremely "hidden" for users in a way that it could lead to subtle breaks if someone would rely on it.

This is another reason to get rid of this hidden gem in a major release.

2020-01-08 20:00 UTC, beberlei submitted a review, later dismissed

2020-01-08 20:30 UTC, morozov commented
@beberlei could you reapprove please? I had to resolve a conflict with a just merged PR.

2020-01-10 09:16 UTC, SenseException requested changes
These changes also seem to be in sync with the QueryBuilder documentation, where 0 is used for the first parameter. It doesn't though with the Data Retrieval chapter. To prevent the communication of mixed usages, I suggest to adapt the parameter indexes to start with 0: https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/data-retrieval-and-manipulation.html#dynamic-parameters-and-prepared-statements

> OCI8/Oracle only supports named parameters, but Doctrine implements a client side parser to allow positional parameters also.

Could this be somehow related to the zero-index decision?

2020-01-10 15:49 UTC, morozov commented
> To prevent the communication of mixed usages, I suggest to adapt the parameter indexes to start with 0

@SenseException, which exactly method do you mean? As pointed out int https://github.com/doctrine/dbal/pull/3809#issuecomment-570781608, 

> `Statement::bindParam()` and `Statement::execute($params)` are different APIs

The former will accept 1-based keys (this did and does work for all DBAL drivers and is true for all underlying drivers that support binding a single parameter natively ([PDO](https://www.php.net/manual/en/pdostatement.bindparam#refsect1-pdostatement.bindparam-parameters), [`ibm_db2`](https://www.php.net/manual/en/function.db2-bind-param.php))), the latter will accept the 0-based ones.

The chapter you're referring to doesn't even mention passing parameters to `Statement::execute()`.

2020-01-11 18:37 UTC, morozov commented
@SenseException if you request changes on a PR, please make sure you can participate in the discussion. This PR is a dependency for #3808 and #3802, so by not replying, you're blocking progress on three issues, not just one.

2020-01-13 00:06 UTC, merged