Use the provided index name for primary keys
doctrine/dbal pull request #3890
Opened 2020-03-06 12:45 UTC by aimeos

|      Q       |   A
|------------- | -----------
| Type         | bug
| BC Break     | no

#### Summary

If an index name is passed in setPrimaryKey(), it's not used by the SQL Server platform class and one generated by the database instead. This makes it impossible to specify the required key name when creating a full text column.

2020-03-06 15:35 UTC, SenseException submitted a review, later dismissed
Thank you. Resulting SQL looks good for SQL Server versions. master branch seems to be the appropriate one.

2020-04-14 01:27 UTC, morozov requested changes
This will need a functional test. The existing tests do not describe the problem being solved.

2021-07-30 00:11 UTC, morozov commented
Please consider the following integration test:
```php
public function testPrimaryKeyName(): void
{
    $table = new Table('test_pk_name');
    $table->addColumn('id', 'integer', ['notnull' => true]);
    $table->setPrimaryKey(['id'], 'pk');

    $this->schemaManager->dropAndCreateTable($table);

    $tableIndexes = $this->schemaManager->listTableIndexes('test_pk_name');

    self::assertArrayHasKey('primary', $tableIndexes);
    self::assertEqualsIgnoringCase('pk', $tableIndexes['primary']->getName());
}
```
It doesn't pass with the changes in this PR on any platform including SQL Server. It looks like implementing this requires significant refactoring of schema management.

2021-11-06 23:27 UTC, morozov commented
Closing due to the lack of progress.

2021-11-06 23:27 UTC, closed without merging