Allow php 8
doctrine/dbal pull request #4028
Opened 2020-05-25 20:00 UTC by greg0ire

Targeting 3.0.x on that particular one, because there will never be support for php 8 on 2.x (right?)

2020-05-25 20:21 UTC, SenseException requested changes

2020-05-25 20:21 UTC, SenseException commented on composer.json.orig
> +<<<<<<< HEAD
Whoops.

2020-05-25 20:21 UTC, greg0ire commented on composer.json.orig
> +<<<<<<< HEAD
whoops indeed :sweat_smile:

2020-05-26 14:46 UTC, morozov commented
> Targeting 3.0.x on that particular one, because there will never be support for php 8 on 2.x (right?)

Right. Support for PHP 8 requires a breaking change.

2020-05-26 14:49 UTC, morozov commented on .travis.yml
> +        php: nightly
Given that we already build against `nightly`, why is this specific job needed?

2020-05-26 14:50 UTC, morozov commented on .travis.yml
> +    - php: nightly
This is already configured:

https://github.com/doctrine/dbal/blob/54a6f7b3585e0cda5d5613200ea6bc6fadf04e95/.travis.yml#L230-L232

2020-05-26 17:36 UTC, greg0ire commented
Sorry, I didn't notice that `nightly` was already handled here… nothing to change besides the version constraint.

2020-05-26 19:00 UTC, SenseException approved these changes
Some green nightly builds :man_dancing:

2020-05-26 19:06 UTC, morozov approved these changes

2020-05-26 19:07 UTC, morozov commented
Should we then remove `--ignore-platform-reqs`?

2020-05-26 20:20 UTC, greg0ire commented
> Should we then remove --ignore-platform-reqs?

We can try replacing that with `composer config platform.php 7.4.99`, because we still need to fool our own dependencies into thinking this is 8.

2020-05-26 20:25 UTC, morozov commented
> because we still need to fool our own dependencies into thinking this is 8

I don't get this. Isn't PHP nightly the PHP 8?

2020-05-26 20:28 UTC, greg0ire commented
Sorry, I meant: into thinking this is 7. Some might not be 8-compatible yet.

2020-05-26 20:28 UTC, morozov commented
Okay, not it makes sense.

2020-05-26 20:30 UTC, greg0ire commented
So do we stay with `--ignore-platform-reqs`, or do we use the above trick?

2020-05-26 20:44 UTC, morozov commented
`--ignore-platform-reqs` seems to be the proper way.

2020-05-26 20:50 UTC, merged