Added specific handling of string type query parameters
doctrine/dbal pull request #4036
Opened 2020-05-28 13:49 UTC by dvaeversted

|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no

#### Summary

This change introduces specific handling of strings, which will assist the SQL server query optimizer in choosing the best possible execution plan.

The current behaviour causes all string parameters to be sent to the SQL server as NVARCHAR(4000).
This causes an unfortunate situation for the query optimizer, that will create a sub-optimal execution plan from the assumption that the parameters are big data strings.

In production we saw multiple instances of a factor 10 or more changes in query time, with the proposed change.

2020-05-28 20:40 UTC, SenseException requested changes
Please create a test that is covering your code and use case. This also breaks existing tests which might be because of BC breaks.

2020-05-29 06:00 UTC, dvaeversted commented
I have corrected the patch, to fix the failure seen in the unit tests.
Apparently we never have a query where we send in a NULL as a string parameter in our environment, hence i missed that case.

Regarding a specific test for the introduced change, i am unsure how to actually write a specific test for it since the previous way it was done will yield the same result seen from the client.
It is affecting the query optimizer in the SQL server to make a better execution plan, i also believe that the function itself is sufficiently covered by the existing unit tests as illustrated by the previous failing unit tests.

2020-06-02 21:43 UTC, SenseException commented
I want to achieve that removing your new introduced code will also have tests failing. The other cases, like e.g. large objects, were covered in functional tests. I wonder if this one can be handled with an unit test since this change doesn't influence the result. I'll have to look deeper into this for an idea how we can test this.

2020-06-12 20:53 UTC, greg0ire commented
Don't mind me, just testing CodeCov's reports.

2021-04-21 16:26 UTC, closed without merging