Remove unmaintained branches from the project metadata
doctrine/dbal pull request #4453
Opened 2020-11-28 17:56 UTC by morozov

|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no

#### Summary

As of https://github.com/doctrine/doctrine-website/pull/372, the branch name is no longer necessary to locate a version. Therefore, the branch names of the unmaintained releases can be removed. Additionally, the slugs that exactly correspond to the release name can be omitted ([ref](https://github.com/doctrine/doctrine-website/blob/6076042066ba16db8fdc10271010693f656e2104/lib/Model/ProjectVersion.php#L61)).

2020-11-28 18:14 UTC, greg0ire commented
:thinking: why does your PR target `master`? doctrine-website uses the default branch now (it was changed a few months ago, or was it weeks?)

2020-11-28 18:17 UTC, morozov commented
> why does your PR target `master`?

It's a mistake. The shell command I use to create pull requests defaults to `master`. The change was originally made based on `2.12.x`.

2020-11-28 18:34 UTC, greg0ire approved these changes, later dismissed

2020-11-28 18:35 UTC, greg0ire commented
Some jobs seem to have be wrongly marked as required in the settings :thinking: Or this have to do with the target branch change?

2020-11-28 18:41 UTC, morozov commented
IIRC, those jobs got stuck before I changed the branch. Let me see if closing and reopening helps.

2020-11-29 00:52 UTC, SenseException requested changes
Please keep the `slug` for now. It's still use.

2020-11-29 01:31 UTC, morozov commented
> Please keep the `slug` for now. It's still use.

I reverted the removal. Is there an existing issue to make them non-mandatory and by default use the release name? From the referenced code, it already seems to be the case.

2020-11-29 01:38 UTC, SenseException approved these changes
>  Is there an existing issue to make them non-mandatory and by default use the release name?

I haven't checked if there are differences for their usage or format yet. The `.doctrine-project.json` files I saw seem to use the same value for name and slug.

2020-11-29 01:41 UTC, merged

2020-11-29 01:42 UTC, morozov commented
@SenseException please rebase the website when you have time and confirm that the updated configuration works. I'll delete the old branches after that.

2020-11-29 12:54 UTC, SenseException commented
@morozov The build went through without problems on the server. I manually started a new deployment for this test. If you like to make an in-between step for another test, you can delete one of the older branches and we can test the deployment again to play it safe.

2020-11-29 18:13 UTC, morozov commented
@SenseException good idea. I deleted the `2.5` branch:
```
$ git log -1 upstream/2.5
commit de23082f09b907ecc1593dd35fbdc49a392c50eb (upstream/2.5)
Merge: 9315e61c4 d2b5db388
Author: Marco Pivetta <ocramius@gmail.com>
Date:   Mon Apr 2 12:40:57 2018 +0200

    Merge pull request #3073 from IMSoP/issue-2683-2.5.x

    2.5.x branch should not contain the PHP 5.5-only ::class syntax
 
$ git push upstream :2.5
To github.com:doctrine/dbal.git
 - [deleted]             2.5
```

2020-11-29 19:24 UTC, SenseException commented
Done :+1:

2020-11-29 19:42 UTC, morozov commented
The `2.5` release is still on the website which is good. I believe we can continue with deleting other unmaintaned branches.

Not sure if the older releases were displayed earlier but they are now (e.g. `2.0.9`), although they are not listed in `.doctrine-project.json`.

2020-11-29 19:46 UTC, SenseException commented
Okay, you can proceed.