Drop support for PHP 7.3
doctrine/dbal pull request #4741
Opened 2021-07-31 23:19 UTC by morozov

|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no

Fixes #4434

2021-08-01 18:19 UTC, derrabus submitted a review, later dismissed

2021-08-01 20:06 UTC, SenseException requested changes, later dismissed

2021-08-01 20:06 UTC, SenseException commented on src/Connection.php
> +    protected ?\Doctrine\DBAL\Driver\Connection $_conn = null;
`use Doctrine\DBAL\Driver\Connection`

2021-08-01 20:06 UTC, SenseException commented on tests/Tools/Console/RunSqlCommandTest.php
> +    private RunSqlCommand $command;
```suggestion

    private RunSqlCommand $command;
```

2021-08-01 20:39 UTC, derrabus commented on src/Connection.php
> +    protected ?\Doctrine\DBAL\Driver\Connection $_conn = null;
… `as DriverConnection` (this file already declares a class of that name.)

2021-08-02 07:22 UTC, greg0ire approved these changes
Looks OK to me. I'm not to sure about doing such things now on this branch though: it causes a big divergence between branches, so merges up might become more difficult. By the time 4.0 is released, I think 7.3 will have been dropped from 3.x too, won't it?

2021-08-02 08:18 UTC, derrabus commented
@greg0ire We're applying pretty much the same changes to Symfony's 6.0 branch right now. Yes, they do cause merge conflicts, but they're easy to fix in most cases.

2021-08-02 16:21 UTC, morozov commented
> I'm not to sure about doing such things now on this branch though: it causes a big divergence between branches, so merges up might become more difficult.

Most of the changes in this PR are automated. So if there are new conflicts caused by the property types, they should be possible to resolve in favor of 3.x and then fixed by `phpcbf`. Doesn't look like a big deal to me.

> By the time 4.0 is released, I think 7.3 will have been dropped from 3.x too, won't it?

I don't see much point in doing it. Specifically, I don't see a point in introducing property types in `3.x`: compared to `4.0.x`, most of the methods don't have scalar argument/return types enforced, enforcing them at the property level will lead to a nightmare.

2021-08-02 16:23 UTC, greg0ire commented
Thanks to you both! What's wrong with the build?

2021-08-02 16:23 UTC, morozov commented
> What's wrong with the build?

I'll disable the PHP 7.3 jobs right before the merge.

2021-08-02 16:28 UTC, merged