Enable default values for Text/Blot type in MariaDB 10.2 platform
doctrine/dbal pull request #4917
Opened 2021-10-22 09:16 UTC by gregor-tb

|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no
| Fixed issues | #4747

#### Summary

MariaDB allows default values on Text and Blob fields starting with 10.2.1, see https://mariadb.com/kb/en/text/

2021-10-22 17:15 UTC, morozov reviewed
Thanks for the patch, @gregor-tb. The code looks good for the most part but it will require a functional test that runs on all supported platforms.

Also, please retarget against `3.2.x` since this is not a bugfix.

2021-10-22 17:15 UTC, morozov commented on src/Platforms/MySQLPlatform.php
> +    protected function supportsDefaultValue(array $column): bool
Instead of accepting `array $column`, it should accept just the type. E.g.:
```php
protected function supportsDefaultValueForType(Type $type): bool
```

2022-03-15 13:37 UTC, rabauss requested changes
Apply the suggested changes from @morozov to accept only `$type`

2022-03-15 13:37 UTC, rabauss commented on src/Platforms/MariaDb1027Platform.php
> +    protected function supportsDefaultValue(array $column): bool
```suggestion
    protected function supportsDefaultValue(Type $type): bool
```

2022-03-15 13:37 UTC, rabauss commented on src/Platforms/MySQLPlatform.php
> +    protected function supportsDefaultValue(array $column): bool
```suggestion
    protected function supportsDefaultValue(Type $type): bool
```

2022-03-15 13:37 UTC, rabauss commented on src/Platforms/MySQLPlatform.php
> +        return ($column['type'] instanceof TextType || $column['type'] instanceof BlobType) === false;
```suggestion
        return ($type instanceof TextType || $type instanceof BlobType) === false;
```

2022-03-15 13:37 UTC, rabauss commented on src/Platforms/MySQLPlatform.php
> +                ! $this->supportsDefaultValue($columnArray)
```suggestion
                ! $this->supportsDefaultValue($columnArray['type'])
```

2022-03-15 13:37 UTC, rabauss commented on src/Platforms/MySQLPlatform.php
> +        if (! $this->supportsDefaultValue($column)) {
```suggestion
        if (! $this->supportsDefaultValue($column['type'])) {
```

2022-03-15 13:43 UTC, ausi commented
This is also supported in MySQL since version 8.0.13: <https://dev.mysql.com/doc/refman/8.0/en/data-type-defaults.html#data-type-defaults-explicit>

But MySQL requires it to be written as an expression by wrapping the value into parentheses: `TEXT DEFAULT ('foo')`

2022-03-23 18:56 UTC, closed without merging