Fix MSSQL CLOB column type to support Unicode
doctrine/dbal pull request #4987
Opened 2021-11-14 13:02 UTC by mvorisek

|      Q       |   A
|------------- | -----------
| Type         | bug
| BC Break     | no
| Fixed issues | no

#### Summary

`VARCHAR` MSSQL type does not support Unicode, fix CLOB mapping to `NVARCHAR`. This is also consistent with standard string mapping which uses `NVARCHAR` already.

2021-11-21 16:24 UTC, morozov commented
It doesn't look like a bug so far. If it is, please provide the steps to reproduce and cover the change with an integration test. The mapping cannot be changed in a patch release, especially in `2.x`. Additionally, upgrade testing should be done to understand the impact on backward compatibility.

2021-11-21 16:37 UTC, mvorisek commented
> It doesn't look like a bug so far.

why not? `text` (CLOB) type represent a case insensitive type. It is true for all DB platforms except MSSQL and this PR fixes this inconsistency.

steps to replicate:

1. create table with a `text` column
2. insert 2 rows with `mixedcase` and `mixedCase` values
3. select with where = `MIXEDcase`
4. both rows must be selected

2021-11-21 16:46 UTC, morozov commented
How are these steps related to Unicode?

2021-11-21 17:14 UTC, mvorisek commented
> How are these steps related to Unicode?

updated steps, previously, I posted steps for a different issue

2021-11-21 20:35 UTC, morozov commented
> `text` (CLOB) type represent a long `string` type, eg. non-case sensitive type with full Unicode / UTF-8 support

Where does it come from?

2021-11-21 21:12 UTC, mvorisek commented
where is the definition of `string`, `text` vs. `blob` type mapping to DB

2021-11-22 19:33 UTC, morozov requested changes
Please identify the upgrade impact and retarget towards `3.2.x`.

2021-11-22 19:33 UTC, morozov commented on lib/Doctrine/DBAL/Platforms/SQLServerPlatform.php
> +            return true;
Only TEXT maps to `VARCHAR(MAX)`. Is it possible to identify this during the schema introspection? See https://github.com/doctrine/dbal/blob/5b456d8b77c3ea3fcb4b27b40d2cc60ea043cafd/src/Schema/SQLServerSchemaManager.php#L80-L86

2022-03-30 08:03 UTC, mvorisek commented
non-stale

2022-04-03 07:07 UTC, closed without merging

2022-04-03 09:00 UTC, mvorisek commented
`text` DBAL type does support UTF-8 with every common DB vendor excl. MSSQL and I belive MSSQL should support it too. That is what whis PR does.

About the upgrade path request, yes, the request is legit, but I have no time and experience to impl. it easily, thus I would like to keep this PR open for others to help with that. Thank you.