Add MariaDb1070Platform with native GUID support
doctrine/dbal pull request #4998
Opened 2021-11-17 00:38 UTC by Rixafy

|      Q       |   A
|------------- | -----------
| Type         | feature
| BC Break     | no

#### Summary

Mariadb 10.7 has new type for storing GUID (UUID), https://mariadb.org/10-7-preview-feature-uuid-data-type/

2021-11-17 00:57 UTC, derrabus requested changes
Thank you for your pull request. Since this is a new feature, please target the 3.2.x branch.

2021-11-17 00:57 UTC, derrabus commented on src/Platforms/MariaDb1070Platform.php
> + */
This doc block looks like copy&paste from the 10.2.7 platform. It should be adjusted to match what this new class actually represents.

2021-11-17 01:13 UTC, Rixafy commented
@derrabus it is a new feature, but when someone uses older doctrine/dbal with newest MariaDB, it won't recognize native guid type, will it be backported also to older versions?

2021-11-17 06:58 UTC, derrabus commented
I don't think that would be necessary. If someone uses the latest and greatest MariaDB, it's fair to have them upgrade to the latest and greatest DBAL as well.

2021-11-17 14:28 UTC, Rixafy commented
Why is that PHPUnit failing? I'm sure I fixed that in last commit, and
`Doctrine\DBAL\Tests\Platforms\MariaDb1070PlatformTest::testReturnsJsonTypeDeclarationSQL`
no longer exists.

2021-11-19 01:09 UTC, morozov commented
Since this is a type mapping change, we need to make sure if a user using GUID on PostgreSQL with DBAL 3.1 upgrades to DBAL 3.2, the schema manager will be able to migrate the schema automatically. If not, we'll to at least document the migration path.

@Rixafy please test the DBAL upgrade and document the current behavior in the comments.

2021-11-19 01:32 UTC, Rixafy commented
@morozov I don't get that note with postgres, do you mean mariadb and migration for converting from byte(16) to uuid? And also unfortunately I'm unable to test it in my projects, I'm using Nette Framework with [Nettrine](https://github.com/nettrine) extensions and it's locked to dbal 2.x versions because of migrations, I would need to update that integrations as well and it would take some time, or made stand-alone project or repo using symfony and I'm little bit bussy right now.

But I guess it may fail by default, or when there are all FK from another tables dropped before changing id type, it may work.

2021-11-19 15:53 UTC, morozov commented
> I don't get that note with postgres, do you mean mariadb and migration for converting from byte(16) to uuid?

Yes, MariaDB, sorry.

> And also unfortunately I'm unable to test it in my projects […]

You don't have to test it in your project. You can create a table with a GUID field on the previous version of the DBAL, then update the dependency and try to migrate the schema.

> But I guess it may fail by default, or when there are all FK from another tables dropped before changing id type, it may work.

Good point on foreign keys. I'd start simple with just a single column and then test the FK scenario.

2022-04-25 03:22 UTC, closed without merging

2022-04-27 07:54 UTC, fd6130 commented
Hi, does the latest dbal support mariadb 10.7 uuid type? Or currently still have to use it as binary type?

2022-04-27 10:50 UTC, Rixafy commented
> Hi, does the latest dbal support mariadb 10.7 uuid type? Or currently still have to use it as binary type?

Still binary as far as I know, I added the support but I didn't have time to test it, since I'm not even using dbal 3.