Document minor BC Break about cache keys
doctrine/dbal pull request #5059
Opened 2021-11-30 22:16 UTC by greg0ire

2021-11-30 23:25 UTC, SenseException requested changes, later dismissed

2021-11-30 23:25 UTC, SenseException commented on UPGRADE.md
> +`psr/cache instead`. To help calling our own internal APIs in a unified way, we
```suggestion
`psr/cache` instead. To help calling our own internal APIs in a unified way, we
```

2021-12-01 14:33 UTC, morozov approved these changes

2021-12-01 15:39 UTC, derrabus approved these changes

2021-12-01 21:09 UTC, merged