Fixed return type of DBAL\Connection methods
doctrine/dbal pull request #5802
Opened 2022-10-29 13:42 UTC by stephanvierkant

|      Q       |   A
|------------- | -----------
| Type         | bug/feature/improvement
| Fixed issues | n/a

#### Summary

There is no way this method `\Doctrine\DBAL\Connection::executeStatement` returns a string, so it should be removed from the docblock.

Both `\Doctrine\DBAL\Driver\Connection::exec` and `\Doctrine\DBAL\Driver\Result::rowCount` already have a native return type `int`.

2022-10-30 18:36 UTC, SenseException requested changes
I guess this can be seen as a bugfix for 3.5.

You can also adapt phpdoc of `setTransactionIsolation($level)`.

2022-10-31 06:03 UTC, derrabus requested changes
The native return type `int` of `rowCount()` and `exec()` was a mistake that will be corrected with 4.0. Those doc blocks prepare that change. We shouldn't change them.

2022-10-31 11:19 UTC, closed without merging

2023-01-25 08:15 UTC, GromNaN commented
As a user of the library, I do not expect "The number or rows" to be `string`. I have a better understanding after reading this commit https://github.com/doctrine/dbal/commit/4b68d84583fca51d2e0bac786bf5e75e107b791e

What do you think of adding a comment stating why the return type can be a string ?

Upgrading PHPStan level, my teammate blindly casted the result.
```diff
for (/* ... */)(
-    $affectedRows += $connection->executeStatement(/* ... */);
+    $affectedRows += (int) $connection->executeStatement(/* ... */);
} 
```

2023-01-25 10:06 UTC, derrabus commented
> What do you think of adding a comment stating why the return type can be a string ?

Sure, go ahead.