Explain why the number of affected rows can be a string
doctrine/dbal pull request #5872
Opened 2023-01-27 08:42 UTC by GromNaN

|      Q       |   A
|------------- | -----------
| Type         | improvement
| Fixed issues | https://github.com/doctrine/dbal/pull/5802#issuecomment-1403239263

#### Summary

Mysqli is the only driver that can return a string when the number of affected rows is greater that `PHP_INT_MAX`.

Adding a comment in order to make clear for users they can safely cast the result of `Connection::executeStatement()` to `(int)` when they don't use this driver, or the executed statement cannot update so many rows.

2023-01-27 08:49 UTC, GromNaN commented on src/Driver/PDO/Connection.php
> +    public function exec(string $sql): int
[`PDO::exec()`](https://www.php.net/manual/en/pdo.exec.php) returns `int|false`.

2023-01-27 08:49 UTC, GromNaN commented on src/Driver/SQLSrv/Connection.php
> +    public function exec(string $sql): int
[`sqlsrv_rows_affected`](https://www.php.net/manual/en/function.sqlsrv-rows-affected.php) returns `int|false`.

2023-01-27 08:49 UTC, GromNaN commented on src/Driver/OCI8/Connection.php
> +    public function exec(string $sql): int
[`oci_num_rows`](https://www.php.net/manual/en/function.oci-num-rows.php) returns `int|false`.

2023-01-28 08:29 UTC, derrabus requested changes
You are correct that only MySQLi supports row counts > `PHP_INT_MAX` at the moment. But we should not close the door here: If one of the other extensions at some point decides to support this as well, we should not be forced to issue a new major release of DBAL. Since all driver connection classes are `final`, I think your return type changes are fine.

2023-01-28 08:29 UTC, derrabus commented on UPGRADE.md
> +If the number is greater than `PHP_INT_MAX`, the number of affected rows will be returned as a `string`.
```suggestion
If the number is greater than `PHP_INT_MAX`, the number of affected rows may be returned as a string if the driver supports it.
```

As you already found out, not all drivers will act that way.

2023-01-28 08:29 UTC, derrabus commented on src/Driver/Connection.php
> +     * the number of affected rows will be returned as a string.
```suggestion
     * the number of affected rows may be returned as a string.
```

2023-01-28 20:50 UTC, GromNaN reviewed
> we should not close the door here: If one of the other extensions at some point decides to support this as well, we should not be forced to issue a new major release of DBAL.

It is wise to anticipate this. I'm OK to revert the type to `int|string` on all the driver connections, including `SQLite3\Connection` which is currently `int`.

With your last sentence, I'm not sure what's your thoughts.

2023-01-28 20:55 UTC, GromNaN commented
Seen https://github.com/doctrine/dbal/pull/5879. Thank you.

2023-01-29 13:44 UTC, derrabus approved these changes

2023-01-29 13:44 UTC, merged

2023-01-29 13:44 UTC, derrabus commented
Thanks!