Replace `@inheritDoc` tags with `@inheritdoc`
doctrine/dbal pull request #6015
Opened 2023-04-17 03:07 UTC by phansys

|      Q       |   A
|------------- | -----------
| Type         | improvement
| Fixed issues | n/a

#### Summary

Normalize the usage for the `@inheritdoc` tag.

2023-04-17 08:52 UTC, derrabus commented
This looks like something PHPCS should do.

2023-04-17 09:26 UTC, phansys commented
I agree, but I don't know if PHPCS has a specific rule for this or if the [`FunctionCommentSniff`](https://github.com/squizlabs/PHP_CodeSniffer/blob/ed8e00df0a83aa96acf703f8c2979ff33341f879/src/Standards/Squiz/Sniffs/Commenting/FunctionCommentSniff.php#L17) rule should be enough in this case.

2023-04-17 11:28 UTC, greg0ire commented
Can you please open an issue about this on https://github.com/slevomat/coding-standard ?

2023-04-17 11:59 UTC, derrabus requested changes
Unless we can have this fixed by PHPCS, I'd like to keep everything as inconsistent as it is.

2023-04-17 17:24 UTC, phansys commented
>Can you please open an issue about this on https://github.com/slevomat/coding-standard ?


Seems that both variants are intentionally allowed there. See:
* https://github.com/slevomat/coding-standard/blob/c831e3aa3aeed3e0c4c7cabc3a35652347ea9e50/SlevomatCodingStandard/Sniffs/Commenting/UselessInheritDocCommentSniff.php#L51-L53 (`i` modifier is used for the regex);
* https://github.com/slevomat/coding-standard/blob/c831e3aa3aeed3e0c4c7cabc3a35652347ea9e50/SlevomatCodingStandard/Helpers/DocCommentHelper.php#L120 (`stripos()` is called instead of `strpos()`).

2023-04-17 17:59 UTC, greg0ire commented
I believe both are correct and mean the same thing, but I might be wrong. The sniff that detects such comments that are useless should absolutely detect both. The helper should also detect both.
If they both mean the same thing, then it's a matter of style, and a rule to pick one style over the other is 100% the job of a coding standard.

2023-04-21 16:58 UTC, phansys commented
>Unless we can have this fixed by PHPCS, I'd like to keep everything as inconsistent as it is.

@derrabus: doctrine/coding-standard#311.

2023-04-24 18:45 UTC, phansys commented on composer.json
> +        "doctrine/coding-standard": "12.0.0",
BTW, if we are releasing new CS rules from "doctrine/coding-standard" only in major versions, couldn't we use `^12.0` here?

2023-04-24 18:49 UTC, greg0ire commented on composer.json
> +        "doctrine/coding-standard": "12.0.0",
You're right, we probably should… not sure why we are pinning this one.

2023-04-24 19:50 UTC, greg0ire approved these changes

2023-04-24 21:12 UTC, derrabus approved these changes

2023-04-24 21:13 UTC, merged