partial fix for json field with default value
doctrine/dbal pull request #6041
Opened 2023-05-16 02:51 UTC by bilogic

1. fixes #6037
2. the affected funciton `getDefaultValueDeclarationSQL` was never directly referenced in any tests
3. all other tests are passing

2023-05-22 23:14 UTC, phansys requested changes

2023-05-22 23:14 UTC, phansys commented on src/Platforms/AbstractPlatform.php
> +        if ($type instanceof Types\JsonType && in_array(strtoupper($default), ['JSON_ARRAY()', 'JSON_OBJECT()'])) {
```suggestion
        if ($type instanceof Types\JsonType && in_array(strtoupper($default), ['JSON_ARRAY()', 'JSON_OBJECT()'], true)) {
```

2023-05-25 10:39 UTC, derrabus commented
Related issue: #5689

2023-05-25 10:52 UTC, derrabus commented
Thank you for your PR. However, we don't merge changes without tests.

The referenced bug report does not provide a reproducer for DBAL, but uses wrapper APIs from Laravel. To me, it looks like Laravel advertises a feature that DBAL does not provide, expressions as default values. This is why I'm not convinced, this is actually a bug (on our side).

Moreover, your change does not add that feature, it merely implements a workaround for two cases, `JSON_ARRAY()` and `JSON_OBJECT()`. Merging it is a slippery slope because why would we support `JSON_ARRAY()`, but not `JSON_ARRAY( )` or `JSON_ARRAY(1, 2, 3)`?

I'm open to discuss how expressions as default values can be implemented. But I don't think that this PR is the right way, sorry.

2023-06-05 20:59 UTC, closed without merging