Add support for unlogged tables in PostgreSQL
doctrine/dbal pull request #6046
Opened 2023-05-24 12:24 UTC by f-lombardo

|      Q       |   A
|------------- | -----------
| Type         | bug/feature/improvement
| Feature | see #6044 

#### Summary

Add support for creating unlogged PostgreSQL tables:
https://www.postgresql.org/docs/current/sql-createtable.html

I added a boolean `unlogged` option to `default_table_options` doctrine configuration
https://www.doctrine-project.org/projects/doctrine-bundle/en/latest/configuration.html
For example:

doctrine:
    dbal:
        default_table_options:
            unlogged: true

2023-05-25 10:32 UTC, derrabus commented
Thank you. As always, we need functional tests that prove that your change actually works. Assertions on generated SQL are never sufficient.

In this case, the following scenarios must be covered:

* Create a table with that new option.
* Introspect logged and unlogged tables.
* Compare a logged with an unlogged table and vice versa.
* What happens if I use that option on a database that does not support it?

2023-05-25 10:33 UTC, derrabus commented
Since this is a new feature and 3.6.x is closed for features, I'm targeting the 3.7.x branch now. Please rebase your PR onto that branch to make sure you don't run into merge conflicts.

2023-05-25 14:20 UTC, f-lombardo commented
>     * What happens if I use that option on a database that does not support it?

I think nothing should happen, since the option shouldn't be used by any other db driver

2023-05-25 22:28 UTC, SenseException commented
`UNLOGGED` was introduced in 9.1, if I believe what the docs say. At least this isn't breaking between versions supported by DBAL.

What's the use case that made you create the PR for adding this new feature?

2023-05-26 20:56 UTC, f-lombardo commented
> What's the use case that made you create the PR for adding this new feature?
I have many Behat tests that read/write data on PostgreSQL DBs and I'd like to run them faster. As I'm using test data, I'm not concerned about possible data corruption in case of crashes.

2023-06-05 20:57 UTC, derrabus requested changes

2023-06-05 20:57 UTC, derrabus commented on tests/Functional/Driver/PDO/PgSQL/DBAL6044Test.php
> +/** @requires extension pdo_pgsql */
```suggestion
```

No, it doesn't.

2023-06-05 20:57 UTC, derrabus commented on tests/Functional/Driver/PDO/PgSQL/DBAL6044Test.php
> +        if (TestUtil::isDriverOneOf('pdo_pgsql')) {
The test should be executed with the `pgsql` driver as well.

2023-06-05 20:57 UTC, derrabus commented on tests/Functional/Driver/PDO/PgSQL/DBAL6044Test.php
> +        $this->assertEquals($unloggedTable->getName(), $validationTable->getName());
Performing assertions on the table name does not make sense here. We already have tests that make sure a tables does not change its name unexpectedly.

Instead, we need to make sure, the new "unlogged" option is introspected correctly.

2023-06-07 08:57 UTC, derrabus approved these changes

2023-06-07 09:00 UTC, merged

2023-06-07 09:00 UTC, derrabus commented
Thank you!

2023-06-07 09:23 UTC, f-lombardo commented
> Thank you!

It was a pleasure! 
Do you think we should also edit documentation about this new feature?

2023-06-07 09:35 UTC, derrabus commented
Sure, go ahead!

2023-06-07 09:52 UTC, f-lombardo commented
> Sure, go ahead!

I'm looking at the docs folder and I'm a bit confused. What docs do yo think I should edit?

2023-06-07 09:57 UTC, derrabus commented
> I'm a bit confused

Why's that?

2023-06-08 07:17 UTC, f-lombardo commented
> 

I don't understand where to put this new information, since I haven't found any part of the documentation regarding the already existing table options for MySQL.

2023-06-08 11:20 UTC, derrabus commented
There a chapter on schema representation. This is where this piece of information fits best, I'd say. But note that…

https://github.com/doctrine/dbal/blob/4e673be0ecad4ee4fd68c55f686edc098df6a047/docs/en/reference/schema-representation.rst?plain=1#L77

2023-08-22 09:07 UTC, f-lombardo commented
Hi @derrabus , do you already have a planned date for a release containing this feature?

Thanks.

2023-08-22 09:21 UTC, derrabus commented
No. But I realize that there are already some features waiting to be released, so I don't want to wait too long either. That being said, you can use the feature already by using a 3.7.x-dev snapshot.

2023-10-05 14:02 UTC, f-lombardo commented
Any news about release dates for this update?

2023-10-05 14:03 UTC, greg0ire commented
Yes.

![2023-10-05_16-03](https://github.com/doctrine/dbal/assets/657779/4c5b0139-d2b5-4b75-a40a-ac7a239f3425)