Document alternative to Type::getName
doctrine/dbal pull request #6077
Opened 2023-06-28 18:58 UTC by Tofandel

|      Q       |   A
|------------- | -----------
| Type         | Improvement
| Fixed issues |  #6076 
#### Summary

Simply document the deprecation with an alternative and fix a type

2023-06-28 19:08 UTC, greg0ire approved these changes, later dismissed

2023-06-28 22:40 UTC, SenseException approved these changes

2023-06-28 22:43 UTC, SenseException requested changes, later dismissed
At least ✅ after you fix the line length of the phpdoc

2023-06-29 09:31 UTC, derrabus commented on src/Types/Type.php
> +     * You should use Type::getTypeRegistry()->lookupName($type) instead.
```suggestion
     * @deprecated this method will be removed in Doctrine DBAL 4.0,
     *             use {@ see TypeRegistry::lookupName()} instead.
```

2023-06-29 10:01 UTC, derrabus approved these changes

2023-06-29 10:28 UTC, merged