Apply the connection filter to indexes
doctrine/dbal pull request #6099
Opened 2023-07-17 14:16 UTC by allenisalai

|      Q       |   A
|------------- | -----------
| Type         | improvement
| Fixed issues | #5420

#### Summary

When there are indexes that are not supported by doctrne present in a database, they will consistently create "DROP" migrations.  By applying the schema filter to the indexes one will be able to exclude these indexes from future migrations preventing the manual work of removing the DROP statement each time a migration is created.

2023-07-19 12:27 UTC, derrabus requested changes
This change is problematic. Until now, `listTableIndexes()` did not take the assets filter into account. In fact, that filter is not applied to indexes at all at the moment, IIRC.

That means that your change will break apps that don't expect the filter to be applied or that don't expect the filter function to be called with an index name.

2023-07-19 12:27 UTC, derrabus commented on src/Schema/AbstractSchemaManager.php
> +            },
```suggestion
            static fn (Index $i): bool => $filter($i->getName()),
```

2023-07-19 12:27 UTC, derrabus commented on src/Schema/AbstractSchemaManager.php
> +     * @return array<int|string, Index>
```suggestion
     * @param Index[] $indexes
     *
     * @return Index[]
```

2023-07-19 12:37 UTC, derrabus commented
Regarding your motivation: Your problem is that you database contains indexes that DBAL is not able to introspect properly. It does not feel right to leverage the asset filter to anticipate which indexes DBAL will choke on.

Reading @morozov's comments on #5420, I'm leaning towards removing the assets filter from the DBAL rather than using it as a general hook for workarounds.

In other words: I recognize the issue that you're having, but I'm not convinced that the assets filter is the best tool to solve it.

2023-07-20 15:50 UTC, allenisalai commented
Do you feel this direction is worth continuing to pursue?  I have a plan to make it backwards compatible but based on your comment the work seems moot. 

Would my `CustomIndex` idea outlined https://github.com/doctrine/dbal/issues/5420#issuecomment-1622254141 make
any more sense? It does feel a little counter intuitive to an Abstraction Layer..

2023-07-20 16:27 UTC, derrabus commented
> Do you feel this direction is worth continuing to pursue? I have a plan to make it backwards compatible but based on your comment the work seems moot.

Generally sepaking: _if_ we have an asset filter, it kinda makes sense that we're able to filer _all_ assets. That fact that indexes are excluded feels arbitrary.

My problem is with your motivation behind it because the assets filter is not meant as a way to anticipate which assets the DBAL is going to error on.

> Would my `CustomIndex` idea outlined [#5420 (comment)](https://github.com/doctrine/dbal/issues/5420#issuecomment-1622254141) make any more sense? It does feel a little counter intuitive to an Abstraction Layer..

The ORM uses DBAL's schema classes to model the database schema. As long as the DBAL cannot handle whatever you configure with that `CustomIndex` annotation, you won't be able to implement that idea.

2023-08-18 17:34 UTC, allenisalai commented
I made my changes BC by adding an interface that will check all assets when used as a filter.

2024-01-02 03:01 UTC, closed without merging