Enum support
doctrine/dbal pull request #6347
Opened 2024-03-22 00:21 UTC by bigfoot90

I'm migrating a project to DBAL 4.
This is initial support for native ENUM type.
A custom mapping type is used in the ORM side.

|      Q       |   A
|------------- | -----------
| Type         | feature
| Fixed issues | --

#### Summary

This change allows to track ENUM members in order to be able to generate right migration.

If this is welcome and you like it, I can continue to work on this feature adding some tests

2024-03-22 07:49 UTC, derrabus commented
Thank you for your contribution. However, we don't merge any changes that aren't covered by tests.

2024-03-24 09:41 UTC, derrabus requested changes
Your feature is not tested against any database. Please have a look at our existing _functional_ tests and add some that cover your feature.

2024-03-24 20:58 UTC, bigfoot90 commented
**UPDATE:** It maps to string by default.
It also supports mapping to php Enum or custom class setting `enumClassname` property while registering type.

Provided functional test in `tests/Functional/Types/EnumTest.php`

2024-03-24 21:41 UTC, derrabus commented
* The functional test only covers happy cases.
* Schema introspection and comparison aren't covered at all.

2024-03-24 22:04 UTC, bigfoot90 commented
What are unhappy cases?
Where I can take a look for missing tests?
Please help

2024-03-25 06:53 UTC, derrabus commented
https://en.wikipedia.org/wiki/Happy_path

2024-03-25 14:44 UTC, bigfoot90 commented
Sorry but it don't help me. I know what is Happy path.
I'm asking what do you mean for "unhappy" for the Enum case.
Can you provide any example?

Also where I can found similar **Schema introspection** and **comparison** tests so I can see and write the missing cases

2024-03-25 14:55 UTC, derrabus commented
> I'm asking what do you mean for "unhappy" for the Enum case. Can you provide any example?

* Store a value that is not part of the enum.
* Store a value that has the wrong type (boolean, DateTime, …).
* Store a value from a different enum.
* Retrieve a value from the database that is not part of the enum.

> Also where I can found similar **Schema introspection** and **comparison** tests so I can see and write the missing cases

All tests in `Doctrine\DBAL\Tests\Functional\Schema` deal with that topic.

2024-03-26 23:36 UTC, bigfoot90 commented
@derrabus Wrote Functional tests. You can review. 
I need to run CI on all supported platforms

2024-03-26 23:54 UTC, bigfoot90 commented
It seems that CHANCH/ALTER COLUMN functionality is not supported on SQLite.

2024-03-27 00:14 UTC, derrabus commented
> It seems that CHANCH/ALTER COLUMN functionality is not supported on SQLite.

That is correct, see https://www.sqlite.org/lang_altertable.html

2024-03-27 11:56 UTC, bigfoot90 commented
Also there is not better way to inspect CHECK constraints on SQLite
This is the only way https://stackoverflow.com/questions/20813007/how-to-list-out-check-constraints-in-a-sqlite-table

Should we drop support for SQLite platform or fallback to TEXT type without CHECK constraint?

2024-03-27 13:11 UTC, greg0ire commented
If this cannot be implemented on all platforms, then I don't think we should support enums at all, sorry.

2024-03-27 13:41 UTC, derrabus requested changes

2024-03-27 13:41 UTC, derrabus commented on src/Schema/MySQLSchemaManager.php
> +        if ($dbType === 'enum' && preg_match_all("/'([^']+)'/", $tableColumn['type'], $members) !== false) {
`preg_match_all()` returns `false` only if an error occurred, for instance if the regular expression is invalid. I'm pretty sure that's not the case you wanted to catch here.

2024-03-27 13:41 UTC, derrabus commented on src/Types/EnumType.php
> +    public ?string $enumClassname = null;
Should this be a constructor parameter? Is the class even usable without a class name? Why is this public?

2024-03-27 13:41 UTC, derrabus commented on src/Types/EnumType.php
> +    public string $name = 'enum';
What's the purpose of this property? Types are usually unaware of the name(s) under which they've been registered.

2024-03-27 13:41 UTC, derrabus commented on src/Types/EnumType.php
> +    }
Doesn't the database type that we map to depend on the platform?

2024-03-27 13:41 UTC, derrabus commented on src/Types/EnumType.php
> +                static fn (string $value) => sprintf('\'%s\'', $value),
The platform should know better how to properly quote and escape a string.

2024-03-27 13:41 UTC, derrabus commented on src/Types/EnumType.php
> +            default => sprintf('ENUM(%s)', $values),
Isn't `ENUM()` a MySQL-specific SQL extension? In that case, it does not look like a reasonable default.

That being said, the platform classes exist so we don't have to do this SQL dialect limbo anywhere but in those platform classes. Move this logic into the platforms, please.

2024-03-27 13:41 UTC, derrabus commented on src/Types/EnumType.php
> +    public function convertToDatabaseValue($value, AbstractPlatform $platform): ?string
```suggestion
    public function convertToDatabaseValue(mixed $value, AbstractPlatform $platform): ?string
```

Why did your remove the parameter type?

2024-03-27 13:41 UTC, derrabus commented on src/Types/EnumType.php
> +            return $value->name;
If an enum is not backed, we don't know its scalar representation. No guesswork please. That means, we can only support backed enums.

2024-03-27 13:41 UTC, derrabus commented on src/Types/EnumType.php
> +            if (! $value instanceof Stringable) {
Why are we dealing with stringables here? I thought this is an enum type?

2024-03-27 13:41 UTC, derrabus commented on src/Types/EnumType.php
> +        return (string) $value;
Again, no guesswork please. This type is responsible for writing enums into the database. If the passed value is not an enum, this class shouldn't guess what to do with it.

2024-03-27 13:41 UTC, derrabus commented on src/Types/EnumType.php
> +        if (! is_string($value)) {
So, we don't support integer-backed enums?

2024-03-27 13:41 UTC, derrabus commented on tests/Functional/Schema/ComparatorTestUtils.php
> +        var_dump($diff->getModifiedColumns()[0]);
Forgot your debug code?

2024-03-27 13:41 UTC, derrabus commented on tests/Functional/Schema/MySQL/ComparatorTest.php
> +        ComparatorTestUtils::assertDiffNotEmpty($this->connection, $this->comparator, $table);
It's good that the diff is not empty, but we should actually have an opinion on what is in that diff, shouldn't we.

2024-03-27 13:43 UTC, derrabus commented
Dropping support for SQLite is not an option. We must make sure, our type is usable on all platforms in some shape or form.

2024-03-27 13:45 UTC, derrabus commented
Please have a look at the errors reported by PHPCS and PHPStan. You can run those tools locally.

2024-07-04 03:01 UTC, closed without merging