Add PHP 8.4 to CI
doctrine/dbal pull request #6348
Opened 2024-03-24 11:42 UTC by andreybolonin

|      Q       |   A
|------------- | -----------
| Type         | bug/feature/improvement
| Fixed issues | 

#### Summary

2024-03-24 12:00 UTC, greg0ire commented
:thinking: isn't this a bit premature?

2024-03-30 08:18 UTC, derrabus commented
> 🤔 isn't this a bit premature?

I don't think so. We can start running the CI against PHP 8.4, but if we do, we should test all extensions and not just SQLite.

2024-03-30 16:04 UTC, andreybolonin commented
@derrabus updated

2024-04-03 19:59 UTC, derrabus requested changes

2024-04-03 19:59 UTC, derrabus commented on .github/workflows/continuous-integration.yml
> +            extension: "pdo_mysql"
We need to test with both extensions!

2024-04-03 19:59 UTC, derrabus commented on .github/workflows/continuous-integration.yml
> +            extension: "pdo_mysql"
Same here

2024-04-03 19:59 UTC, derrabus commented
And please target 3.8.x for this PR.

2024-05-10 14:47 UTC, closed without merging

2024-05-10 20:46 UTC, derrabus commented
🤷🏻‍♂️