MySQL 8.4 removed keywords
doctrine/dbal pull request #6408
Opened 2024-05-16 17:38 UTC by wmouwen

|      Q       |   A
|------------- | -----------
| Type         | improvement
| Fixed issues | none

#### Summary

PR doctrine/dbal#6385 added MySQL 8.4 support by extending the list of reserved keywords. MySQL 8.4 freed up several keywords as well.

https://dev.mysql.com/doc/refman/8.4/en/keywords.html#keywords-removed-in-current-series

This PR removes the freed keywords from the list.

Branch 3.9.x was targeted to stay in line with doctrine/dbal#6385 given that there hasn't been a new release yet either.

2024-05-16 20:03 UTC, SenseException requested changes

2024-05-16 20:03 UTC, SenseException commented on src/Platforms/Keywords/MySQL84Keywords.php
> +            'MASTER_ZSTD_COMPRESSION_LEVEL',
The only keywords that are implemented in the parent keyword classes are `MASTER_BIND` and `MASTER_SSL_VERIFY_SERVER_CERT`. We currently don't need all the other ones.

Please also check the tests and create one that covers your changes.

2024-05-17 06:18 UTC, greg0ire approved these changes

2024-05-17 06:20 UTC, derrabus approved these changes

2024-05-17 06:22 UTC, merged