feat: add support for function as default value
doctrine/dbal pull request #6441
Opened 2024-06-14 14:57 UTC by vencakrecl

|      Q       |   A
|------------- | -----------
| Type         | feature
| Fixed issues | 

#### Summary
Added support for function as default value, for example `id UUID NOT NULL DEFAULT gen_random_uuid()`

2024-06-19 14:05 UTC, derrabus requested changes
Thank you. Please add functional tests that cover the creation, introspection and comparison of columns with this kind of default value. The test that you provided never hits a database, so I don't really know if your change actually works.

2024-06-19 14:07 UTC, derrabus commented
Also, please keep in mind that we only allow bugfixes on the 3.8.x branch. Your change however adds new functionality. For that, please target 4.1.x.

2024-07-07 22:05 UTC, vencakrecl commented
@derrabus I added a functional test, see https://github.com/doctrine/dbal/pull/6441/commits/24a2b4aeb619de0d094f84d00de384445b3c33e2

2024-07-08 08:02 UTC, derrabus commented
Schema comparison is still not covered.

2024-07-08 18:50 UTC, derrabus requested changes

2024-07-08 18:50 UTC, derrabus commented on tests/Functional/Schema/DefaultValueTest.php
> +        );
This is good! Now, what happens if the introspected table…

* … has no default?
* … has a literal value as default?
* … has `NULL` as default?
* … has a different expression as default?

In that case, we would expect the schema manager to execute the proper SQL to migrate the deployed table and we need to verify that this migration performed successfully.

This has to be covered with tests as well.

Sames goes for the opposite direction: The schema deployed to the database has a column with a default expression and we want to change that to a literal, `NULL`, no default or a different expression.

2025-01-17 03:02 UTC, closed without merging